// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: BokehBlur
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_BokehBlur {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct padded_1 {
    float radius;
    float highlightGain;
    float highlightThreshold;
    float bladeCount;
    float bladeRotation;
    float chromaticFringe;
    float _opacity;
    float _pad0;
};

struct struct_1 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    padded_1 n_x;
    padded n_child;
    struct_1 _sys;
};

struct item {
    float radius;
    float highlightGain;
    float highlightThreshold;
    float rotCos;
    float rotSin;
    float chromaticFringe;
    float inputWidth;
    float inputHeight;
};

static float4 unpremultiplyAlpha(float4 color2) {
    const float alpha = color2.w;
    const float3 straightRGB = select(float3(0), ((color2.xyz / alpha)), ((alpha > 1.0e-3f)));
    return float4(straightRGB, alpha);
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float4 overComposite(float4 base, float3 blended, float overlayAlpha) {
    const float baseWeight = ((base.w * ((1.0f - overlayAlpha))));
    const float finalAlpha = ((overlayAlpha + baseWeight));
    const float3 rgb = ((((blended * overlayAlpha)) + ((base.xyz * baseWeight))));
    return float4(rgb, finalAlpha);
}

static float4 blend_normal(float4 base, float4 overlay2, float opacity) {
    const float overlayAlpha = ((overlay2.w * opacity));
    return overComposite(base, overlay2.xyz, overlayAlpha);
}

static float bokehHighlightWeight(float4 base, float threshold, float gain, float rim) {
    const float lum = dot(base.xyz, float3(0.2125999927520752f, 0.7152000069618225f, 0.0722000002861023f));
    const float hi = smoothstep(threshold, ((threshold + 0.35f)), lum);
    return ((((1.0f + ((((gain * hi)) * hi)))) * rim));
}

static void bokehGather(uint cx, uint cy, texture2d<float> input, texture2d<float, access::write> output, constant item& params, constant metal::array<float4, 100>& taps) {
    auto p = ((&params));
    const float radius = ((*p)).radius;
    const float inputCx = ((((((((float(cx) + 0.5f)) * ((*p)).inputWidth)) / 1024.0f)) - 0.5f));
    const float inputCy = ((((((((float(cy) + 0.5f)) * ((*p)).inputHeight)) / 768.0f)) - 0.5f));
    const int inputWm1 = int(((((*p)).inputWidth - 1.0f)));
    const int inputHm1 = int(((((*p)).inputHeight - 1.0f)));
    if ((((radius < 0.5f)))) {
        const int sx = clamp(int(rint(inputCx)), 0, inputWm1);
        const int sy = clamp(int(rint(inputCy)), 0, inputHm1);
        const float4 texel = input.read(uint2(uint(sx), uint(sy)), 0);
        output.write(texel, uint2(cx, cy));
    } else {
        const float gain = ((*p)).highlightGain;
        const float threshold = ((*p)).highlightThreshold;
        const float fringe = ((*p)).chromaticFringe;
        const float rotC = ((*p)).rotCos;
        const float rotS = ((*p)).rotSin;
        float3 accum = float3(0);
        float alphaAccum = 0.0f;
        float wSum = 0.0f;
        for (int i = 0; ((i < 100)); i++) {
            auto tap = ((&taps[i]));
            const float ox = ((((((*tap)).x * rotC)) - ((((*tap)).y * rotS))));
            const float oy = ((((((*tap)).x * rotS)) + ((((*tap)).y * rotC))));
            const float2 off = float2(((ox * radius)), ((oy * radius)));
            const int sx = clamp(int(rint(((inputCx + off.x)))), 0, inputWm1);
            const int sy = clamp(int(rint(((inputCy + off.y)))), 0, inputHm1);
            const float4 base = input.read(uint2(uint(sx), uint(sy)), 0);
            float colR = base.x;
            float colB = base.z;
            if ((((fringe > 1.0e-3f)))) {
                const float2 offR = ((off * ((1.0f + ((fringe * 0.5f))))));
                const int rx = clamp(int(rint(((inputCx + offR.x)))), 0, inputWm1);
                const int ry = clamp(int(rint(((inputCy + offR.y)))), 0, inputHm1);
                colR = input.read(uint2(uint(rx), uint(ry)), 0).x;
                const float2 offB = ((off * ((1.0f - ((fringe * 0.5f))))));
                const int bx = clamp(int(rint(((inputCx + offB.x)))), 0, inputWm1);
                const int by = clamp(int(rint(((inputCy + offB.y)))), 0, inputHm1);
                colB = input.read(uint2(uint(bx), uint(by)), 0).z;
            }
            const float3 col = float3(colR, base.y, colB);
            const float w = bokehHighlightWeight(base, threshold, gain, ((*tap)).z);
            accum = ((accum + ((col * w))));
            alphaAccum = ((alphaAccum + ((base.w * w))));
            wSum = ((wSum + w));
        }
        const float invW = ((1.0f / max(wSum, 1.0e-4f)));
        output.write(float4(((accum * invW)), ((alphaAccum * invW))), uint2(cx, cy));
    }
}
} // namespace S_BokehBlur

using namespace S_BokehBlur;

fragment float4 BokehBlur_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    float4 composed_0 = unpremultiplyAlpha(compute_0.sample(linearClamp, uv));
    return composed_0;
}

fragment float4 BokehBlur_v0_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

static void BokehBlur_k0_body(uint cx, uint cy, uint _arg_2, texture2d<float> input, texture2d<float, access::write> output, constant item& params, constant metal::array<float4, 100>& taps) {
    bokehGather(cx, cy, input, output, params, taps);
}

kernel void BokehBlur_k0(uint3 sk_gid [[thread_position_in_grid]], texture2d<float> input [[texture(0)]], texture2d<float, access::write> output [[texture(1)]], constant item& params [[buffer(0)]], constant metal::array<float4, 100>& taps [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    BokehBlur_k0_body(sk_gid.x, sk_gid.y, sk_gid.z, input, output, params, taps);
}
