// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: Chrome
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_Chrome {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float2 center;
    float scale;
    float rotation;
    float4 tint;
    float4 warmColor;
    float4 coolColor;
    float bevelWidth;
    float bevelShape;
    float curvature;
    float waviness;
    float environment;
    float envRotation;
    float softness;
    float spectral;
    float dispersion;
    float shadows;
    float speed;
    float edgeSoftness;
    float _opacity;
    float _animTime;
    float _vfOriginX;
    float _vfOriginY;
    float _vfSpanX;
    float _vfSpanY;
    float _vfActiveRes;
    float _vfRBound;
    float _saRadius;
    float _saSides;
    float _saRounding;
    float _saInnerRatio;
    float _saRotation;
    float _saHeight;
    float _saOffset;
    float _saAperture;
};

struct struct_2 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    struct_1 n_x;
    struct_2 _sys;
};

struct RotStruct {
    float cx;
    float sx;
    float cy;
    float sy;
    float cz;
    float sz;
    char _sk_pad0[8];
};

struct MarchParams {
    RotStruct rot;
    float rBound;
    float spanX;
    float spanY;
    float originX;
    float originY;
    uint activeRes;
    float pA;
    float pB;
    float pC;
    float pD;
    float3 mb0;
    float3 mb1;
    float3 mb2;
    float3 mb3;
    float3 mb4;
    float3 mb5;
    float3 mb6;
    float3 mb7;
};

static float2 sdfSpaceUV(float2 center, float scale, float rotation, float2 uv, float aspect) {
    const float centerX = center.x;
    const float centerY = ((1.0f - center.y));
    const float dxAc = ((((uv.x - centerX)) * aspect));
    const float dy = ((uv.y - centerY));
    const float rotRad = ((rotation * 0.017453292519943295f));
    const float cosR = cos(rotRad);
    const float sinR = sin(rotRad);
    const float rdx = ((((dxAc * cosR)) + ((dy * sinR))));
    const float rdy = ((((dy * cosR)) - ((dxAc * sinR))));
    return float2(((((rdx / scale)) + 0.5f)), ((((rdy / scale)) + 0.5f)));
}

static float4 fieldSampleArg(float2 uv, texture2d<float> field, float originX, float originY, float spanX, float spanY, float activeResF, float rBound) {
    const float uxc = clamp(uv.x, originX, ((originX + spanX)));
    const float uyc = clamp(uv.y, originY, ((originY + spanY)));
    const float outsideDist = length(float2(((uv.x - uxc)), ((uv.y - uyc))));
    const float px = ((((((((uxc - originX)) / spanX)) * activeResF)) - 0.5f));
    const float py = ((((((((uyc - originY)) / spanY)) * activeResF)) - 0.5f));
    const float x0 = floor(px);
    const float y0 = floor(py);
    const float fx = ((px - x0));
    const float fy = ((py - y0));
    const float tx2 = ((fx * fx));
    const float tx3 = ((tx2 * fx));
    const float wx0 = ((((((tx3 * (-0.5f))) + tx2)) - ((fx * 0.5f))));
    const float wx1 = ((((((tx3 * 1.5f)) - ((tx2 * 2.5f)))) + 1.0f));
    const float wx2 = ((((((tx3 * (-1.5f))) + ((tx2 * 2.0f)))) + ((fx * 0.5f))));
    const float wx3 = ((((tx3 * 0.5f)) - ((tx2 * 0.5f))));
    const float ty2 = ((fy * fy));
    const float ty3 = ((ty2 * fy));
    const float wy0 = ((((((ty3 * (-0.5f))) + ty2)) - ((fy * 0.5f))));
    const float wy1 = ((((((ty3 * 1.5f)) - ((ty2 * 2.5f)))) + 1.0f));
    const float wy2 = ((((((ty3 * (-1.5f))) + ((ty2 * 2.0f)))) + ((fy * 0.5f))));
    const float wy3 = ((((ty3 * 0.5f)) - ((ty2 * 0.5f))));
    const float maxT = ((activeResF - 1.0f));
    const uint cxm = wgsl_f2u(clamp(((x0 - 1.0f)), 0.0f, maxT));
    const uint cx0 = wgsl_f2u(clamp(x0, 0.0f, maxT));
    const uint cx1 = wgsl_f2u(clamp(((x0 + 1.0f)), 0.0f, maxT));
    const uint cx2 = wgsl_f2u(clamp(((x0 + 2.0f)), 0.0f, maxT));
    const uint cym = wgsl_f2u(clamp(((y0 - 1.0f)), 0.0f, maxT));
    const uint cy0 = wgsl_f2u(clamp(y0, 0.0f, maxT));
    const uint cy1 = wgsl_f2u(clamp(((y0 + 1.0f)), 0.0f, maxT));
    const uint cy2 = wgsl_f2u(clamp(((y0 + 2.0f)), 0.0f, maxT));
    const float4 k00 = field.read(uint2(cxm, cym), 0);
    const float4 k01 = field.read(uint2(cx0, cym), 0);
    const float4 k02 = field.read(uint2(cx1, cym), 0);
    const float4 k03 = field.read(uint2(cx2, cym), 0);
    const float4 k10 = field.read(uint2(cxm, cy0), 0);
    const float4 k11 = field.read(uint2(cx0, cy0), 0);
    const float4 k12 = field.read(uint2(cx1, cy0), 0);
    const float4 k13 = field.read(uint2(cx2, cy0), 0);
    const float4 k20 = field.read(uint2(cxm, cy1), 0);
    const float4 k21 = field.read(uint2(cx0, cy1), 0);
    const float4 k22 = field.read(uint2(cx1, cy1), 0);
    const float4 k23 = field.read(uint2(cx2, cy1), 0);
    const float4 k30 = field.read(uint2(cxm, cy2), 0);
    const float4 k31 = field.read(uint2(cx0, cy2), 0);
    const float4 k32 = field.read(uint2(cx1, cy2), 0);
    const float4 k33 = field.read(uint2(cx2, cy2), 0);
    const float rAcc = ((((((((((((((((((((((((((((((((((k00.r * wx0)) * wy0)) + ((((k01.r * wx1)) * wy0)))) + ((((k02.r * wx2)) * wy0)))) + ((((k03.r * wx3)) * wy0)))) + ((((k10.r * wx0)) * wy1)))) + ((((k11.r * wx1)) * wy1)))) + ((((k12.r * wx2)) * wy1)))) + ((((k13.r * wx3)) * wy1)))) + ((((k20.r * wx0)) * wy2)))) + ((((k21.r * wx1)) * wy2)))) + ((((k22.r * wx2)) * wy2)))) + ((((k23.r * wx3)) * wy2)))) + ((((k30.r * wx0)) * wy3)))) + ((((k31.r * wx1)) * wy3)))) + ((((k32.r * wx2)) * wy3)))) + ((((k33.r * wx3)) * wy3))));
    const float aAcc = ((((((((((((((((((((((((((((((((((k00.a * wx0)) * wy0)) + ((((k01.a * wx1)) * wy0)))) + ((((k02.a * wx2)) * wy0)))) + ((((k03.a * wx3)) * wy0)))) + ((((k10.a * wx0)) * wy1)))) + ((((k11.a * wx1)) * wy1)))) + ((((k12.a * wx2)) * wy1)))) + ((((k13.a * wx3)) * wy1)))) + ((((k20.a * wx0)) * wy2)))) + ((((k21.a * wx1)) * wy2)))) + ((((k22.a * wx2)) * wy2)))) + ((((k23.a * wx3)) * wy2)))) + ((((k30.a * wx0)) * wy3)))) + ((((k31.a * wx1)) * wy3)))) + ((((k32.a * wx2)) * wy3)))) + ((((k33.a * wx3)) * wy3))));
    const float4 bl = mix(mix(k11, k12, fx), mix(k21, k22, fx), fy);
    const float rMin = min(min(k11.r, k12.r), min(k21.r, k22.r));
    const float rMax = max(max(k11.r, k12.r), max(k21.r, k22.r));
    const float aMin = min(min(k11.a, k12.a), min(k21.a, k22.a));
    const float aMax = max(max(k11.a, k12.a), max(k21.a, k22.a));
    const float aOut = clamp(aAcc, aMin, aMax);
    const float rNear = ((clamp(rAcc, rMin, rMax) + outsideDist));
    const float rCircle = ((length(float2(((uv.x - 0.5f)), ((uv.y - 0.5f)))) - rBound));
    const float rOut = mix(rNear, max(rCircle, rNear), smoothstep(0.0f, 0.25f, outsideDist));
    return float4(rOut, bl.g, bl.b, aOut);
}

static bool outsideShape(float sdf, float pxH) {
    return ((sdf > ((pxH * 2.0f))));
}

static float3 perspectiveViewRay(float2 uv, float aspect, float fov) {
    return normalize(float3(((((((uv.x - 0.5f)) * aspect)) * fov)), ((((uv.y - 0.5f)) * fov)), 1.0f));
}

static float4 fieldSampleFastArg(float2 uv, texture2d<float> field, float originX, float originY, float spanX, float spanY, float activeResF, float rBound) {
    const float uxc = clamp(uv.x, originX, ((originX + spanX)));
    const float uyc = clamp(uv.y, originY, ((originY + spanY)));
    const float outsideDist = length(float2(((uv.x - uxc)), ((uv.y - uyc))));
    const float px = ((((((((uxc - originX)) / spanX)) * activeResF)) - 0.5f));
    const float py = ((((((((uyc - originY)) / spanY)) * activeResF)) - 0.5f));
    const float x0 = floor(px);
    const float y0 = floor(py);
    const float fx = ((px - x0));
    const float fy = ((py - y0));
    const float maxT = ((activeResF - 1.0f));
    const uint cx0 = wgsl_f2u(clamp(x0, 0.0f, maxT));
    const uint cx1 = wgsl_f2u(clamp(((x0 + 1.0f)), 0.0f, maxT));
    const uint cy0 = wgsl_f2u(clamp(y0, 0.0f, maxT));
    const uint cy1 = wgsl_f2u(clamp(((y0 + 1.0f)), 0.0f, maxT));
    const float4 t00 = field.read(uint2(cx0, cy0), 0);
    const float4 t10 = field.read(uint2(cx1, cy0), 0);
    const float4 t01 = field.read(uint2(cx0, cy1), 0);
    const float4 t11 = field.read(uint2(cx1, cy1), 0);
    const float4 bl = mix(mix(t00, t10, fx), mix(t01, t11, fx), fy);
    const float rNear = ((bl.r + outsideDist));
    const float rCircle = ((length(float2(((uv.x - 0.5f)), ((uv.y - 0.5f)))) - rBound));
    const float rOut = mix(rNear, max(rCircle, rNear), smoothstep(0.0f, 0.25f, outsideDist));
    return float4(rOut, bl.g, bl.b, bl.a);
}

static float2 offsetUV(float2 uv, float ox, float oy) {
    return float2(((uv.x + ox)), ((uv.y + oy)));
}

static float3 volumetricNormal(float4 surf0, float4 surfX, float4 surfY, float eps, float gradClamp) {
    const float ddx = clamp(((((surfX.w - surf0.w)) / eps)), ((gradClamp * (-1.0f))), gradClamp);
    const float ddy = clamp(((((surfY.w - surf0.w)) / eps)), ((gradClamp * (-1.0f))), gradClamp);
    return normalize(float3(ddx, ddy, (-1.0f)));
}

static float2 patternCoords(float2 sdfUV, float4 surf0, float volumetric) {
    return float2(select(((sdfUV.x - 0.5f)), surf0.y, ((volumetric > 0.5f))), select(((sdfUV.y - 0.5f)), surf0.z, ((volumetric > 0.5f))));
}

static uint2 floatBitsToUint2(float2 v) {
    return as_type<uint2>(v);
}

static float2 hash22(float2 p) {
    const uint2 u = floatBitsToUint2(((p * float2(141421360, 2718281728))));
    const uint h = ((u.x ^ u.y));
    const uint2 prod = ((uint2(h, h) * uint2(3141592653, 1618033988)));
    return ((float2(float(prod.x), float(prod.y)) / 4294967296.0f));
}

static float3 perlin12d(float2 p) {
    const float2 i = floor(p);
    const float2 f = fract(p);
    const float2 u = ((((((f * f)) * f)) * ((((f * ((((f * 6.0f)) - 15.0f)))) + 10.0f))));
    const float2 du = ((((((f * f)) * ((((f * ((f - 2.0f)))) + 1.0f)))) * 30.0f));
    const float2 ga = ((((hash22(((i + float2(0)))) * 2.0f)) - 1.0f));
    const float2 gb = ((((hash22(((i + float2(1, 0)))) * 2.0f)) - 1.0f));
    const float2 gc = ((((hash22(((i + float2(0, 1)))) * 2.0f)) - 1.0f));
    const float2 gd = ((((hash22(((i + float2(1)))) * 2.0f)) - 1.0f));
    const float va = dot(ga, ((f - float2(0))));
    const float vb = dot(gb, ((f - float2(1, 0))));
    const float vc = dot(gc, ((f - float2(0, 1))));
    const float vd = dot(gd, ((f - float2(1))));
    const float k = ((((((va - vb)) - vc)) + vd));
    const float value = ((((((va + ((u.x * ((vb - va)))))) + ((u.y * ((vc - va)))))) + ((((u.x * u.y)) * k))));
    const float2 deriv = ((((((((ga + ((((gb - ga)) * u.x)))) + ((((gc - ga)) * u.y)))) + ((((((((ga - gb)) - gc)) + gd)) * ((u.x * u.y)))))) + ((du * ((((((float2(u.y, u.x) * k)) + float2(vb, vc))) - va))))));
    return float3(value, deriv.x, deriv.y);
}

static float2 clampedPerlinGrad(float2 q, float gain) {
    const float gMax = 4.0f;
    const float3 nd = perlin12d(q);
    return float2(clamp(((nd.y * gain)), ((gMax * (-1.0f))), gMax), clamp(((nd.z * gain)), ((gMax * (-1.0f))), gMax));
}

static float3 nudgeNormal(float3 n, float dx, float dy) {
    return normalize(float3(((n.x + dx)), ((n.y + dy)), n.z));
}

static float3 tonemapNeutral(float3 color) {
    const float x = min(color.x, min(color.y, color.z));
    const float offset = select(0.04f, ((x - ((((6.25f * x)) * x)))), ((x < 0.08f)));
    float3 c = ((color - offset));
    const float peak = max(c.x, max(c.y, c.z));
    if ((((peak < 0.76f)))) {
        return c;
    }
    const float dd = 0.24f;
    const float newPeak = ((1.0f - ((((dd * dd)) / ((((peak + dd)) - 0.76f))))));
    c = ((c * ((newPeak / peak))));
    const float g = ((1.0f - ((1.0f / ((((0.15f * ((peak - newPeak)))) + 1.0f))))));
    return mix(c, float3(newPeak), g);
}

static float insideMask(float sdf, float sharpEdge, float pxH, float minPixels) {
    const float w = max(((sharpEdge * 0.03125f)), ((pxH * minPixels)));
    return clamp(((((sdf * (-1.0f))) / w)), 0.0f, 1.0f);
}

static float silhouetteAlpha(float sdf, float edgeSoftness, float pxH) {
    const float sharpEdge = max(((edgeSoftness * 0.5f)), 1.0e-3f);
    return smoothstep(0.0f, 1.0f, insideMask(sdf, sharpEdge, pxH, 1.5f));
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float3 rotateVec3(float3 v, RotStruct rot) {
    const float x1 = ((((v.x * rot.cy)) + ((v.z * rot.sy))));
    const float z1 = ((((v.z * rot.cy)) - ((v.x * rot.sy))));
    const float y2 = ((((v.y * rot.cx)) - ((z1 * rot.sx))));
    const float z2 = ((((v.y * rot.sx)) + ((z1 * rot.cx))));
    const float x3 = ((((x1 * rot.cz)) - ((y2 * rot.sz))));
    const float y3 = ((((x1 * rot.sz)) + ((y2 * rot.cz))));
    return float3(x3, y3, z2);
}

static float sdSphere(float3 p, float r) {
    return ((length(p) - r));
}

static float sdfFn(float3 p, constant MarchParams& params) {
    auto pp = ((&params));
    return sdSphere(p, ((*pp)).pA);
}

static float4 raymarchedField(float2 fuv, RotStruct rot, float rBound, constant MarchParams& params) {
    const float3 ro0 = float3(((fuv.x - 0.5f)), ((0.5f - fuv.y)), (-1.2f));
    const float3 rd0 = float3(0, 0, 1);
    const float3 ro = rotateVec3(ro0, rot);
    const float3 rd = rotateVec3(rd0, rot);
    const int steps = int(clamp(((rBound * 220.0f)), 96.0f, 384.0f));
    const float b = dot(ro, rd);
    const float perp = sqrt(max(((dot(ro, ro) - ((b * b)))), 0.0f));
    const float halfSpan = sqrt(max(((((rBound * rBound)) - ((perp * perp)))), 0.0f));
    const float tStart = max(((((b * (-1.0f))) - halfSpan)), 0.0f);
    const float tEnd = ((((((b * (-1.0f))) + halfSpan)) + 0.01f));
    float t = tStart;
    float tPrev = tStart;
    float minD = 10.0f;
    float hit = 0.0f;
    for (int i = 0; ((i < steps)); i++) {
        const float3 p = ((ro + ((rd * t))));
        const float dd = sdfFn(p, params);
        minD = min(minD, dd);
        if ((((dd < 0.0f)))) {
            hit = 1.0f;
            break;
        }
        if ((((t > tEnd)))) {
            break;
        }
        tPrev = t;
        t = ((t + max(dd, 2.0e-3f)));
    }
    float fieldVal = minD;
    float patternU = 0.0f;
    float patternV = 0.0f;
    float viewDepth = ((tEnd + 0.4f));
    if ((((hit > 0.5f)))) {
        float eLo = tPrev;
        float eHi = t;
        for (int i = 0; ((i < 10)); i++) {
            const float mid = ((((eLo + eHi)) * 0.5f));
            const float dm = sdfFn(((ro + ((rd * mid)))), params);
            if ((((dm > 0.0f)))) {
                eLo = mid;
            } else {
                eHi = mid;
            }
        }
        const float tEnter = ((((eLo + eHi)) * 0.5f));
        float tExit = tEnter;
        {
            const float3 roB = ((ro + ((rd * tEnd))));
            const float span = ((((tEnd - tStart)) + 0.01f));
            float s = 0.0f;
            float sPrev = 0.0f;
            for (int i = 0; ((i < steps)); i++) {
                const float3 p = ((roB - ((rd * s))));
                const float dd = sdfFn(p, params);
                if ((((dd < 0.0f)))) {
                    break;
                }
                if ((((s > span)))) {
                    break;
                }
                sPrev = s;
                s = ((s + max(dd, 2.0e-3f)));
            }
            float xLo = sPrev;
            float xHi = s;
            for (int i = 0; ((i < 10)); i++) {
                const float mid = ((((xLo + xHi)) * 0.5f));
                const float dm = sdfFn(((roB - ((rd * mid)))), params);
                if ((((dm > 0.0f)))) {
                    xLo = mid;
                } else {
                    xHi = mid;
                }
            }
            tExit = ((tEnd - ((((xLo + xHi)) * 0.5f))));
        }
        const float halfChord = ((max(((tExit - tEnter)), 0.0f) * 0.5f));
        fieldVal = ((halfChord * (-1.0f)));
        viewDepth = tEnter;
        {
            const float3 hp = ((ro + ((rd * tEnter))));
            patternU = ((hp.x + ((hp.z * 0.7f))));
            patternV = ((hp.y + ((hp.z * 0.5f))));
        }
    }
    return float4(fieldVal, patternU, patternV, viewDepth);
}

static void volumetricFieldMarch(uint cx, uint cy, texture2d<float, access::write> field_1, constant MarchParams& params) {
    auto p = ((&params));
    const float activeResF = float(((*p)).activeRes);
    const float2 uv = float2(((((*p)).originX + ((((((float(cx) + 0.5f)) / activeResF)) * ((*p)).spanX)))), ((((*p)).originY + ((((((float(cy) + 0.5f)) / activeResF)) * ((*p)).spanY)))));
    const float4 field = raymarchedField(uv, ((*p)).rot, ((*p)).rBound, params);
    field_1.write(field, uint2(cx, cy));
}
} // namespace S_Chrome

using namespace S_Chrome;

fragment float4 Chrome_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]]) {
    float2 uv = in.uv;
    const float2 sdfUV_3 = sdfSpaceUV(uniforms.n_x.center, uniforms.n_x.scale, uniforms.n_x.rotation, uv, uniforms._sys.aspect);
    const float4 s0_2 = fieldSampleArg(sdfUV_3, compute_0, uniforms.n_x._vfOriginX, uniforms.n_x._vfOriginY, uniforms.n_x._vfSpanX, uniforms.n_x._vfSpanY, uniforms.n_x._vfActiveRes, uniforms.n_x._vfRBound);
    const float sdf_1 = ((s0_2.x / uniforms.n_x.scale));
    const float pxH_4 = ((1.0f / uniforms._sys.viewportSize.y));
    float4 chrome_0 = float4(0.0f, 0.0f, 0.0f, 0.0f);
    if ((((!(outsideShape(sdf_1, pxH_4)))))) {
        const float3 coolC_6 = uniforms.n_x.coolColor.rgb;
        const float shadows_7 = uniforms.n_x.shadows;
        const float3 viewI_13 = perspectiveViewRay(uv, ((uniforms._sys.viewportSize.x / uniforms._sys.viewportSize.y)), 0.55f);
        const float4 sX_16 = fieldSampleFastArg(offsetUV(sdfUV_3, 0.01f, 0.0f), compute_0, uniforms.n_x._vfOriginX, uniforms.n_x._vfOriginY, uniforms.n_x._vfSpanX, uniforms.n_x._vfSpanY, uniforms.n_x._vfActiveRes, uniforms.n_x._vfRBound);
        const float4 sY_17 = fieldSampleFastArg(offsetUV(sdfUV_3, 0.0f, 0.01f), compute_0, uniforms.n_x._vfOriginX, uniforms.n_x._vfOriginY, uniforms.n_x._vfSpanX, uniforms.n_x._vfSpanY, uniforms.n_x._vfActiveRes, uniforms.n_x._vfRBound);
        const float3 nGeo_15 = volumetricNormal(s0_2, sX_16, sY_17, 0.01f, 5.0f);
        const float2 pat_19 = patternCoords(sdfUV_3, s0_2, 1.0f);
        const float2 wg_18 = clampedPerlinGrad(float2(((((pat_19.x * 1.05f)) + ((uniforms.n_x._animTime * 0.08f)))), ((pat_19.y * 1.05f))), 1.0f);
        const float wAmt_20 = ((uniforms.n_x.waviness * 0.2f));
        const float3 n_14 = nudgeNormal(nGeo_15, ((wg_18.x * wAmt_20)), ((wg_18.y * wAmt_20)));
        const float3 R_12 = reflect(viewI_13, n_14);
        const float rotA_22 = ((((uniforms.n_x.envRotation * 0.017453292519943295f)) + ((sin(((uniforms.n_x._animTime * 0.23f))) * 0.05f))));
        const float envS_21 = sin(rotA_22);
        const float upY_23 = ((R_12.y * (-1.0f)));
        const float envC_24 = cos(rotA_22);
        const float ry0_11 = ((((R_12.x * envS_21)) + ((upY_23 * envC_24))));
        const float nod_26 = ((sin(((((uniforms.n_x._animTime * 0.31f)) + 0.9f))) * 0.12f));
        const float nc_25 = cos(nod_26);
        const float orbit_29 = ((((sin(((uniforms.n_x._animTime * 0.5f))) * 0.4f)) + ((sin(((((uniforms.n_x._animTime * 0.19f)) + 1.7f))) * 0.2f))));
        const float oc_28 = cos(orbit_29);
        const float rx0_30 = ((((R_12.x * envC_24)) - ((upY_23 * envS_21))));
        const float os_31 = sin(orbit_29);
        const float rz0_27 = ((((R_12.z * oc_28)) - ((rx0_30 * os_31))));
        const float ns_32 = sin(nod_26);
        const float ry_10 = ((((ry0_11 * nc_25)) - ((rz0_27 * ns_32))));
        const float grazing_34 = ((1.0f - clamp(((-(dot(n_14, viewI_13)))), 0.0f, 1.0f)));
        const float delta_33 = ((uniforms.n_x.dispersion * ((0.004f + ((((grazing_34 * grazing_34)) * 0.06f))))));
        const float ey_9 = ((ry_10 + delta_33));
        const float up_8 = smoothstep((-0.65f), 1.0f, ey_9);
        const float cd_35 = ((((ey_9 + 0.45f)) / 0.2f));
        const float spectral_36 = uniforms.n_x.spectral;
        const float rx_40 = ((((rx0_30 * oc_28)) + ((R_12.z * os_31))));
        const float ex_39 = rx_40;
        const float horiz_38 = ((ex_39 / ((length(float2(ex_39, ey_9)) + 0.0001f))));
        const float coolSide_37 = ((0.45f + ((0.55f * smoothstep((-0.7f), 0.7f, ((horiz_38 * (-1.0f))))))));
        const float soft_43 = uniforms.n_x.softness;
        const float softEff_42 = ((soft_43 + ((smoothstep(0.75f, 1.0f, ((n_14.z * (-1.0f)))) * 0.2f))));
        const float boxSoft_41 = ((0.05f + ((softEff_42 * 0.4f))));
        const float rz_49 = ((((rz0_27 * nc_25)) + ((ry0_11 * ns_32))));
        const float ez_48 = rz_49;
        const float pz_47 = max(((0.32f - ez_48)), 0.06f);
        const float px_46 = ((ex_39 / pz_47));
        const float bx_45 = ((abs(px_46) - 0.62f));
        const float py_51 = ((ey_9 / pz_47));
        const float by_50 = ((abs(((py_51 - 0.3f))) - 0.28f));
        const float dbox_44 = ((length(max(float2(bx_45, by_50), float2(0.0f, 0.0f))) + min(max(bx_45, by_50), 0.0f)));
        const float facing_52 = smoothstep(0.18f, (-0.1f), ez_48);
        const float3 warmC_53 = uniforms.n_x.warmColor.rgb;
        const float dOut_54 = max(dbox_44, 0.0f);
        const float gw_55 = ((0.065f + ((soft_43 * 0.05f))));
        const float warmSide_56 = ((0.35f + ((0.65f * smoothstep((-0.7f), 0.7f, horiz_38)))));
        const float fb_57 = ((((ey_9 + 0.12f)) / 0.05f));
        const float cbx_59 = ((abs(px_46) - 0.7f));
        const float cby_60 = ((abs(((py_51 + 0.78f))) - 0.05f));
        const float dcard_58 = ((length(max(float2(cbx_59, cby_60), float2(0.0f, 0.0f))) + min(max(cbx_59, cby_60), 0.0f)));
        const float3 envRt_5 = ((((((((((((((mix(mix(float3(0.17f, 0.175f, 0.19f), ((((coolC_6 * 0.03f)) + float3(0.003f, 0.003f, 0.004f))), float3(shadows_7)), float3(0.56f, 0.57f, 0.6f), float3(((up_8 * up_8)))) + ((float3(0.55f, 0.55f, 0.56f) * smoothstep(0.3f, 0.9f, ey_9))))) + ((coolC_6 * ((((((exp(((((cd_35 * cd_35)) * (-1.0f)))) * spectral_36)) * 0.2f)) * coolSide_37)))))) + ((float3(2.9f, 2.87f, 2.82f) * ((smoothstep(boxSoft_41, ((boxSoft_41 * (-0.6f))), dbox_44) * facing_52)))))) * mix(1.0f, mix(0.55f, 0.07f, shadows_7), smoothstep(0.5f, 0.92f, abs(ex_39))))) + ((warmC_53 * ((((((((((exp(((((((dOut_54 / gw_55)) * ((dOut_54 / gw_55)))) * (-1.0f)))) * smoothstep((-0.06f), 0.1f, dbox_44))) * spectral_36)) * 1.3f)) * warmSide_56)) * facing_52)))))) + ((warmC_53 * ((((((((exp(((((fb_57 * fb_57)) * (-1.0f)))) * spectral_36)) * 0.5f)) * warmSide_56)) * ((1.0f - facing_52)))))))) + ((float3(0.5f, 0.5f, 0.52f) * ((smoothstep(boxSoft_41, ((boxSoft_41 * (-0.6f))), dcard_58) * facing_52))))));
        const float ey_63 = ry_10;
        const float up_62 = smoothstep((-0.65f), 1.0f, ey_63);
        const float cd_64 = ((((ey_63 + 0.45f)) / 0.2f));
        const float ex_67 = rx_40;
        const float horiz_66 = ((ex_67 / ((length(float2(ex_67, ey_63)) + 0.0001f))));
        const float coolSide_65 = ((0.45f + ((0.55f * smoothstep((-0.7f), 0.7f, ((horiz_66 * (-1.0f))))))));
        const float boxSoft_68 = ((0.05f + ((softEff_42 * 0.4f))));
        const float ez_73 = rz_49;
        const float pz_72 = max(((0.32f - ez_73)), 0.06f);
        const float px_71 = ((ex_67 / pz_72));
        const float bx_70 = ((abs(px_71) - 0.62f));
        const float py_75 = ((ey_63 / pz_72));
        const float by_74 = ((abs(((py_75 - 0.3f))) - 0.28f));
        const float dbox_69 = ((length(max(float2(bx_70, by_74), float2(0.0f, 0.0f))) + min(max(bx_70, by_74), 0.0f)));
        const float facing_76 = smoothstep(0.18f, (-0.1f), ez_73);
        const float dOut_77 = max(dbox_69, 0.0f);
        const float gw_78 = ((0.065f + ((soft_43 * 0.05f))));
        const float warmSide_79 = ((0.35f + ((0.65f * smoothstep((-0.7f), 0.7f, horiz_66)))));
        const float fb_80 = ((((ey_63 + 0.12f)) / 0.05f));
        const float cbx_82 = ((abs(px_71) - 0.7f));
        const float cby_83 = ((abs(((py_75 + 0.78f))) - 0.05f));
        const float dcard_81 = ((length(max(float2(cbx_82, cby_83), float2(0.0f, 0.0f))) + min(max(cbx_82, cby_83), 0.0f)));
        const float3 envG_61 = ((((((((((((((mix(mix(float3(0.17f, 0.175f, 0.19f), ((((coolC_6 * 0.03f)) + float3(0.003f, 0.003f, 0.004f))), float3(shadows_7)), float3(0.56f, 0.57f, 0.6f), float3(((up_62 * up_62)))) + ((float3(0.55f, 0.55f, 0.56f) * smoothstep(0.3f, 0.9f, ey_63))))) + ((coolC_6 * ((((((exp(((((cd_64 * cd_64)) * (-1.0f)))) * spectral_36)) * 0.2f)) * coolSide_65)))))) + ((float3(2.9f, 2.87f, 2.82f) * ((smoothstep(boxSoft_68, ((boxSoft_68 * (-0.6f))), dbox_69) * facing_76)))))) * mix(1.0f, mix(0.55f, 0.07f, shadows_7), smoothstep(0.5f, 0.92f, abs(ex_67))))) + ((warmC_53 * ((((((((((exp(((((((dOut_77 / gw_78)) * ((dOut_77 / gw_78)))) * (-1.0f)))) * smoothstep((-0.06f), 0.1f, dbox_69))) * spectral_36)) * 1.3f)) * warmSide_79)) * facing_76)))))) + ((warmC_53 * ((((((((exp(((((fb_80 * fb_80)) * (-1.0f)))) * spectral_36)) * 0.5f)) * warmSide_79)) * ((1.0f - facing_76)))))))) + ((float3(0.5f, 0.5f, 0.52f) * ((smoothstep(boxSoft_68, ((boxSoft_68 * (-0.6f))), dcard_81) * facing_76))))));
        const float ey_86 = ((ry_10 - delta_33));
        const float up_85 = smoothstep((-0.65f), 1.0f, ey_86);
        const float cd_87 = ((((ey_86 + 0.45f)) / 0.2f));
        const float ex_90 = rx_40;
        const float horiz_89 = ((ex_90 / ((length(float2(ex_90, ey_86)) + 0.0001f))));
        const float coolSide_88 = ((0.45f + ((0.55f * smoothstep((-0.7f), 0.7f, ((horiz_89 * (-1.0f))))))));
        const float boxSoft_91 = ((0.05f + ((softEff_42 * 0.4f))));
        const float ez_96 = rz_49;
        const float pz_95 = max(((0.32f - ez_96)), 0.06f);
        const float px_94 = ((ex_90 / pz_95));
        const float bx_93 = ((abs(px_94) - 0.62f));
        const float py_98 = ((ey_86 / pz_95));
        const float by_97 = ((abs(((py_98 - 0.3f))) - 0.28f));
        const float dbox_92 = ((length(max(float2(bx_93, by_97), float2(0.0f, 0.0f))) + min(max(bx_93, by_97), 0.0f)));
        const float facing_99 = smoothstep(0.18f, (-0.1f), ez_96);
        const float dOut_100 = max(dbox_92, 0.0f);
        const float gw_101 = ((0.065f + ((soft_43 * 0.05f))));
        const float warmSide_102 = ((0.35f + ((0.65f * smoothstep((-0.7f), 0.7f, horiz_89)))));
        const float fb_103 = ((((ey_86 + 0.12f)) / 0.05f));
        const float cbx_105 = ((abs(px_94) - 0.7f));
        const float cby_106 = ((abs(((py_98 + 0.78f))) - 0.05f));
        const float dcard_104 = ((length(max(float2(cbx_105, cby_106), float2(0.0f, 0.0f))) + min(max(cbx_105, cby_106), 0.0f)));
        const float3 envBt_84 = ((((((((((((((mix(mix(float3(0.17f, 0.175f, 0.19f), ((((coolC_6 * 0.03f)) + float3(0.003f, 0.003f, 0.004f))), float3(shadows_7)), float3(0.56f, 0.57f, 0.6f), float3(((up_85 * up_85)))) + ((float3(0.55f, 0.55f, 0.56f) * smoothstep(0.3f, 0.9f, ey_86))))) + ((coolC_6 * ((((((exp(((((cd_87 * cd_87)) * (-1.0f)))) * spectral_36)) * 0.2f)) * coolSide_88)))))) + ((float3(2.9f, 2.87f, 2.82f) * ((smoothstep(boxSoft_91, ((boxSoft_91 * (-0.6f))), dbox_92) * facing_99)))))) * mix(1.0f, mix(0.55f, 0.07f, shadows_7), smoothstep(0.5f, 0.92f, abs(ex_90))))) + ((warmC_53 * ((((((((((exp(((((((dOut_100 / gw_101)) * ((dOut_100 / gw_101)))) * (-1.0f)))) * smoothstep((-0.06f), 0.1f, dbox_92))) * spectral_36)) * 1.3f)) * warmSide_102)) * facing_99)))))) + ((warmC_53 * ((((((((exp(((((fb_103 * fb_103)) * (-1.0f)))) * spectral_36)) * 0.5f)) * warmSide_102)) * ((1.0f - facing_99)))))))) + ((float3(0.5f, 0.5f, 0.52f) * ((smoothstep(boxSoft_91, ((boxSoft_91 * (-0.6f))), dcard_104) * facing_99))))));
        chrome_0 = float4(tonemapNeutral(((((float3(envRt_5.x, envG_61.y, envBt_84.z) * uniforms.n_x.environment)) * uniforms.n_x.tint.rgb))), silhouetteAlpha(sdf_1, uniforms.n_x.edgeSoftness, pxH_4));
    }
    float4 composed_107 = chrome_0;
    return composed_107;
}

static void Chrome_k0_body(uint cx, uint cy, uint _arg_2, texture2d<float, access::write> field_1, constant MarchParams& params) {
    volumetricFieldMarch(cx, cy, field_1, params);
}

kernel void Chrome_k0(uint3 sk_gid [[thread_position_in_grid]], texture2d<float, access::write> field_1 [[texture(0)]], constant MarchParams& params [[buffer(0)]], constant uint3& sk_size [[buffer(1)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Chrome_k0_body(sk_gid.x, sk_gid.y, sk_gid.z, field_1, params);
}
