// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: DiamondWipe
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_DiamondWipe {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct CellGrid {
    float2 cell;
    float2 local;
    float2 grid;
};

struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct padded_1 {
    float progress;
    float size;
    float feather;
    float invert;
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    padded_1 n_x;
    padded n_child;
    struct_1 _sys;
};

static float4 applyReveal(float4 color, float reveal) {
    return float4(color.x, color.y, color.z, ((color.w * reveal)));
}

static float revealMask(float coord, float progress, float feather, float invert) {
    const float c = select(coord, ((1.0f - coord)), ((invert > 0.0f)));
    const float f = max(feather, 1.0e-4f);
    const float front = ((((progress * ((1.0f + ((2.0f * f)))))) - f));
    return smoothstep(((front - f)), ((front + f)), c);
}

static CellGrid cellGrid(float2 uv, float aspect, float size) {
    const float gridX = ((1.0f / max(size, 1.0e-3f)));
    const float gridY = max(((gridX / aspect)), 1.0f);
    const float sx = ((uv.x * gridX));
    const float sy = ((uv.y * gridY));
    return CellGrid{float2(floor(sx), floor(sy)), float2(fract(sx), fract(sy)), float2(gridX, gridY)};
}

static float cellDiamondCoord(float2 uv, float aspect, float size) {
    const CellGrid g = cellGrid(uv, aspect, size);
    return ((abs(((g.local.x - 0.5f))) + abs(((g.local.y - 0.5f)))));
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}
} // namespace S_DiamondWipe

using namespace S_DiamondWipe;

fragment float4 DiamondWipe_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = applyReveal(media_0.sample(linearClamp, uv), revealMask(cellDiamondCoord(uv, uniforms._sys.aspect, uniforms.n_x.size), uniforms.n_x.progress, uniforms.n_x.feather, uniforms.n_x.invert));
    return composed_0;
}
