// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: DiffuseBlur
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_DiffuseBlur {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct padded_1 {
    float intensity;
    float edges;
    float _opacity;
    float _pad0;
};

struct struct_1 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    padded_1 n_x;
    padded n_child;
    struct_1 _sys;
};

static float4 unpremultiplyAlpha(float4 color2) {
    const float alpha = color2.w;
    const float3 straightRGB = select(float3(0), ((color2.xyz / alpha)), ((alpha > 1.0e-3f)));
    return float4(straightRGB, alpha);
}

static uint2 floatBitsToUint2(float2 v) {
    return as_type<uint2>(v);
}

static float2 hash22(float2 p) {
    const uint2 u = floatBitsToUint2(((p * float2(141421360, 2718281728))));
    const uint h = ((u.x ^ u.y));
    const uint2 prod = ((uint2(h, h) * uint2(3141592653, 1618033988)));
    return ((float2(float(prod.x), float(prod.y)) / 4294967296.0f));
}

static float2 diffuseBlurUV(float2 uv, float intensity, float2 viewport) {
    const float2 seed = ((uv * 1000.0f));
    const float2 randVec = hash22(seed);
    const float2 offset = ((((((((randVec * 2.0f)) - float2(1))) * intensity)) / viewport));
    return ((uv + offset));
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float4 overComposite(float4 base, float3 blended, float overlayAlpha) {
    const float baseWeight = ((base.w * ((1.0f - overlayAlpha))));
    const float finalAlpha = ((overlayAlpha + baseWeight));
    const float3 rgb = ((((blended * overlayAlpha)) + ((base.xyz * baseWeight))));
    return float4(rgb, finalAlpha);
}

static float4 blend_normal(float4 base, float4 overlay2, float opacity) {
    const float overlayAlpha = ((overlay2.w * opacity));
    return overComposite(base, overlay2.xyz, overlayAlpha);
}

static float edgeTransparentMask(float2 uv) {
    const float inX = ((step(0.0f, uv.x) * step(uv.x, 1.0f)));
    const float inY = ((step(0.0f, uv.y) * step(uv.y, 1.0f)));
    return ((inX * inY));
}

static float2 edgeMirrorUV(float2 uv) {
    const float mirrorX = (fmod(abs(uv.x), 2.0f));
    const float mirrorY = (fmod(abs(uv.y), 2.0f));
    return float2(select(mirrorX, ((2.0f - mirrorX)), ((mirrorX >= 1.0f))), select(mirrorY, ((2.0f - mirrorY)), ((mirrorY >= 1.0f))));
}

static float2 edgeWrapUV(float2 uv) {
    return fract(uv);
}
} // namespace S_DiffuseBlur

using namespace S_DiffuseBlur;

fragment float4 DiffuseBlur_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = unpremultiplyAlpha(rtt_0.sample(linearClamp, diffuseBlurUV(uv, uniforms.n_x.intensity, uniforms._sys.viewportSize)));
    return composed_0;
}

fragment float4 DiffuseBlur_v0_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 DiffuseBlur_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = unpremultiplyAlpha(float4((rtt_0.sample(linearClamp, diffuseBlurUV(uv, uniforms.n_x.intensity, uniforms._sys.viewportSize))).rgb, (((rtt_0.sample(linearClamp, diffuseBlurUV(uv, uniforms.n_x.intensity, uniforms._sys.viewportSize))).a * edgeTransparentMask(diffuseBlurUV(uv, uniforms.n_x.intensity, uniforms._sys.viewportSize))))));
    return composed_0;
}

fragment float4 DiffuseBlur_v1_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 DiffuseBlur_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = unpremultiplyAlpha(rtt_0.sample(linearClamp, edgeMirrorUV(diffuseBlurUV(uv, uniforms.n_x.intensity, uniforms._sys.viewportSize))));
    return composed_0;
}

fragment float4 DiffuseBlur_v2_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 DiffuseBlur_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = unpremultiplyAlpha(rtt_0.sample(linearClamp, edgeWrapUV(diffuseBlurUV(uv, uniforms.n_x.intensity, uniforms._sys.viewportSize))));
    return composed_0;
}

fragment float4 DiffuseBlur_v3_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}
