// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: FilmStock
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_FilmStock {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct padded_1 {
    float strength;
    float halation;
    float halationRadius;
    float weave;
    float _opacity;
    float weaveTime;
    float _pad0;
    float _pad1;
};

struct struct_1 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    padded_1 n_x;
    padded n_child;
    struct_1 _sys;
};

struct item {
    float inputWidth;
    float inputHeight;
    char _sk_pad0[8];
};

struct item_2 {
    float scaleY;
    char _sk_pad0[12];
};

struct Params {
    float threshold;
    float size;
    float inputWidth;
    float inputHeight;
};

static float4 tintedScreenGlow(float4 base, float4 glow, float4 tintStrength) {
    const float strength = tintStrength.w;
    const float3 bloomC = clamp(((((glow.xyz * tintStrength.xyz)) * strength)), float3(0), float3(1));
    const float3 one = float3(1);
    const float3 screened = ((one - ((((one - base.xyz)) * ((one - bloomC))))));
    const float a = ((base.w + ((((glow.w * strength)) * ((1.0f - base.w))))));
    return float4(screened.x, screened.y, screened.z, clamp(a, 0.0f, 1.0f));
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tonemap_srgbToLinear(float3 color) {
    const float3 hi = pow(((((color + float3(0.054999999701976776f))) / float3(1.0549999475479126f))), float3(2.4000000953674316f));
    const float3 lo = ((color / float3(12.920000076293945f)));
    const bool3 isLow = ((color <= float3(0.040449999272823334f)));
    return select(hi, lo, isLow);
}

static float4 lutAtlasApply(float4 color, float4 tapLo, float4 tapHi, float strength) {
    const float3 enc = linearToSrgb(clamp(color.xyz, float3(0), float3(1)));
    const float slice = ((enc.z * 16.0f));
    const float f = ((slice - floor(slice)));
    const float3 graded = tonemap_srgbToLinear(mix(tapLo.xyz, tapHi.xyz, float3(f, f, f)));
    const float3 rgb = mix(color.xyz, graded, float3(strength, strength, strength));
    return float4(rgb.x, rgb.y, rgb.z, color.w);
}

static float4 unpremultiplyAlpha(float4 color2) {
    const float alpha = color2.w;
    const float3 straightRGB = select(float3(0), ((color2.xyz / alpha)), ((alpha > 1.0e-3f)));
    return float4(straightRGB, alpha);
}

static float2 swayUV(float2 uv, float amount, float t) {
    const float amp = ((amount * 6.0e-3f));
    const float ox = ((((((sin(((t * 1.7f))) * 0.5f)) + ((sin(((((t * 0.9f)) + 1.3f))) * 0.5f)))) * amp));
    const float oy = ((((((sin(((((t * 1.3f)) + 0.7f))) * 0.5f)) + ((sin(((t * 2.3f))) * 0.5f)))) * amp));
    const float ang = ((((sin(((t * 0.6f))) * amount)) * 4.0e-3f));
    const float c = cos(ang);
    const float s = sin(ang);
    const float2 p = ((uv - float2(0.5f)));
    const float rx = ((((p.x * c)) - ((p.y * s))));
    const float ry = ((((p.x * s)) + ((p.y * c))));
    return float2(((((rx + 0.5f)) + ox)), ((((ry + 0.5f)) + oy)));
}

static float2 lutAtlasUv(float4 color, float hi) {
    const float3 enc = linearToSrgb(clamp(color.xyz, float3(0), float3(1)));
    const float slice = ((enc.z * 16.0f));
    const float s = clamp(((floor(slice) + hi)), 0.0f, 16.0f);
    const float u = ((((((((s * 17.0f)) + 0.5f)) + ((enc.x * 16.0f)))) * 0.0034602077212184668f));
    const float v = ((((0.5f + ((enc.y * 16.0f)))) * 0.05882352963089943f));
    return float2(u, v);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float4 overComposite(float4 base, float3 blended, float overlayAlpha) {
    const float baseWeight = ((base.w * ((1.0f - overlayAlpha))));
    const float finalAlpha = ((overlayAlpha + baseWeight));
    const float3 rgb = ((((blended * overlayAlpha)) + ((base.xyz * baseWeight))));
    return float4(rgb, finalAlpha);
}

static float4 blend_normal(float4 base, float4 overlay2, float opacity) {
    const float overlayAlpha = ((overlay2.w * opacity));
    return overComposite(base, overlay2.xyz, overlayAlpha);
}

static void variableBlurH(uint cx, uint cy, texture2d<float, access::read> blurMap, texture2d<float> input, texture2d<float, access::write> intermediate, constant item& params, device float* weights) {
    auto p = ((&params));
    const float blurRadius = blurMap.read(uint2(cx, cy)).r;
    const float inputCx = ((((((((float(cx) + 0.5f)) * ((*p)).inputWidth)) / 1024.0f)) - 0.5f));
    const float inputCy = ((((((((float(cy) + 0.5f)) * ((*p)).inputHeight)) / 768.0f)) - 0.5f));
    const int inputWm1 = int(((((*p)).inputWidth - 1.0f)));
    const int inputHm1 = int(((((*p)).inputHeight - 1.0f)));
    const int inputCyI = clamp(int(rint(inputCy)), 0, inputHm1);
    if ((((blurRadius < 0.5f)))) {
        const int cxClamp = clamp(int(rint(inputCx)), 0, inputWm1);
        const float4 texel = input.read(uint2(uint(cxClamp), uint(inputCyI)), 0);
        intermediate.write(texel, uint2(cx, cy));
    } else {
        const float jitterH = ((fract(((52.9829189f * fract(((((float(cx) * 0.06711056f)) + ((float(cy) * 0.00583715f)))))))) - 0.5f));
        float4 sum = float4(0);
        for (int i = (-24); ((i <= 24)); i++) {
            const float offset = ((((((float(i) + jitterH)) * 0.041666666666666664f)) * blurRadius));
            const int sampleX = clamp(int(rint(((inputCx + offset)))), 0, inputWm1);
            const float4 texel = input.read(uint2(uint(sampleX), uint(inputCyI)), 0);
            sum = ((sum + ((texel * weights[((i + 24))]))));
        }
        intermediate.write(sum, uint2(cx, cy));
    }
}

static void variableBlurV(uint cx, uint cy, texture2d<float, access::read> blurMap, texture2d<float, access::write> output, constant item_2& params_2, texture2d<float, access::read> src, device float* weights) {
    const float blurRadius = blurMap.read(uint2(cx, cy)).r;
    if ((((blurRadius < 0.5f)))) {
        const float4 texel = src.read(uint2(cx, cy));
        output.write(texel, uint2(cx, cy));
    } else {
        const int yi = int(cy);
        const float radiusComputeY = ((blurRadius / params_2.scaleY));
        const float jitterV = ((fract(((52.9829189f * fract(((((float(cx) * 0.00583715f)) + ((float(cy) * 0.06711056f)))))))) - 0.5f));
        float4 sum = float4(0);
        for (int i = (-24); ((i <= 24)); i++) {
            const float offset = ((((((float(i) + jitterV)) * 0.041666666666666664f)) * radiusComputeY));
            const int sampleY = clamp(((yi + int(rint(offset)))), 0, 767);
            const float4 texel = src.read(uint2(cx, uint(sampleY)));
            sum = ((sum + ((texel * weights[((i + 24))]))));
        }
        output.write(sum, uint2(cx, cy));
    }
}

static float4 bloomExtractSoftKnee(texture2d<float> childTexture, uint cx, uint cy, float2 inputSize, float2 computeSize, float threshold) {
    const float iw = inputSize.x;
    const float ih = inputSize.y;
    const int inputWm1 = int(((iw - 1.0f)));
    const int inputHm1 = int(((ih - 1.0f)));
    float4 sample = float4(0);
    for (int ty = 0; ((ty < 4)); ty++) {
        for (int tx = 0; ((tx < 4)); tx++) {
            const float su = ((((float(cx) + ((((float(tx) + 0.5f)) / 4.0f)))) / computeSize.x));
            const float sv = ((((float(cy) + ((((float(ty) + 0.5f)) / 4.0f)))) / computeSize.y));
            const int sx = clamp(int(((su * iw))), 0, inputWm1);
            const int sy = clamp(int(((sv * ih))), 0, inputHm1);
            sample = ((sample + childTexture.read(uint2(uint(sx), uint(sy)), 0)));
        }
    }
    sample = ((sample * 0.0625f));
    const float knee = ((((threshold * 0.5f)) + 1.0e-4f));
    const float lum = dot(sample.xyz, float3(0.2125999927520752f, 0.7152000069618225f, 0.0722000002861023f));
    const float soft = clamp(((((lum - threshold)) + knee)), 0.0f, ((knee * 2.0f)));
    const float softCurve = ((((soft * soft)) / ((knee * 4.0f))));
    const float mask = ((max(softCurve, ((lum - threshold))) / max(lum, 1.0e-4f)));
    return float4(((sample.xyz * mask)), ((sample.w * mask)));
}

static void filmStockHalationExtract(uint cx, uint cy, texture2d<float, access::write> blurMap_2, texture2d<float, access::write> brightMap, texture2d<float> childTexture, constant Params& params_3) {
    auto p = ((&params_3));
    const float4 bright = bloomExtractSoftKnee(childTexture, cx, cy, float2(((*p)).inputWidth, ((*p)).inputHeight), float2(1024, 768), ((*p)).threshold);
    brightMap.write(bright, uint2(cx, cy));
    blurMap_2.write(float4(((*p)).size, 0.0f, 0.0f, 1.0f), uint2(cx, cy));
}
} // namespace S_FilmStock

using namespace S_FilmStock;

fragment float4 FilmStock_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> media_1 [[texture(1)]], texture2d<float> compute_0 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = tintedScreenGlow(lutAtlasApply(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 0.0f)), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 1.0f)), uniforms.n_x.strength), compute_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime)), float4(1.0f, 0.38f, 0.16f, uniforms.n_x.halation));
    return composed_0;
}

fragment float4 FilmStock_v0_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 FilmStock_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> media_1 [[texture(1)]], texture2d<float> compute_0 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = tintedScreenGlow(lutAtlasApply(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 0.0f)), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 1.0f)), uniforms.n_x.strength), compute_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime)), float4(1.0f, 0.38f, 0.16f, uniforms.n_x.halation));
    return composed_0;
}

fragment float4 FilmStock_v1_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 FilmStock_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> media_1 [[texture(1)]], texture2d<float> compute_0 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = tintedScreenGlow(lutAtlasApply(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 0.0f)), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 1.0f)), uniforms.n_x.strength), compute_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime)), float4(1.0f, 0.38f, 0.16f, uniforms.n_x.halation));
    return composed_0;
}

fragment float4 FilmStock_v2_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 FilmStock_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> media_1 [[texture(1)]], texture2d<float> compute_0 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = tintedScreenGlow(lutAtlasApply(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 0.0f)), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 1.0f)), uniforms.n_x.strength), compute_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime)), float4(1.0f, 0.38f, 0.16f, uniforms.n_x.halation));
    return composed_0;
}

fragment float4 FilmStock_v3_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 FilmStock_v4_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> media_1 [[texture(1)]], texture2d<float> compute_0 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = tintedScreenGlow(lutAtlasApply(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 0.0f)), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 1.0f)), uniforms.n_x.strength), compute_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime)), float4(1.0f, 0.38f, 0.16f, uniforms.n_x.halation));
    return composed_0;
}

fragment float4 FilmStock_v4_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 FilmStock_v5_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> media_1 [[texture(1)]], texture2d<float> compute_0 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = tintedScreenGlow(lutAtlasApply(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 0.0f)), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 1.0f)), uniforms.n_x.strength), compute_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime)), float4(1.0f, 0.38f, 0.16f, uniforms.n_x.halation));
    return composed_0;
}

fragment float4 FilmStock_v5_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 FilmStock_v6_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> media_1 [[texture(1)]], texture2d<float> compute_0 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = tintedScreenGlow(lutAtlasApply(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 0.0f)), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 1.0f)), uniforms.n_x.strength), compute_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime)), float4(1.0f, 0.38f, 0.16f, uniforms.n_x.halation));
    return composed_0;
}

fragment float4 FilmStock_v6_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 FilmStock_v7_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> media_1 [[texture(1)]], texture2d<float> compute_0 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = tintedScreenGlow(lutAtlasApply(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 0.0f)), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 1.0f)), uniforms.n_x.strength), compute_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime)), float4(1.0f, 0.38f, 0.16f, uniforms.n_x.halation));
    return composed_0;
}

fragment float4 FilmStock_v7_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 FilmStock_v8_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> media_1 [[texture(1)]], texture2d<float> compute_0 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = tintedScreenGlow(lutAtlasApply(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 0.0f)), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 1.0f)), uniforms.n_x.strength), compute_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime)), float4(1.0f, 0.38f, 0.16f, uniforms.n_x.halation));
    return composed_0;
}

fragment float4 FilmStock_v8_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 FilmStock_v9_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> media_1 [[texture(1)]], texture2d<float> compute_0 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = tintedScreenGlow(lutAtlasApply(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 0.0f)), media_1.sample(linearClamp, lutAtlasUv(unpremultiplyAlpha(rtt_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime))), 1.0f)), uniforms.n_x.strength), compute_0.sample(linearClamp, swayUV(uv, uniforms.n_x.weave, uniforms.n_x.weaveTime)), float4(1.0f, 0.38f, 0.16f, uniforms.n_x.halation));
    return composed_0;
}

fragment float4 FilmStock_v9_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

static void FilmStock_k0_body(uint cx, uint cy, uint _arg_2, texture2d<float, access::read> blurMap, texture2d<float> input, texture2d<float, access::write> intermediate, constant item& params, device float* weights) {
    variableBlurH(cx, cy, blurMap, input, intermediate, params, weights);
}

kernel void FilmStock_k0(uint3 sk_gid [[thread_position_in_grid]], texture2d<float, access::read> blurMap [[texture(0)]], texture2d<float> input [[texture(1)]], texture2d<float, access::write> intermediate [[texture(2)]], device float* weights [[buffer(0)]], constant item& params [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    FilmStock_k0_body(sk_gid.x, sk_gid.y, sk_gid.z, blurMap, input, intermediate, params, weights);
}

static void FilmStock_k1_body(uint cx, uint cy, uint _arg_2, texture2d<float, access::read> blurMap, texture2d<float, access::write> output, constant item_2& params_2, texture2d<float, access::read> src, device float* weights) {
    variableBlurV(cx, cy, blurMap, output, params_2, src, weights);
}

kernel void FilmStock_k1(uint3 sk_gid [[thread_position_in_grid]], texture2d<float, access::read> blurMap [[texture(0)]], texture2d<float, access::read> src [[texture(1)]], texture2d<float, access::write> output [[texture(2)]], device float* weights [[buffer(0)]], constant item_2& params_2 [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    FilmStock_k1_body(sk_gid.x, sk_gid.y, sk_gid.z, blurMap, output, params_2, src, weights);
}

static void FilmStock_k2_body(uint cx, uint cy, uint _arg_2, texture2d<float, access::write> blurMap_2, texture2d<float, access::write> brightMap, texture2d<float> childTexture, constant Params& params_3) {
    filmStockHalationExtract(cx, cy, blurMap_2, brightMap, childTexture, params_3);
}

kernel void FilmStock_k2(uint3 sk_gid [[thread_position_in_grid]], texture2d<float> childTexture [[texture(0)]], texture2d<float, access::write> brightMap [[texture(1)]], texture2d<float, access::write> blurMap_2 [[texture(2)]], constant Params& params_3 [[buffer(0)]], constant uint3& sk_size [[buffer(1)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    FilmStock_k2_body(sk_gid.x, sk_gid.y, sk_gid.z, blurMap_2, brightMap, childTexture, params_3);
}
