// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: FlowingGradient
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_FlowingGradient {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float4 colorA;
    float4 colorB;
    float4 colorC;
    float4 colorD;
    float colorSpace;
    float speed;
    float distortion;
    float seed;
    float _opacity;
    float _animTime;
    float3 convA;
    float3 convB;
    float3 convC;
    float3 convD;
};

struct struct_2 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    struct_1 n_x;
    struct_2 _sys;
};

struct MixStep {
    float3 conv;
    float alpha;
};

static float mxFade(float t) {
    return ((((((t * t)) * t)) * ((((t * ((((t * 6.0f)) - 15.0f)))) + 10.0f))));
}

static uint mxRotl32(uint x, int k) {
    return ((((x << uint(k))) | ((x >> uint(((32 - k)))))));
}

static uint mxBjfinal(uint a0, uint b0, uint c0) {
    uint a = a0;
    uint b = b0;
    uint c = c0;
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 14)));
    a = ((a ^ c));
    a = ((a - mxRotl32(c, 11)));
    b = ((b ^ a));
    b = ((b - mxRotl32(a, 25)));
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 16)));
    a = ((a ^ c));
    a = ((a - mxRotl32(c, 4)));
    b = ((b ^ a));
    b = ((b - mxRotl32(a, 14)));
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 24)));
    return c;
}

static uint mxHashInt2(int x, int y, int z) {
    const uint len = 3u;
    const uint seed = ((((3735928559u + ((len << 2u)))) + 13u));
    const uint a = ((seed + uint(x)));
    const uint b = ((seed + uint(y)));
    const uint c = ((seed + uint(z)));
    return mxBjfinal(a, b, c);
}

static float mxGradientFloat3(uint hash, float x, float y, float z) {
    const uint h = ((hash & 15u));
    const float u = select(y, x, ((h < 8u)));
    const float inner = select(z, x, ((((h == 12u)) || ((h == 14u)))));
    const float v = select(inner, y, ((h < 4u)));
    const float uu = select(u, (-(u)), ((((h & 1u)) != 0u)));
    const float vv = select(v, (-(v)), ((((h & 2u)) != 0u)));
    return ((uu + vv));
}

static float mxTrilerp(float v0, float v1, float v2, float v3, float v4, float v5, float v6, float v7, float s, float t, float r) {
    const float s1 = ((1.0f - s));
    const float t1 = ((1.0f - t));
    const float r1 = ((1.0f - r));
    return ((((r1 * ((((t1 * ((((v0 * s1)) + ((v1 * s)))))) + ((t * ((((v2 * s1)) + ((v3 * s)))))))))) + ((r * ((((t1 * ((((v4 * s1)) + ((v5 * s)))))) + ((t * ((((v6 * s1)) + ((v7 * s))))))))))));
}

static float mxGradientScale3d(float v) {
    return ((0.982f * v));
}

static float mxPerlinNoiseFloat3(float3 p) {
    const int X = int(floor(p.x));
    const int Y = int(floor(p.y));
    const int Z = int(floor(p.z));
    const float fx = ((p.x - float(X)));
    const float fy = ((p.y - float(Y)));
    const float fz = ((p.z - float(Z)));
    const float u = mxFade(fx);
    const float v = mxFade(fy);
    const float w = mxFade(fz);
    const float result = mxTrilerp(mxGradientFloat3(mxHashInt2(X, Y, Z), fx, fy, fz), mxGradientFloat3(mxHashInt2(((X + 1)), Y, Z), ((fx - 1.0f)), fy, fz), mxGradientFloat3(mxHashInt2(X, ((Y + 1)), Z), fx, ((fy - 1.0f)), fz), mxGradientFloat3(mxHashInt2(((X + 1)), ((Y + 1)), Z), ((fx - 1.0f)), ((fy - 1.0f)), fz), mxGradientFloat3(mxHashInt2(X, Y, ((Z + 1))), fx, fy, ((fz - 1.0f))), mxGradientFloat3(mxHashInt2(((X + 1)), Y, ((Z + 1))), ((fx - 1.0f)), fy, ((fz - 1.0f))), mxGradientFloat3(mxHashInt2(X, ((Y + 1)), ((Z + 1))), fx, ((fy - 1.0f)), ((fz - 1.0f))), mxGradientFloat3(mxHashInt2(((X + 1)), ((Y + 1)), ((Z + 1))), ((fx - 1.0f)), ((fy - 1.0f)), ((fz - 1.0f))), u, v, w);
    return mxGradientScale3d(result);
}

static float mxNoiseFloat3(float3 p) {
    return mxPerlinNoiseFloat3(p);
}

static float4 chainedWarpStep(float2 pos, float scale, float z, float2 offA, float2 offB, float k, float strength) {
    const float3 wp = float3(((pos.x * scale)), ((pos.y * scale)), z);
    const float nx = mxNoiseFloat3(((wp + float3(offA.x, offA.y, 0.0f))));
    const float ny = mxNoiseFloat3(((wp + float3(offB.x, offB.y, 0.0f))));
    return float4(((pos.x + ((((nx * k)) * strength)))), ((pos.y + ((((ny * k)) * strength)))), nx, ny);
}

static float3 awMix(float3 a, float3 b, float wA, float wB, float sw) {
    return ((((((a * wA)) + ((b * wB)))) / sw));
}

static float4 mixColors(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 rgb = awMix(colorA.xyz, colorB.xyz, weightA, weightB, safeWeight);
    return float4(rgb, totalWeight);
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static MixStep mixPreconvertedInSpace(float3 convA, float alphaA, float3 convB, float alphaB, float t) {
    const float weightA = ((alphaA * ((1.0f - t))));
    const float weightB = ((alphaB * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    return MixStep{awMix(convA, convB, weightA, weightB, safeWeight), totalWeight};
}

static float3 oklchToOklab(float3 lch) {
    const float L = lch.x;
    const float C = lch.y;
    const float h = lch.z;
    return float3(L, ((C * cos(h))), ((C * sin(h))));
}

static float3 oklabToRgb(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float l_ = ((((L + ((a * 0.3963377774f)))) + ((b * 0.2158037573f))));
    const float m_ = ((((L - ((a * 0.1055613458f)))) - ((b * 0.0638541728f))));
    const float s_ = ((((L - ((a * 0.0894841775f)))) - ((b * 1.291485548f))));
    const float l = pow(l_, 3.0f);
    const float m = pow(m_, 3.0f);
    const float s = pow(s_, 3.0f);
    return float3(((((((l * 4.0767416621f)) - ((m * 3.3077115913f)))) + ((s * 0.2309699292f)))), ((((((l * (-1.2684380046f))) + ((m * 2.6097574011f)))) - ((s * 0.3413193965f)))), ((((((l * (-0.0041960863f))) - ((m * 0.7034186147f)))) + ((s * 1.707614701f)))));
}

static float3 sRGBToP3(float3 srgb) {
    const float r = ((((((srgb.x * 0.8224621f)) + ((srgb.y * 0.177538f)))) + ((srgb.z * 0.0f))));
    const float g = ((((((srgb.x * 0.0331941f)) + ((srgb.y * 0.9668058f)))) + ((srgb.z * 0.0f))));
    const float b = ((((((srgb.x * 0.0170826f)) + ((srgb.y * 0.0723974f)))) + ((srgb.z * 0.9105199f))));
    return float3(r, g, b);
}

static float4 mixPreconvertedColors(float3 convA, float3 convB, float alphaA, float alphaB, float t) {
    const float weightA = ((alphaA * ((1.0f - t))));
    const float weightB = ((alphaB * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 mixed = awMix(convA, convB, weightA, weightB, safeWeight);
    return float4(sRGBToP3(oklabToRgb(oklchToOklab(mixed))), totalWeight);
}

static float4 mixPreconvertedColors_2(float3 convA, float3 convB, float alphaA, float alphaB, float t) {
    const float weightA = ((alphaA * ((1.0f - t))));
    const float weightB = ((alphaB * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 mixed = awMix(convA, convB, weightA, weightB, safeWeight);
    return float4(sRGBToP3(oklabToRgb(mixed)), totalWeight);
}

static float3 selectRGBBySector(float c, float x, float sector) {
    float r = 0.0f;
    float g = 0.0f;
    float b = 0.0f;
    if ((((sector < 1.0f)))) {
        r = c;
        g = x;
    } else {
        if ((((sector < 2.0f)))) {
            r = x;
            g = c;
        } else {
            if ((((sector < 3.0f)))) {
                g = c;
                b = x;
            } else {
                if ((((sector < 4.0f)))) {
                    g = x;
                    b = c;
                } else {
                    if ((((sector < 5.0f)))) {
                        r = x;
                        b = c;
                    } else {
                        r = c;
                        b = x;
                    }
                }
            }
        }
    }
    return float3(r, g, b);
}

static float3 hslToRgb(float3 hsl) {
    const float h = hsl.x;
    const float s = hsl.y;
    const float l = hsl.z;
    const float c = ((s * ((1.0f - abs(((((l * 2.0f)) - 1.0f)))))));
    const float hPrime = ((h / 1.0471975512f));
    const float x = ((c * ((1.0f - abs((((fmod(hPrime, 2.0f)) - 1.0f)))))));
    const float m = ((l - ((c * 0.5f))));
    const float sector = floor(hPrime);
    return ((selectRGBBySector(c, x, sector) + m));
}

static float4 mixPreconvertedColors_3(float3 convA, float3 convB, float alphaA, float alphaB, float t) {
    const float weightA = ((alphaA * ((1.0f - t))));
    const float weightB = ((alphaB * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 mixed = awMix(convA, convB, weightA, weightB, safeWeight);
    return float4(sRGBToP3(hslToRgb(mixed)), totalWeight);
}

static float3 hsvToRgb(float3 hsv) {
    const float h = hsv.x;
    const float s = hsv.y;
    const float v = hsv.z;
    const float c = ((v * s));
    const float hPrime = ((h / 1.0471975512f));
    const float x = ((c * ((1.0f - abs((((fmod(hPrime, 2.0f)) - 1.0f)))))));
    const float m = ((v - c));
    const float sector = floor(hPrime);
    return ((selectRGBBySector(c, x, sector) + m));
}

static float4 mixPreconvertedColors_4(float3 convA, float3 convB, float alphaA, float alphaB, float t) {
    const float weightA = ((alphaA * ((1.0f - t))));
    const float weightB = ((alphaB * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 mixed = awMix(convA, convB, weightA, weightB, safeWeight);
    return float4(sRGBToP3(hsvToRgb(mixed)), totalWeight);
}

static float3 labToRgb(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float fy = ((((L + 16.0f)) / 116.0f));
    const float fx = ((((a / 500.0f)) + fy));
    const float fz = ((fy - ((b / 200.0f))));
    const float xn = select(((((fx - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fx, 3.0f), ((fx > 0.20689655172413793f)));
    const float yn = select(((((fy - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fy, 3.0f), ((fy > 0.20689655172413793f)));
    const float zn = select(((((fz - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fz, 3.0f), ((fz > 0.20689655172413793f)));
    const float x = ((xn * 0.95047f));
    const float y = ((yn * 1.0f));
    const float z = ((zn * 1.08883f));
    const float r = ((((((x * 3.2404542f)) - ((y * 1.5371385f)))) - ((z * 0.4985314f))));
    const float g = ((((((x * (-0.969266f))) + ((y * 1.8760108f)))) + ((z * 0.041556f))));
    const float bRgb = ((((((x * 0.0556434f)) - ((y * 0.2040259f)))) + ((z * 1.0572252f))));
    return float3(r, g, bRgb);
}

static float4 mixPreconvertedColors_5(float3 convA, float3 convB, float alphaA, float alphaB, float t) {
    const float weightA = ((alphaA * ((1.0f - t))));
    const float weightB = ((alphaB * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 mixed = awMix(convA, convB, weightA, weightB, safeWeight);
    return float4(sRGBToP3(labToRgb(oklchToOklab(mixed))), totalWeight);
}
} // namespace S_FlowingGradient

using namespace S_FlowingGradient;

fragment float4 FlowingGradient_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 flowCentred_9 = ((uv - 0.5f));
    const float aspect_10 = ((uniforms._sys.viewportSize.x / max(uniforms._sys.viewportSize.y, 0.000001f)));
    const float flowTime_12 = ((uniforms.n_x._animTime * 0.075f));
    const float flowSeed_13 = ((uniforms.n_x.seed * 0.17f));
    const float flowStrength_14 = uniforms.n_x.distortion;
    const float flowAngle_11 = ((((mxNoiseFloat3(float3(((((flowCentred_9.x * 0.8f)) + ((flowTime_12 * 0.4f)))), ((((flowCentred_9.y * 0.8f)) - ((flowTime_12 * 0.25f)))), flowSeed_13)) * 12.566370614359172f)) * flowStrength_14));
    const float2 flowSpun_8 = float2((((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * cos(flowAngle_11))) - (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * sin(flowAngle_11))))), (((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * sin(flowAngle_11))) + (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * cos(flowAngle_11))))));
    const float2 flowRot_7 = float2(flowSpun_8.x, ((flowSpun_8.y * aspect_10)));
    const float flowShearX_6 = ((flowRot_7.x + ((((sin(((((flowRot_7.y * 5.0f)) + ((flowTime_12 * 2.0f))))) / 50.0f)) * flowStrength_14))));
    const float4 flowWarp1_5 = chainedWarpStep(float2(flowShearX_6, ((flowRot_7.y + ((((sin(((((flowShearX_6 * 7.5f)) + ((flowTime_12 * 2.0f))))) / 25.0f)) * flowStrength_14))))), 2.0f, ((((flowTime_12 * 0.5f)) + flowSeed_13)), float2(5.2f, 1.3f), float2(1.7f, 9.2f), 0.25f, flowStrength_14);
    const float flowHardness_4 = pow(((((flowWarp1_5.z * 0.5f)) + 0.5f)), 1.5f);
    const float flowEdge_3 = mix(0.5f, 0.008f, flowHardness_4);
    const float flowTz_16 = ((((flowTime_12 * 0.3f)) + flowSeed_13));
    const float4 flowWarp2_15 = chainedWarpStep(flowWarp1_5.xy, 1.5f, flowTz_16, float2(8.3f, 2.8f), float2(3.1f, 7.4f), 0.2f, flowStrength_14);
    const float flowT1_2 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, mxNoiseFloat3(float3(((flowWarp2_15.x * 1.8f)), ((flowWarp2_15.y * 1.8f)), flowTz_16)));
    const float4 flowRow1_1 = mixColors(uniforms.n_x.colorA, uniforms.n_x.colorB, flowT1_2);
    const float4 flowRow2_17 = mixColors(uniforms.n_x.colorC, uniforms.n_x.colorD, flowT1_2);
    const float flowT2_18 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, flowWarp1_5.w);
    const float4 flowBase_0 = mixColors(flowRow1_1, flowRow2_17, flowT2_18);
    float4 composed_19 = float4(clamp(((flowBase_0.rgb * ((((((((((flowWarp2_15.z * 0.5f)) + 0.5f)) * 0.12f)) + 0.94f)) * ((1.0f + ((((max(((1.0f - abs(((((flowT1_2 * 2.0f)) - 1.0f))))), ((1.0f - abs(((((flowT2_18 * 2.0f)) - 1.0f)))))) * flowHardness_4)) * 0.35f)))))))), float3(0.0f), float3(1.0f)), flowBase_0.a);
    return composed_19;
}

fragment float4 FlowingGradient_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 flowCentred_9 = ((uv - 0.5f));
    const float aspect_10 = ((uniforms._sys.viewportSize.x / max(uniforms._sys.viewportSize.y, 0.000001f)));
    const float flowTime_12 = ((uniforms.n_x._animTime * 0.075f));
    const float flowSeed_13 = ((uniforms.n_x.seed * 0.17f));
    const float flowStrength_14 = uniforms.n_x.distortion;
    const float flowAngle_11 = ((((mxNoiseFloat3(float3(((((flowCentred_9.x * 0.8f)) + ((flowTime_12 * 0.4f)))), ((((flowCentred_9.y * 0.8f)) - ((flowTime_12 * 0.25f)))), flowSeed_13)) * 12.566370614359172f)) * flowStrength_14));
    const float2 flowSpun_8 = float2((((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * cos(flowAngle_11))) - (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * sin(flowAngle_11))))), (((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * sin(flowAngle_11))) + (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * cos(flowAngle_11))))));
    const float2 flowRot_7 = float2(flowSpun_8.x, ((flowSpun_8.y * aspect_10)));
    const float flowShearX_6 = ((flowRot_7.x + ((((sin(((((flowRot_7.y * 5.0f)) + ((flowTime_12 * 2.0f))))) / 50.0f)) * flowStrength_14))));
    const float4 flowWarp1_5 = chainedWarpStep(float2(flowShearX_6, ((flowRot_7.y + ((((sin(((((flowShearX_6 * 7.5f)) + ((flowTime_12 * 2.0f))))) / 25.0f)) * flowStrength_14))))), 2.0f, ((((flowTime_12 * 0.5f)) + flowSeed_13)), float2(5.2f, 1.3f), float2(1.7f, 9.2f), 0.25f, flowStrength_14);
    const float flowHardness_4 = pow(((((flowWarp1_5.z * 0.5f)) + 0.5f)), 1.5f);
    const float flowEdge_3 = mix(0.5f, 0.008f, flowHardness_4);
    const float flowTz_16 = ((((flowTime_12 * 0.3f)) + flowSeed_13));
    const float4 flowWarp2_15 = chainedWarpStep(flowWarp1_5.xy, 1.5f, flowTz_16, float2(8.3f, 2.8f), float2(3.1f, 7.4f), 0.2f, flowStrength_14);
    const float flowT1_2 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, mxNoiseFloat3(float3(((flowWarp2_15.x * 1.8f)), ((flowWarp2_15.y * 1.8f)), flowTz_16)));
    const MixStep flowRow1_1 = mixPreconvertedInSpace(uniforms.n_x.convA, uniforms.n_x.colorA.a, uniforms.n_x.convB, uniforms.n_x.colorB.a, flowT1_2);
    const MixStep flowRow2_17 = mixPreconvertedInSpace(uniforms.n_x.convC, uniforms.n_x.colorC.a, uniforms.n_x.convD, uniforms.n_x.colorD.a, flowT1_2);
    const float flowT2_18 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, flowWarp1_5.w);
    const float4 flowBase_0 = mixPreconvertedColors(flowRow1_1.conv, flowRow2_17.conv, flowRow1_1.alpha, flowRow2_17.alpha, flowT2_18);
    float4 composed_19 = float4(clamp(((flowBase_0.rgb * ((((((((((flowWarp2_15.z * 0.5f)) + 0.5f)) * 0.12f)) + 0.94f)) * ((1.0f + ((((max(((1.0f - abs(((((flowT1_2 * 2.0f)) - 1.0f))))), ((1.0f - abs(((((flowT2_18 * 2.0f)) - 1.0f)))))) * flowHardness_4)) * 0.35f)))))))), float3(0.0f), float3(1.0f)), flowBase_0.a);
    return composed_19;
}

fragment float4 FlowingGradient_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 flowCentred_9 = ((uv - 0.5f));
    const float aspect_10 = ((uniforms._sys.viewportSize.x / max(uniforms._sys.viewportSize.y, 0.000001f)));
    const float flowTime_12 = ((uniforms.n_x._animTime * 0.075f));
    const float flowSeed_13 = ((uniforms.n_x.seed * 0.17f));
    const float flowStrength_14 = uniforms.n_x.distortion;
    const float flowAngle_11 = ((((mxNoiseFloat3(float3(((((flowCentred_9.x * 0.8f)) + ((flowTime_12 * 0.4f)))), ((((flowCentred_9.y * 0.8f)) - ((flowTime_12 * 0.25f)))), flowSeed_13)) * 12.566370614359172f)) * flowStrength_14));
    const float2 flowSpun_8 = float2((((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * cos(flowAngle_11))) - (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * sin(flowAngle_11))))), (((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * sin(flowAngle_11))) + (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * cos(flowAngle_11))))));
    const float2 flowRot_7 = float2(flowSpun_8.x, ((flowSpun_8.y * aspect_10)));
    const float flowShearX_6 = ((flowRot_7.x + ((((sin(((((flowRot_7.y * 5.0f)) + ((flowTime_12 * 2.0f))))) / 50.0f)) * flowStrength_14))));
    const float4 flowWarp1_5 = chainedWarpStep(float2(flowShearX_6, ((flowRot_7.y + ((((sin(((((flowShearX_6 * 7.5f)) + ((flowTime_12 * 2.0f))))) / 25.0f)) * flowStrength_14))))), 2.0f, ((((flowTime_12 * 0.5f)) + flowSeed_13)), float2(5.2f, 1.3f), float2(1.7f, 9.2f), 0.25f, flowStrength_14);
    const float flowHardness_4 = pow(((((flowWarp1_5.z * 0.5f)) + 0.5f)), 1.5f);
    const float flowEdge_3 = mix(0.5f, 0.008f, flowHardness_4);
    const float flowTz_16 = ((((flowTime_12 * 0.3f)) + flowSeed_13));
    const float4 flowWarp2_15 = chainedWarpStep(flowWarp1_5.xy, 1.5f, flowTz_16, float2(8.3f, 2.8f), float2(3.1f, 7.4f), 0.2f, flowStrength_14);
    const float flowT1_2 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, mxNoiseFloat3(float3(((flowWarp2_15.x * 1.8f)), ((flowWarp2_15.y * 1.8f)), flowTz_16)));
    const MixStep flowRow1_1 = mixPreconvertedInSpace(uniforms.n_x.convA, uniforms.n_x.colorA.a, uniforms.n_x.convB, uniforms.n_x.colorB.a, flowT1_2);
    const MixStep flowRow2_17 = mixPreconvertedInSpace(uniforms.n_x.convC, uniforms.n_x.colorC.a, uniforms.n_x.convD, uniforms.n_x.colorD.a, flowT1_2);
    const float flowT2_18 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, flowWarp1_5.w);
    const float4 flowBase_0 = mixPreconvertedColors_2(flowRow1_1.conv, flowRow2_17.conv, flowRow1_1.alpha, flowRow2_17.alpha, flowT2_18);
    float4 composed_19 = float4(clamp(((flowBase_0.rgb * ((((((((((flowWarp2_15.z * 0.5f)) + 0.5f)) * 0.12f)) + 0.94f)) * ((1.0f + ((((max(((1.0f - abs(((((flowT1_2 * 2.0f)) - 1.0f))))), ((1.0f - abs(((((flowT2_18 * 2.0f)) - 1.0f)))))) * flowHardness_4)) * 0.35f)))))))), float3(0.0f), float3(1.0f)), flowBase_0.a);
    return composed_19;
}

fragment float4 FlowingGradient_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 flowCentred_9 = ((uv - 0.5f));
    const float aspect_10 = ((uniforms._sys.viewportSize.x / max(uniforms._sys.viewportSize.y, 0.000001f)));
    const float flowTime_12 = ((uniforms.n_x._animTime * 0.075f));
    const float flowSeed_13 = ((uniforms.n_x.seed * 0.17f));
    const float flowStrength_14 = uniforms.n_x.distortion;
    const float flowAngle_11 = ((((mxNoiseFloat3(float3(((((flowCentred_9.x * 0.8f)) + ((flowTime_12 * 0.4f)))), ((((flowCentred_9.y * 0.8f)) - ((flowTime_12 * 0.25f)))), flowSeed_13)) * 12.566370614359172f)) * flowStrength_14));
    const float2 flowSpun_8 = float2((((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * cos(flowAngle_11))) - (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * sin(flowAngle_11))))), (((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * sin(flowAngle_11))) + (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * cos(flowAngle_11))))));
    const float2 flowRot_7 = float2(flowSpun_8.x, ((flowSpun_8.y * aspect_10)));
    const float flowShearX_6 = ((flowRot_7.x + ((((sin(((((flowRot_7.y * 5.0f)) + ((flowTime_12 * 2.0f))))) / 50.0f)) * flowStrength_14))));
    const float4 flowWarp1_5 = chainedWarpStep(float2(flowShearX_6, ((flowRot_7.y + ((((sin(((((flowShearX_6 * 7.5f)) + ((flowTime_12 * 2.0f))))) / 25.0f)) * flowStrength_14))))), 2.0f, ((((flowTime_12 * 0.5f)) + flowSeed_13)), float2(5.2f, 1.3f), float2(1.7f, 9.2f), 0.25f, flowStrength_14);
    const float flowHardness_4 = pow(((((flowWarp1_5.z * 0.5f)) + 0.5f)), 1.5f);
    const float flowEdge_3 = mix(0.5f, 0.008f, flowHardness_4);
    const float flowTz_16 = ((((flowTime_12 * 0.3f)) + flowSeed_13));
    const float4 flowWarp2_15 = chainedWarpStep(flowWarp1_5.xy, 1.5f, flowTz_16, float2(8.3f, 2.8f), float2(3.1f, 7.4f), 0.2f, flowStrength_14);
    const float flowT1_2 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, mxNoiseFloat3(float3(((flowWarp2_15.x * 1.8f)), ((flowWarp2_15.y * 1.8f)), flowTz_16)));
    const MixStep flowRow1_1 = mixPreconvertedInSpace(uniforms.n_x.convA, uniforms.n_x.colorA.a, uniforms.n_x.convB, uniforms.n_x.colorB.a, flowT1_2);
    const MixStep flowRow2_17 = mixPreconvertedInSpace(uniforms.n_x.convC, uniforms.n_x.colorC.a, uniforms.n_x.convD, uniforms.n_x.colorD.a, flowT1_2);
    const float flowT2_18 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, flowWarp1_5.w);
    const float4 flowBase_0 = mixPreconvertedColors_3(flowRow1_1.conv, flowRow2_17.conv, flowRow1_1.alpha, flowRow2_17.alpha, flowT2_18);
    float4 composed_19 = float4(clamp(((flowBase_0.rgb * ((((((((((flowWarp2_15.z * 0.5f)) + 0.5f)) * 0.12f)) + 0.94f)) * ((1.0f + ((((max(((1.0f - abs(((((flowT1_2 * 2.0f)) - 1.0f))))), ((1.0f - abs(((((flowT2_18 * 2.0f)) - 1.0f)))))) * flowHardness_4)) * 0.35f)))))))), float3(0.0f), float3(1.0f)), flowBase_0.a);
    return composed_19;
}

fragment float4 FlowingGradient_v4_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 flowCentred_9 = ((uv - 0.5f));
    const float aspect_10 = ((uniforms._sys.viewportSize.x / max(uniforms._sys.viewportSize.y, 0.000001f)));
    const float flowTime_12 = ((uniforms.n_x._animTime * 0.075f));
    const float flowSeed_13 = ((uniforms.n_x.seed * 0.17f));
    const float flowStrength_14 = uniforms.n_x.distortion;
    const float flowAngle_11 = ((((mxNoiseFloat3(float3(((((flowCentred_9.x * 0.8f)) + ((flowTime_12 * 0.4f)))), ((((flowCentred_9.y * 0.8f)) - ((flowTime_12 * 0.25f)))), flowSeed_13)) * 12.566370614359172f)) * flowStrength_14));
    const float2 flowSpun_8 = float2((((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * cos(flowAngle_11))) - (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * sin(flowAngle_11))))), (((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * sin(flowAngle_11))) + (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * cos(flowAngle_11))))));
    const float2 flowRot_7 = float2(flowSpun_8.x, ((flowSpun_8.y * aspect_10)));
    const float flowShearX_6 = ((flowRot_7.x + ((((sin(((((flowRot_7.y * 5.0f)) + ((flowTime_12 * 2.0f))))) / 50.0f)) * flowStrength_14))));
    const float4 flowWarp1_5 = chainedWarpStep(float2(flowShearX_6, ((flowRot_7.y + ((((sin(((((flowShearX_6 * 7.5f)) + ((flowTime_12 * 2.0f))))) / 25.0f)) * flowStrength_14))))), 2.0f, ((((flowTime_12 * 0.5f)) + flowSeed_13)), float2(5.2f, 1.3f), float2(1.7f, 9.2f), 0.25f, flowStrength_14);
    const float flowHardness_4 = pow(((((flowWarp1_5.z * 0.5f)) + 0.5f)), 1.5f);
    const float flowEdge_3 = mix(0.5f, 0.008f, flowHardness_4);
    const float flowTz_16 = ((((flowTime_12 * 0.3f)) + flowSeed_13));
    const float4 flowWarp2_15 = chainedWarpStep(flowWarp1_5.xy, 1.5f, flowTz_16, float2(8.3f, 2.8f), float2(3.1f, 7.4f), 0.2f, flowStrength_14);
    const float flowT1_2 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, mxNoiseFloat3(float3(((flowWarp2_15.x * 1.8f)), ((flowWarp2_15.y * 1.8f)), flowTz_16)));
    const MixStep flowRow1_1 = mixPreconvertedInSpace(uniforms.n_x.convA, uniforms.n_x.colorA.a, uniforms.n_x.convB, uniforms.n_x.colorB.a, flowT1_2);
    const MixStep flowRow2_17 = mixPreconvertedInSpace(uniforms.n_x.convC, uniforms.n_x.colorC.a, uniforms.n_x.convD, uniforms.n_x.colorD.a, flowT1_2);
    const float flowT2_18 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, flowWarp1_5.w);
    const float4 flowBase_0 = mixPreconvertedColors_4(flowRow1_1.conv, flowRow2_17.conv, flowRow1_1.alpha, flowRow2_17.alpha, flowT2_18);
    float4 composed_19 = float4(clamp(((flowBase_0.rgb * ((((((((((flowWarp2_15.z * 0.5f)) + 0.5f)) * 0.12f)) + 0.94f)) * ((1.0f + ((((max(((1.0f - abs(((((flowT1_2 * 2.0f)) - 1.0f))))), ((1.0f - abs(((((flowT2_18 * 2.0f)) - 1.0f)))))) * flowHardness_4)) * 0.35f)))))))), float3(0.0f), float3(1.0f)), flowBase_0.a);
    return composed_19;
}

fragment float4 FlowingGradient_v5_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 flowCentred_9 = ((uv - 0.5f));
    const float aspect_10 = ((uniforms._sys.viewportSize.x / max(uniforms._sys.viewportSize.y, 0.000001f)));
    const float flowTime_12 = ((uniforms.n_x._animTime * 0.075f));
    const float flowSeed_13 = ((uniforms.n_x.seed * 0.17f));
    const float flowStrength_14 = uniforms.n_x.distortion;
    const float flowAngle_11 = ((((mxNoiseFloat3(float3(((((flowCentred_9.x * 0.8f)) + ((flowTime_12 * 0.4f)))), ((((flowCentred_9.y * 0.8f)) - ((flowTime_12 * 0.25f)))), flowSeed_13)) * 12.566370614359172f)) * flowStrength_14));
    const float2 flowSpun_8 = float2((((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * cos(flowAngle_11))) - (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * sin(flowAngle_11))))), (((((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).x * sin(flowAngle_11))) + (((float2(flowCentred_9.x, ((flowCentred_9.y / aspect_10)))).y * cos(flowAngle_11))))));
    const float2 flowRot_7 = float2(flowSpun_8.x, ((flowSpun_8.y * aspect_10)));
    const float flowShearX_6 = ((flowRot_7.x + ((((sin(((((flowRot_7.y * 5.0f)) + ((flowTime_12 * 2.0f))))) / 50.0f)) * flowStrength_14))));
    const float4 flowWarp1_5 = chainedWarpStep(float2(flowShearX_6, ((flowRot_7.y + ((((sin(((((flowShearX_6 * 7.5f)) + ((flowTime_12 * 2.0f))))) / 25.0f)) * flowStrength_14))))), 2.0f, ((((flowTime_12 * 0.5f)) + flowSeed_13)), float2(5.2f, 1.3f), float2(1.7f, 9.2f), 0.25f, flowStrength_14);
    const float flowHardness_4 = pow(((((flowWarp1_5.z * 0.5f)) + 0.5f)), 1.5f);
    const float flowEdge_3 = mix(0.5f, 0.008f, flowHardness_4);
    const float flowTz_16 = ((((flowTime_12 * 0.3f)) + flowSeed_13));
    const float4 flowWarp2_15 = chainedWarpStep(flowWarp1_5.xy, 1.5f, flowTz_16, float2(8.3f, 2.8f), float2(3.1f, 7.4f), 0.2f, flowStrength_14);
    const float flowT1_2 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, mxNoiseFloat3(float3(((flowWarp2_15.x * 1.8f)), ((flowWarp2_15.y * 1.8f)), flowTz_16)));
    const MixStep flowRow1_1 = mixPreconvertedInSpace(uniforms.n_x.convA, uniforms.n_x.colorA.a, uniforms.n_x.convB, uniforms.n_x.colorB.a, flowT1_2);
    const MixStep flowRow2_17 = mixPreconvertedInSpace(uniforms.n_x.convC, uniforms.n_x.colorC.a, uniforms.n_x.convD, uniforms.n_x.colorD.a, flowT1_2);
    const float flowT2_18 = smoothstep(((flowEdge_3 * (-1.0f))), flowEdge_3, flowWarp1_5.w);
    const float4 flowBase_0 = mixPreconvertedColors_5(flowRow1_1.conv, flowRow2_17.conv, flowRow1_1.alpha, flowRow2_17.alpha, flowT2_18);
    float4 composed_19 = float4(clamp(((flowBase_0.rgb * ((((((((((flowWarp2_15.z * 0.5f)) + 0.5f)) * 0.12f)) + 0.94f)) * ((1.0f + ((((max(((1.0f - abs(((((flowT1_2 * 2.0f)) - 1.0f))))), ((1.0f - abs(((((flowT2_18 * 2.0f)) - 1.0f)))))) * flowHardness_4)) * 0.35f)))))))), float3(0.0f), float3(1.0f)), flowBase_0.a);
    return composed_19;
}
