// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: FlowField
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_FlowField {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct padded_1 {
    float strength;
    float detail;
    float speed;
    float evolutionSpeed;
    float seed;
    float edges;
    float _opacity;
    float _animTime;
    float _animTime_evolution;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    padded_1 n_x;
    padded n_child;
    struct_1 _sys;
};

static float2 edgeClampUV(float2 uv) {
    return clamp(uv, float2(0), float2(1));
}

static float mxFade(float t) {
    return ((((((t * t)) * t)) * ((((t * ((((t * 6.0f)) - 15.0f)))) + 10.0f))));
}

static uint mxRotl32(uint x, int k) {
    return ((((x << uint(k))) | ((x >> uint(((32 - k)))))));
}

static uint mxBjfinal(uint a0, uint b0, uint c0) {
    uint a = a0;
    uint b = b0;
    uint c = c0;
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 14)));
    a = ((a ^ c));
    a = ((a - mxRotl32(c, 11)));
    b = ((b ^ a));
    b = ((b - mxRotl32(a, 25)));
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 16)));
    a = ((a ^ c));
    a = ((a - mxRotl32(c, 4)));
    b = ((b ^ a));
    b = ((b - mxRotl32(a, 14)));
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 24)));
    return c;
}

static uint mxHashInt2(int x, int y, int z) {
    const uint len = 3u;
    const uint seed = ((((3735928559u + ((len << 2u)))) + 13u));
    const uint a = ((seed + uint(x)));
    const uint b = ((seed + uint(y)));
    const uint c = ((seed + uint(z)));
    return mxBjfinal(a, b, c);
}

static float mxGradientFloat3(uint hash, float x, float y, float z) {
    const uint h = ((hash & 15u));
    const float u = select(y, x, ((h < 8u)));
    const float inner = select(z, x, ((((h == 12u)) || ((h == 14u)))));
    const float v = select(inner, y, ((h < 4u)));
    const float uu = select(u, (-(u)), ((((h & 1u)) != 0u)));
    const float vv = select(v, (-(v)), ((((h & 2u)) != 0u)));
    return ((uu + vv));
}

static float mxTrilerp(float v0, float v1, float v2, float v3, float v4, float v5, float v6, float v7, float s, float t, float r) {
    const float s1 = ((1.0f - s));
    const float t1 = ((1.0f - t));
    const float r1 = ((1.0f - r));
    return ((((r1 * ((((t1 * ((((v0 * s1)) + ((v1 * s)))))) + ((t * ((((v2 * s1)) + ((v3 * s)))))))))) + ((r * ((((t1 * ((((v4 * s1)) + ((v5 * s)))))) + ((t * ((((v6 * s1)) + ((v7 * s))))))))))));
}

static float mxGradientScale3d(float v) {
    return ((0.982f * v));
}

static float mxPerlinNoiseFloat3(float3 p) {
    const int X = int(floor(p.x));
    const int Y = int(floor(p.y));
    const int Z = int(floor(p.z));
    const float fx = ((p.x - float(X)));
    const float fy = ((p.y - float(Y)));
    const float fz = ((p.z - float(Z)));
    const float u = mxFade(fx);
    const float v = mxFade(fy);
    const float w = mxFade(fz);
    const float result = mxTrilerp(mxGradientFloat3(mxHashInt2(X, Y, Z), fx, fy, fz), mxGradientFloat3(mxHashInt2(((X + 1)), Y, Z), ((fx - 1.0f)), fy, fz), mxGradientFloat3(mxHashInt2(X, ((Y + 1)), Z), fx, ((fy - 1.0f)), fz), mxGradientFloat3(mxHashInt2(((X + 1)), ((Y + 1)), Z), ((fx - 1.0f)), ((fy - 1.0f)), fz), mxGradientFloat3(mxHashInt2(X, Y, ((Z + 1))), fx, fy, ((fz - 1.0f))), mxGradientFloat3(mxHashInt2(((X + 1)), Y, ((Z + 1))), ((fx - 1.0f)), fy, ((fz - 1.0f))), mxGradientFloat3(mxHashInt2(X, ((Y + 1)), ((Z + 1))), fx, ((fy - 1.0f)), ((fz - 1.0f))), mxGradientFloat3(mxHashInt2(((X + 1)), ((Y + 1)), ((Z + 1))), ((fx - 1.0f)), ((fy - 1.0f)), ((fz - 1.0f))), u, v, w);
    return mxGradientScale3d(result);
}

static float mxNoiseFloat3(float3 p) {
    return mxPerlinNoiseFloat3(p);
}

static float2 flowFieldUV(float2 uv, float aspect, float scale, float strength, float time, float evolutionTime) {
    const float2 aspectCorrectedUV = float2(((uv.x * aspect)), uv.y);
    const float drift1 = ((time * 0.7f));
    const float evolve1 = ((evolutionTime * 0.2f));
    const float angle1 = ((mxNoiseFloat3(float3(((((aspectCorrectedUV.x * scale)) + ((drift1 * 0.3f)))), ((((aspectCorrectedUV.y * scale)) + ((drift1 * 0.5f)))), evolve1)) * 6.283185307179586f));
    const float2 flow1 = float2(cos(angle1), sin(angle1));
    const float drift2 = ((time * 0.5f));
    const float evolve2 = ((evolutionTime * 0.15f));
    const float angle2 = ((mxNoiseFloat3(float3(((((((aspectCorrectedUV.x * ((scale * 2.3f)))) + ((drift2 * (-0.4f))))) + 173.5f)), ((((((aspectCorrectedUV.y * ((scale * 2.3f)))) + ((drift2 * 0.3f)))) + 291.7f)), ((evolve2 + 50.0f)))) * 6.283185307179586f));
    const float2 flow2 = float2(cos(angle2), sin(angle2));
    const float drift3 = ((time * 0.3f));
    const float evolve3 = ((evolutionTime * 0.1f));
    const float angle3 = ((mxNoiseFloat3(float3(((((((aspectCorrectedUV.x * ((scale * 4.7f)))) + ((drift3 * 0.2f)))) + 527.3f)), ((((((aspectCorrectedUV.y * ((scale * 4.7f)))) + ((drift3 * (-0.6f))))) + 839.1f)), ((evolve3 + 100.0f)))) * 6.283185307179586f));
    const float2 flow3 = float2(cos(angle3), sin(angle3));
    const float2 combinedFlow = ((((flow1 + ((flow2 * 0.5f)))) + ((flow3 * 0.25f))));
    const float flowLength = max(length(combinedFlow), 1.0e-3f);
    const float2 normalizedFlow = ((combinedFlow / flowLength));
    const float2 finalFlow = float2(((((normalizedFlow.x * strength)) / aspect)), ((normalizedFlow.y * strength)));
    return float2(((uv.x + finalFlow.x)), ((uv.y + finalFlow.y)));
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float edgeTransparentMask(float2 uv) {
    const float inX = ((step(0.0f, uv.x) * step(uv.x, 1.0f)));
    const float inY = ((step(0.0f, uv.y) * step(uv.y, 1.0f)));
    return ((inX * inY));
}

static float2 edgeMirrorUV(float2 uv) {
    const float mirrorX = (fmod(abs(uv.x), 2.0f));
    const float mirrorY = (fmod(abs(uv.y), 2.0f));
    return float2(select(mirrorX, ((2.0f - mirrorX)), ((mirrorX >= 1.0f))), select(mirrorY, ((2.0f - mirrorY)), ((mirrorY >= 1.0f))));
}

static float2 edgeWrapUV(float2 uv) {
    return fract(uv);
}
} // namespace S_FlowField

using namespace S_FlowField;

fragment float4 FlowField_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 foldUV_0 = edgeClampUV(flowFieldUV(uv, uniforms._sys.aspect, uniforms.n_x.detail, uniforms.n_x.strength, ((((uniforms.n_x._animTime + uniforms.n_x.seed)) * 0.1f)), ((((uniforms.n_x._animTime_evolution + uniforms.n_x.seed)) * 0.1f))));
    float4 composed_1 = media_0.sample(linearClamp, foldUV_0);
    return composed_1;
}

fragment float4 FlowField_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 foldUV_1 = flowFieldUV(uv, uniforms._sys.aspect, uniforms.n_x.detail, uniforms.n_x.strength, ((((uniforms.n_x._animTime + uniforms.n_x.seed)) * 0.1f)), ((((uniforms.n_x._animTime_evolution + uniforms.n_x.seed)) * 0.1f)));
    const float4 sibs_0 = media_0.sample(linearClamp, foldUV_1);
    float4 composed_2 = float4(sibs_0.rgb, ((sibs_0.a * ((1.0f * edgeTransparentMask(flowFieldUV(uv, uniforms._sys.aspect, uniforms.n_x.detail, uniforms.n_x.strength, ((((uniforms.n_x._animTime + uniforms.n_x.seed)) * 0.1f)), ((((uniforms.n_x._animTime_evolution + uniforms.n_x.seed)) * 0.1f)))))))));
    return composed_2;
}

fragment float4 FlowField_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 foldUV_0 = edgeMirrorUV(flowFieldUV(uv, uniforms._sys.aspect, uniforms.n_x.detail, uniforms.n_x.strength, ((((uniforms.n_x._animTime + uniforms.n_x.seed)) * 0.1f)), ((((uniforms.n_x._animTime_evolution + uniforms.n_x.seed)) * 0.1f))));
    float4 composed_1 = media_0.sample(linearClamp, foldUV_0);
    return composed_1;
}

fragment float4 FlowField_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 foldUV_0 = edgeWrapUV(flowFieldUV(uv, uniforms._sys.aspect, uniforms.n_x.detail, uniforms.n_x.strength, ((((uniforms.n_x._animTime + uniforms.n_x.seed)) * 0.1f)), ((((uniforms.n_x._animTime_evolution + uniforms.n_x.seed)) * 0.1f))));
    float4 composed_1 = media_0.sample(linearClamp, foldUV_0);
    return composed_1;
}
