// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: Fog
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_Fog {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float4 colorA;
    float4 colorB;
    float seed;
    float speed;
    float turbulence;
    float detail;
    float blending;
    float mouseInfluence;
    float mouseRadius;
    float colorSpace;
    float _opacity;
    char _sk_pad0[12];
};

struct struct_2 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    struct_1 n_x;
    struct_2 _sys;
};

struct FogParams {
    float dt;
    float time;
    float seed;
    float turbulence;
    float curlStrength;
    float velFade;
    float blending;
    float cursorX;
    float cursorY;
    float cursorVelX;
    float cursorVelY;
    float mouseActive;
    float mouseRadSq;
    char _sk_pad0[12];
};

static float3 awMix(float3 a, float3 b, float wA, float wB, float sw) {
    return ((((((a * wA)) + ((b * wB)))) / sw));
}

static float4 mixColors(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 rgb = awMix(colorA.xyz, colorB.xyz, weightA, weightB, safeWeight);
    return float4(rgb, totalWeight);
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float3 p3ToSRGB(float3 p3) {
    const float r = ((((((p3.x * 1.2249401f)) - ((p3.y * 0.2249404f)))) - ((p3.z * 0.0f))));
    const float g = ((((((p3.x * (-0.0420569f))) + ((p3.y * 1.0420571f)))) + ((p3.z * 0.0f))));
    const float b = ((((((p3.x * (-0.0196376f))) - ((p3.y * 0.0786361f)))) + ((p3.z * 1.0982735f))));
    return float3(r, g, b);
}

static float3 rgbToOklab(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float l = ((((((r * 0.4122214708f)) + ((g * 0.5363325363f)))) + ((b * 0.0514459929f))));
    const float m = ((((r * 0.2119034982f)) + ((((g * 0.6806995451f)) + ((b * 0.1073969566f))))));
    const float s = ((((((r * 0.0883024619f)) + ((g * 0.2817188376f)))) + ((b * 0.6299787005f))));
    const float l_ = ((sign(l) * pow(abs(l), 0.3333333333333333f)));
    const float m_ = ((sign(m) * pow(abs(m), 0.3333333333333333f)));
    const float s_ = ((sign(s) * pow(abs(s), 0.3333333333333333f)));
    return float3(((((((l_ * 0.2104542553f)) + ((m_ * 0.793617785f)))) - ((s_ * 0.0040720468f)))), ((((((l_ * 1.9779984951f)) - ((m_ * 2.428592205f)))) + ((s_ * 0.4505937099f)))), ((((((l_ * 0.0259040371f)) + ((m_ * 0.7827717662f)))) - ((s_ * 0.808675766f)))));
}

static float3 oklabToOklch(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float C = sqrt(((((a * a)) + ((b * b)))));
    const float h = atan2(b, a);
    return float3(L, C, h);
}

static float3 oklchToOklab(float3 lch) {
    const float L = lch.x;
    const float C = lch.y;
    const float h = lch.z;
    return float3(L, ((C * cos(h))), ((C * sin(h))));
}

static float3 oklabToRgb(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float l_ = ((((L + ((a * 0.3963377774f)))) + ((b * 0.2158037573f))));
    const float m_ = ((((L - ((a * 0.1055613458f)))) - ((b * 0.0638541728f))));
    const float s_ = ((((L - ((a * 0.0894841775f)))) - ((b * 1.291485548f))));
    const float l = pow(l_, 3.0f);
    const float m = pow(m_, 3.0f);
    const float s = pow(s_, 3.0f);
    return float3(((((((l * 4.0767416621f)) - ((m * 3.3077115913f)))) + ((s * 0.2309699292f)))), ((((((l * (-1.2684380046f))) + ((m * 2.6097574011f)))) - ((s * 0.3413193965f)))), ((((((l * (-0.0041960863f))) - ((m * 0.7034186147f)))) + ((s * 1.707614701f)))));
}

static float3 sRGBToP3(float3 srgb) {
    const float r = ((((((srgb.x * 0.8224621f)) + ((srgb.y * 0.177538f)))) + ((srgb.z * 0.0f))));
    const float g = ((((((srgb.x * 0.0331941f)) + ((srgb.y * 0.9668058f)))) + ((srgb.z * 0.0f))));
    const float b = ((((((srgb.x * 0.0170826f)) + ((srgb.y * 0.0723974f)))) + ((srgb.z * 0.9105199f))));
    return float3(r, g, b);
}

static float4 mixColors_2(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 oklchA = oklabToOklch(rgbToOklab(p3ToSRGB(colorA.xyz)));
    const float3 oklchB = oklabToOklch(rgbToOklab(p3ToSRGB(colorB.xyz)));
    const float3 mixed = awMix(oklchA, oklchB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(oklabToRgb(oklchToOklab(mixed)));
    return float4(rgb, totalWeight);
}

static float4 mixColors_3(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 oklabA = rgbToOklab(p3ToSRGB(colorA.xyz));
    const float3 oklabB = rgbToOklab(p3ToSRGB(colorB.xyz));
    const float3 mixed = awMix(oklabA, oklabB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(oklabToRgb(mixed));
    return float4(rgb, totalWeight);
}

static float3 rgbToHsl(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float maxVal = max(max(r, g), b);
    const float minVal = min(min(r, g), b);
    const float delta = ((maxVal - minVal));
    const float l = ((((maxVal + minVal)) * 0.5f));
    const float satDenom = max(((1.0f - abs(((((l * 2.0f)) - 1.0f))))), 1.0e-4f);
    const float s = ((delta / satDenom));
    const bool isRMax = ((maxVal == r));
    const bool isGMax = ((maxVal == g));
    const float hueR = ((((g - b)) / max(delta, 1.0e-4f)));
    const float hueG = ((2.0f + ((((b - r)) / max(delta, 1.0e-4f)))));
    const float hueB = ((4.0f + ((((r - g)) / max(delta, 1.0e-4f)))));
    const float hue = select(select(hueB, hueG, isGMax), hueR, isRMax);
    const float h = ((hue * 1.0471975512f));
    return float3(h, s, l);
}

static float3 selectRGBBySector(float c, float x, float sector) {
    float r = 0.0f;
    float g = 0.0f;
    float b = 0.0f;
    if ((((sector < 1.0f)))) {
        r = c;
        g = x;
    } else {
        if ((((sector < 2.0f)))) {
            r = x;
            g = c;
        } else {
            if ((((sector < 3.0f)))) {
                g = c;
                b = x;
            } else {
                if ((((sector < 4.0f)))) {
                    g = x;
                    b = c;
                } else {
                    if ((((sector < 5.0f)))) {
                        r = x;
                        b = c;
                    } else {
                        r = c;
                        b = x;
                    }
                }
            }
        }
    }
    return float3(r, g, b);
}

static float3 hslToRgb(float3 hsl) {
    const float h = hsl.x;
    const float s = hsl.y;
    const float l = hsl.z;
    const float c = ((s * ((1.0f - abs(((((l * 2.0f)) - 1.0f)))))));
    const float hPrime = ((h / 1.0471975512f));
    const float x = ((c * ((1.0f - abs((((fmod(hPrime, 2.0f)) - 1.0f)))))));
    const float m = ((l - ((c * 0.5f))));
    const float sector = floor(hPrime);
    return ((selectRGBBySector(c, x, sector) + m));
}

static float4 mixColors_4(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 hslA = rgbToHsl(p3ToSRGB(colorA.xyz));
    const float3 hslB = rgbToHsl(p3ToSRGB(colorB.xyz));
    const float3 mixed = awMix(hslA, hslB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(hslToRgb(mixed));
    return float4(rgb, totalWeight);
}

static float3 rgbToHsv(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float maxVal = max(max(r, g), b);
    const float minVal = min(min(r, g), b);
    const float delta = ((maxVal - minVal));
    const float v = maxVal;
    const float s = ((delta / max(maxVal, 1.0e-4f)));
    const bool isRMax = ((maxVal == r));
    const bool isGMax = ((maxVal == g));
    const float hueR = ((((g - b)) / max(delta, 1.0e-4f)));
    const float hueG = ((2.0f + ((((b - r)) / max(delta, 1.0e-4f)))));
    const float hueB = ((4.0f + ((((r - g)) / max(delta, 1.0e-4f)))));
    const float hue = select(select(hueB, hueG, isGMax), hueR, isRMax);
    const float h = ((hue * 1.0471975512f));
    return float3(h, s, v);
}

static float3 hsvToRgb(float3 hsv) {
    const float h = hsv.x;
    const float s = hsv.y;
    const float v = hsv.z;
    const float c = ((v * s));
    const float hPrime = ((h / 1.0471975512f));
    const float x = ((c * ((1.0f - abs((((fmod(hPrime, 2.0f)) - 1.0f)))))));
    const float m = ((v - c));
    const float sector = floor(hPrime);
    return ((selectRGBBySector(c, x, sector) + m));
}

static float4 mixColors_5(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 hsvA = rgbToHsv(p3ToSRGB(colorA.xyz));
    const float3 hsvB = rgbToHsv(p3ToSRGB(colorB.xyz));
    const float3 mixed = awMix(hsvA, hsvB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(hsvToRgb(mixed));
    return float4(rgb, totalWeight);
}

static float3 rgbToLab(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float x = ((((((r * 0.4124564f)) + ((g * 0.3575761f)))) + ((b * 0.1804375f))));
    const float y = ((((((r * 0.2126729f)) + ((g * 0.7151522f)))) + ((b * 0.072175f))));
    const float z = ((((((r * 0.0193339f)) + ((g * 0.119192f)))) + ((b * 0.9503041f))));
    const float xn = ((x / 0.95047f));
    const float yn = ((y / 1.0f));
    const float zn = ((z / 1.08883f));
    const float fx = select(((((xn * 7.787037037037036f)) + 0.13793103448275862f)), pow(xn, 0.3333333333333333f), ((xn > 0.008856451679035631f)));
    const float fy = select(((((yn * 7.787037037037036f)) + 0.13793103448275862f)), pow(yn, 0.3333333333333333f), ((yn > 0.008856451679035631f)));
    const float fz = select(((((zn * 7.787037037037036f)) + 0.13793103448275862f)), pow(zn, 0.3333333333333333f), ((zn > 0.008856451679035631f)));
    const float L = ((((fy * 116.0f)) - 16.0f));
    const float a = ((((fx - fy)) * 500.0f));
    const float bLab = ((((fy - fz)) * 200.0f));
    return float3(L, a, bLab);
}

static float3 labToRgb(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float fy = ((((L + 16.0f)) / 116.0f));
    const float fx = ((((a / 500.0f)) + fy));
    const float fz = ((fy - ((b / 200.0f))));
    const float xn = select(((((fx - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fx, 3.0f), ((fx > 0.20689655172413793f)));
    const float yn = select(((((fy - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fy, 3.0f), ((fy > 0.20689655172413793f)));
    const float zn = select(((((fz - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fz, 3.0f), ((fz > 0.20689655172413793f)));
    const float x = ((xn * 0.95047f));
    const float y = ((yn * 1.0f));
    const float z = ((zn * 1.08883f));
    const float r = ((((((x * 3.2404542f)) - ((y * 1.5371385f)))) - ((z * 0.4985314f))));
    const float g = ((((((x * (-0.969266f))) + ((y * 1.8760108f)))) + ((z * 0.041556f))));
    const float bRgb = ((((((x * 0.0556434f)) - ((y * 0.2040259f)))) + ((z * 1.0572252f))));
    return float3(r, g, bRgb);
}

static float4 mixColors_6(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 lchA = oklabToOklch(rgbToLab(p3ToSRGB(colorA.xyz)));
    const float3 lchB = oklabToOklch(rgbToLab(p3ToSRGB(colorB.xyz)));
    const float3 mixed = awMix(lchA, lchB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(labToRgb(oklchToOklab(mixed)));
    return float4(rgb, totalWeight);
}

static uint floatBitsToUint1(float x) {
    return as_type<uint>(x);
}

static float noise_hash11(float p) {
    const uint u = floatBitsToUint1(((p * 3141592653.0f)));
    return ((float(((((u * u)) * 3141592653u))) / 4294967296.0f));
}

static float2 seedLattice(float x, float y, float seed, float cellsPerTexel) {
    const float sdx = ((noise_hash11(((seed * 37.31f))) * 97.0f));
    const float sdy = ((noise_hash11(((seed * 83.17f))) * 97.0f));
    return float2(((((x * cellsPerTexel)) + sdx)), ((((y * cellsPerTexel)) + sdy)));
}

static uint2 floatBitsToUint2(float2 v) {
    return as_type<uint2>(v);
}

static float hash12(float2 p) {
    const uint2 u = floatBitsToUint2(((p * float2(141421360, 2718281728))));
    return ((float(((((u.x ^ u.y)) * 3141592653u))) / 4294967296.0f));
}

static float valueHash(float px, float py) {
    return hash12(float2(px, py));
}

static float valueNoise2D(float nx, float ny) {
    const float ix = floor(nx);
    const float iy = floor(ny);
    const float sx = fract(nx);
    const float sy = fract(ny);
    const float ux = ((((sx * sx)) * ((3.0f - ((sx * 2.0f))))));
    const float uy = ((((sy * sy)) * ((3.0f - ((sy * 2.0f))))));
    return mix(mix(valueHash(ix, iy), valueHash(((ix + 1.0f)), iy), ux), mix(valueHash(ix, ((iy + 1.0f))), valueHash(((ix + 1.0f)), ((iy + 1.0f))), ux), uy);
}

static float fbm(float nx, float ny) {
    return ((((((valueNoise2D(nx, ny) * 0.5f)) + ((valueNoise2D(((((nx * 2.0f)) + 5.37f)), ((((ny * 2.0f)) + 9.13f))) * 0.3f)))) + ((valueNoise2D(((((nx * 4.0f)) + 1.79f)), ((((ny * 4.0f)) + 3.51f))) * 0.2f))));
}

static void fogInit(uint cx, uint cy, device float* divergence, device float4* dyeA, device float4* dyeB, constant FogParams& params, device float* pressure, device float4* velA, device float4* velB) {
    auto p = ((&params));
    const uint idx = ((((cy * 256u)) + cx));
    const float2 lat = seedLattice(float(cx), float(cy), ((*p)).seed, 0.01171875f);
    const float dens0 = clamp(((((fbm(((lat.x + 31.7f)), ((lat.y + 53.3f))) * 0.75f)) + 0.25f)), 0.15f, 0.9f);
    const float colorVar = clamp(fbm(lat.x, lat.y), 0.0f, 1.0f);
    dyeA[idx] = float4(dens0, colorVar, 0.0f, 0.0f);
    dyeB[idx] = float4(dens0, colorVar, 0.0f, 0.0f);
    velA[idx] = float4(0);
    velB[idx] = float4(0);
    pressure[idx] = 0.0f;
    divergence[idx] = 0.0f;
}

static float gaussianBrushSq(float distSq, float radiusSq) {
    return exp(((((distSq / radiusSq)) * (-1.0f))));
}

static void fogForce(uint cx, uint cy, constant FogParams& params, device float4* velA) {
    auto p = ((&params));
    const uint idx = ((((cy * 256u)) + cx));
    const float jf = ((float(cx) + 0.5f));
    const float iF = ((float(cy) + 0.5f));
    const float x = ((((jf / 256.0f)) * 6.283185307179586f));
    const float y = ((((iF / 256.0f)) * 6.283185307179586f));
    const float t = ((*p)).time;
    auto vel = ((&velA[idx]));
    const float fx = ((((((((((sin(((((x * 2.0f)) + ((t * 0.31f))))) * cos(((((y * 1.5f)) + ((t * 0.23f))))))) + ((sin(((((((x * 0.7f)) + ((y * 1.3f)))) + ((t * 0.17f))))) * 0.4f)))) * ((*p)).turbulence)) * 10.24f)) * ((*p)).dt));
    const float fy = ((((((((((cos(((((x * 1.5f)) + ((t * 0.27f))))) * sin(((((y * 2.0f)) + ((t * 0.19f))))))) + ((cos(((((((x * 1.1f)) + ((y * 0.9f)))) + ((t * 0.21f))))) * 0.4f)))) * ((*p)).turbulence)) * 10.24f)) * ((*p)).dt));
    const float cdx = ((jf - ((*p)).cursorX));
    const float cdy = ((iF - ((*p)).cursorY));
    const float cursorDistSq = ((((cdx * cdx)) + ((cdy * cdy))));
    const float cursorInf = ((gaussianBrushSq(cursorDistSq, max(((*p)).mouseRadSq, 1.0f)) * ((*p)).mouseActive));
    velA[idx] = float4(((((((*vel)).x + fx)) + ((((*p)).cursorVelX * cursorInf)))), ((((((*vel)).y + fy)) + ((((*p)).cursorVelY * cursorInf)))), ((*vel)).z, 0.0f);
}

static void fogColorRestore(uint cx, uint cy, device float4* dyeA, constant FogParams& params) {
    auto p = ((&params));
    const uint idx = ((((cy * 256u)) + cx));
    const float2 lat = seedLattice(float(cx), float(cy), ((*p)).seed, 0.01171875f);
    const float refRaw = fbm(lat.x, lat.y);
    const float invBlend = ((1.0f - ((*p)).blending));
    const float contrastBoost = ((1.0f + ((invBlend * 5.0f))));
    const float refBoosted = clamp(((((((refRaw - 0.5f)) * contrastBoost)) + 0.5f)), 0.0f, 1.0f);
    auto cell = ((&dyeA[idx]));
    const float rateMult = ((1.0f + ((invBlend * 2.5f))));
    const float blendRate = min(((((((*p)).dt * 0.5f)) * rateMult)), 0.3f);
    dyeA[idx] = float4(((*cell)).x, mix(((*cell)).y, refBoosted, blendRate), 0.0f, 0.0f);
}

static uint nw(int ii, int ji, int di, int dj) {
    const int row = ((((((ii + di)) + 256)) % 256));
    const int col = ((((((ji + dj)) + 256)) % 256));
    return uint(((((row * 256)) + col)));
}

static void fogCurl(uint cx, uint cy, device float4* velA) {
    const uint idx = ((((cy * 256u)) + cx));
    const int ii = int(cy);
    const int ji = int(cx);
    auto vL = ((&velA[nw(ii, ji, 0, (-1))]));
    auto vR = ((&velA[nw(ii, ji, 0, 1)]));
    auto vU = ((&velA[nw(ii, ji, (-1), 0)]));
    auto vD = ((&velA[nw(ii, ji, 1, 0)]));
    const float curlZ = ((((((((*vR)).y - ((*vL)).y)) - ((((*vD)).x - ((*vU)).x)))) * 0.5f));
    auto vel = ((&velA[idx]));
    velA[idx] = float4(((*vel)).x, ((*vel)).y, curlZ, 0.0f);
}

static void fogVorticity(uint cx, uint cy, constant FogParams& params, device float4* velA) {
    auto p = ((&params));
    const uint idx = ((((cy * 256u)) + cx));
    const int ii = int(cy);
    const int ji = int(cx);
    const float cL = abs(velA[nw(ii, ji, 0, (-1))].z);
    const float cR = abs(velA[nw(ii, ji, 0, 1)].z);
    const float cU = abs(velA[nw(ii, ji, (-1), 0)].z);
    const float cD = abs(velA[nw(ii, ji, 1, 0)].z);
    const float cc = velA[idx].z;
    const float gx = ((((cR - cL)) * 0.5f));
    const float gy = ((((cD - cU)) * 0.5f));
    const float gl = max(sqrt(((((gx * gx)) + ((gy * gy))))), 9.999999747378752e-6f);
    const float fx = ((((((((gy / gl)) * cc)) * ((*p)).curlStrength)) * ((*p)).dt));
    const float fy = ((((((((((gx / gl)) * (-1.0f))) * cc)) * ((*p)).curlStrength)) * ((*p)).dt));
    auto vel = ((&velA[idx]));
    velA[idx] = float4(((((*vel)).x + fx)), ((((*vel)).y + fy)), ((*vel)).z, 0.0f);
}

static void fogDivergence(uint cx, uint cy, device float* divergence, device float* pressure, device float4* velA) {
    const uint idx = ((((cy * 256u)) + cx));
    const int ii = int(cy);
    const int ji = int(cx);
    const float vL = velA[nw(ii, ji, 0, (-1))].x;
    const float vR = velA[nw(ii, ji, 0, 1)].x;
    const float vU = velA[nw(ii, ji, (-1), 0)].y;
    const float vD = velA[nw(ii, ji, 1, 0)].y;
    const float div = ((((((vR - vL)) + ((vD - vU)))) * 0.5f));
    pressure[idx] = ((pressure[idx] * 0.8f));
    divergence[idx] = div;
}

static void fogJacobi(uint cx, uint cy, device float* divergence, device float* pressure) {
    const uint idx = ((((cy * 256u)) + cx));
    const int ii = int(cy);
    const int ji = int(cx);
    const float pL = pressure[nw(ii, ji, 0, (-1))];
    const float pR = pressure[nw(ii, ji, 0, 1)];
    const float pU = pressure[nw(ii, ji, (-1), 0)];
    const float pD = pressure[nw(ii, ji, 1, 0)];
    const float div = divergence[idx];
    pressure[idx] = ((((((((((pL + pR)) + pU)) + pD)) - div)) * 0.25f));
}

static void fogGradSubtract(uint cx, uint cy, device float* pressure, device float4* velA) {
    const uint idx = ((((cy * 256u)) + cx));
    const int ii = int(cy);
    const int ji = int(cx);
    const float pL = pressure[nw(ii, ji, 0, (-1))];
    const float pR = pressure[nw(ii, ji, 0, 1)];
    const float pU = pressure[nw(ii, ji, (-1), 0)];
    const float pD = pressure[nw(ii, ji, 1, 0)];
    auto vel = ((&velA[idx]));
    const float vx = ((((*vel)).x - ((((pR - pL)) * 0.5f))));
    const float vy = ((((*vel)).y - ((((pD - pU)) * 0.5f))));
    const float maxVel = 153.60000610351562f;
    const float vLen = max(sqrt(((((vx * vx)) + ((vy * vy))))), 9.999999974752427e-7f);
    const float capScale = ((maxVel / max(vLen, maxVel)));
    velA[idx] = float4(((vx * capScale)), ((vy * capScale)), ((*vel)).z, 0.0f);
}

static void fogAdvectVel(uint cx, uint cy, constant FogParams& params, device float4* velA, device float4* velB) {
    auto p = ((&params));
    const uint idx = ((((cy * 256u)) + cx));
    auto vel = ((&velA[idx]));
    const float srcX = (fmod(((((float(cx) - ((((*vel)).x * ((*p)).dt)))) + 256.0f)), 256.0f));
    const float srcY = (fmod(((((float(cy) - ((((*vel)).y * ((*p)).dt)))) + 256.0f)), 256.0f));
    const float x0 = floor(srcX);
    const float y0 = floor(srcY);
    const float sx = ((srcX - x0));
    const float sy = ((srcY - y0));
    const int ix0 = int(x0);
    const int iy0 = int(y0);
    const int ix1 = ((((ix0 + 1)) % 256));
    const int iy1 = ((((iy0 + 1)) % 256));
    auto v00 = ((&velA[uint(((((iy0 * 256)) + ix0)))]));
    auto v10 = ((&velA[uint(((((iy0 * 256)) + ix1)))]));
    auto v01 = ((&velA[uint(((((iy1 * 256)) + ix0)))]));
    auto v11 = ((&velA[uint(((((iy1 * 256)) + ix1)))]));
    const float decay = ((1.0f + ((((*p)).velFade * ((*p)).dt))));
    velB[idx] = float4(((mix(mix(((*v00)).x, ((*v10)).x, sx), mix(((*v01)).x, ((*v11)).x, sx), sy) / decay)), ((mix(mix(((*v00)).y, ((*v10)).y, sx), mix(((*v01)).y, ((*v11)).y, sx), sy) / decay)), 0.0f, 0.0f);
}

static void fogCopyVel(uint cx, uint cy, device float4* velA, device float4* velB) {
    const uint idx = ((((cy * 256u)) + cx));
    auto v = ((&velB[idx]));
    velA[idx] = float4(((*v)).x, ((*v)).y, 0.0f, 0.0f);
}

static void fogAdvectDens(uint cx, uint cy, device float4* dyeA, device float4* dyeB, constant FogParams& params, device float4* velA) {
    auto p = ((&params));
    const uint idx = ((((cy * 256u)) + cx));
    auto vel = ((&velA[idx]));
    const float srcX = (fmod(((((float(cx) - ((((*vel)).x * ((*p)).dt)))) + 256.0f)), 256.0f));
    const float srcY = (fmod(((((float(cy) - ((((*vel)).y * ((*p)).dt)))) + 256.0f)), 256.0f));
    const float x0 = floor(srcX);
    const float y0 = floor(srcY);
    const float sx = ((srcX - x0));
    const float sy = ((srcY - y0));
    const int ix0 = int(x0);
    const int iy0 = int(y0);
    const int ix1 = ((((ix0 + 1)) % 256));
    const int iy1 = ((((iy0 + 1)) % 256));
    auto d00 = ((&dyeA[uint(((((iy0 * 256)) + ix0)))]));
    auto d10 = ((&dyeA[uint(((((iy0 * 256)) + ix1)))]));
    auto d01 = ((&dyeA[uint(((((iy1 * 256)) + ix0)))]));
    auto d11 = ((&dyeA[uint(((((iy1 * 256)) + ix1)))]));
    dyeB[idx] = float4(mix(mix(((*d00)).x, ((*d10)).x, sx), mix(((*d01)).x, ((*d11)).x, sx), sy), mix(mix(((*d00)).y, ((*d10)).y, sx), mix(((*d01)).y, ((*d11)).y, sx), sy), 0.0f, 0.0f);
}

static void fogCopyDens(uint cx, uint cy, device float4* dyeA, device float4* dyeB) {
    const uint idx = ((((cy * 256u)) + cx));
    auto dd = ((&dyeB[idx]));
    dyeA[idx] = float4(((*dd)).x, ((*dd)).y, 0.0f, 0.0f);
}

static void fogOutput(uint cx, uint cy, device float4* dyeA, texture2d<float, access::write> outTex) {
    const uint idx = ((((cy * 256u)) + cx));
    auto dd = ((&dyeA[idx]));
    outTex.write(float4(((*dd)).x, ((*dd)).y, 0.0f, 0.0f), uint2(cx, cy));
}
} // namespace S_Fog

using namespace S_Fog;

fragment float4 Fog_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Fog_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors_2(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors_2(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Fog_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors_3(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors_3(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Fog_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors_4(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors_4(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Fog_v4_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors_5(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors_5(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Fog_v5_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors_6(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors_6(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

static void Fog_k0_body(uint cx, uint cy, uint _arg_2, device float* divergence, device float4* dyeA, device float4* dyeB, constant FogParams& params, device float* pressure, device float4* velA, device float4* velB) {
    fogInit(cx, cy, divergence, dyeA, dyeB, params, pressure, velA, velB);
}

kernel void Fog_k0(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float4* velB [[buffer(1)]], device float4* dyeA [[buffer(2)]], device float4* dyeB [[buffer(3)]], device float* pressure [[buffer(4)]], device float* divergence [[buffer(5)]], constant FogParams& params [[buffer(6)]], constant uint3& sk_size [[buffer(7)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k0_body(sk_gid.x, sk_gid.y, sk_gid.z, divergence, dyeA, dyeB, params, pressure, velA, velB);
}

static void Fog_k1_body(uint cx, uint cy, uint _arg_2, constant FogParams& params, device float4* velA) {
    fogForce(cx, cy, params, velA);
}

kernel void Fog_k1(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], constant FogParams& params [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k1_body(sk_gid.x, sk_gid.y, sk_gid.z, params, velA);
}

static void Fog_k2_body(uint cx, uint cy, uint _arg_2, device float4* dyeA, constant FogParams& params) {
    fogColorRestore(cx, cy, dyeA, params);
}

kernel void Fog_k2(uint3 sk_gid [[thread_position_in_grid]], device float4* dyeA [[buffer(0)]], constant FogParams& params [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k2_body(sk_gid.x, sk_gid.y, sk_gid.z, dyeA, params);
}

static void Fog_k3_body(uint cx, uint cy, uint _arg_2, device float4* velA) {
    fogCurl(cx, cy, velA);
}

kernel void Fog_k3(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], constant uint3& sk_size [[buffer(1)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k3_body(sk_gid.x, sk_gid.y, sk_gid.z, velA);
}

static void Fog_k4_body(uint cx, uint cy, uint _arg_2, constant FogParams& params, device float4* velA) {
    fogVorticity(cx, cy, params, velA);
}

kernel void Fog_k4(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], constant FogParams& params [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k4_body(sk_gid.x, sk_gid.y, sk_gid.z, params, velA);
}

static void Fog_k5_body(uint cx, uint cy, uint _arg_2, device float* divergence, device float* pressure, device float4* velA) {
    fogDivergence(cx, cy, divergence, pressure, velA);
}

kernel void Fog_k5(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float* pressure [[buffer(1)]], device float* divergence [[buffer(2)]], constant uint3& sk_size [[buffer(3)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k5_body(sk_gid.x, sk_gid.y, sk_gid.z, divergence, pressure, velA);
}

static void Fog_k6_body(uint cx, uint cy, uint _arg_2, device float* divergence, device float* pressure) {
    fogJacobi(cx, cy, divergence, pressure);
}

kernel void Fog_k6(uint3 sk_gid [[thread_position_in_grid]], device float* pressure [[buffer(0)]], device float* divergence [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k6_body(sk_gid.x, sk_gid.y, sk_gid.z, divergence, pressure);
}

static void Fog_k7_body(uint cx, uint cy, uint _arg_2, device float* pressure, device float4* velA) {
    fogGradSubtract(cx, cy, pressure, velA);
}

kernel void Fog_k7(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float* pressure [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k7_body(sk_gid.x, sk_gid.y, sk_gid.z, pressure, velA);
}

static void Fog_k8_body(uint cx, uint cy, uint _arg_2, constant FogParams& params, device float4* velA, device float4* velB) {
    fogAdvectVel(cx, cy, params, velA, velB);
}

kernel void Fog_k8(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float4* velB [[buffer(1)]], constant FogParams& params [[buffer(2)]], constant uint3& sk_size [[buffer(3)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k8_body(sk_gid.x, sk_gid.y, sk_gid.z, params, velA, velB);
}

static void Fog_k9_body(uint cx, uint cy, uint _arg_2, device float4* velA, device float4* velB) {
    fogCopyVel(cx, cy, velA, velB);
}

kernel void Fog_k9(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float4* velB [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k9_body(sk_gid.x, sk_gid.y, sk_gid.z, velA, velB);
}

static void Fog_k10_body(uint cx, uint cy, uint _arg_2, device float4* dyeA, device float4* dyeB, constant FogParams& params, device float4* velA) {
    fogAdvectDens(cx, cy, dyeA, dyeB, params, velA);
}

kernel void Fog_k10(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float4* dyeA [[buffer(1)]], device float4* dyeB [[buffer(2)]], constant FogParams& params [[buffer(3)]], constant uint3& sk_size [[buffer(4)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k10_body(sk_gid.x, sk_gid.y, sk_gid.z, dyeA, dyeB, params, velA);
}

static void Fog_k11_body(uint cx, uint cy, uint _arg_2, device float4* dyeA, device float4* dyeB) {
    fogCopyDens(cx, cy, dyeA, dyeB);
}

kernel void Fog_k11(uint3 sk_gid [[thread_position_in_grid]], device float4* dyeA [[buffer(0)]], device float4* dyeB [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k11_body(sk_gid.x, sk_gid.y, sk_gid.z, dyeA, dyeB);
}

static void Fog_k12_body(uint cx, uint cy, uint _arg_2, device float4* dyeA, texture2d<float, access::write> outTex) {
    fogOutput(cx, cy, dyeA, outTex);
}

kernel void Fog_k12(uint3 sk_gid [[thread_position_in_grid]], device float4* dyeA [[buffer(0)]], texture2d<float, access::write> outTex [[texture(0)]], constant uint3& sk_size [[buffer(1)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Fog_k12_body(sk_gid.x, sk_gid.y, sk_gid.z, dyeA, outTex);
}
