// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: KeyFrames
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_KeyFrames {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float trackers;
    float threshold;
    float variance;
    float agility;
    float lifespan;
    float trail;
    float markerSize;
    float lineWidth;
    float4 markerColor;
    float4 keyframeColor;
    float4 pathColor;
    float _opacity;
    char _sk_pad0[12];
};

struct struct_2 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    struct_1 n_x;
    padded n_child;
    struct_2 _sys;
};

struct TrackParams {
    float dt;
    float trackersF;
    float agility;
    float threshold;
    float variance;
    float lifespan;
    char _sk_pad0[8];
};

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float4 overComposite(float4 base, float3 blended, float overlayAlpha) {
    const float baseWeight = ((base.w * ((1.0f - overlayAlpha))));
    const float finalAlpha = ((overlayAlpha + baseWeight));
    const float3 rgb = ((((blended * overlayAlpha)) + ((base.xyz * baseWeight))));
    return float4(rgb, finalAlpha);
}

static float4 blend_normal(float4 base, float4 overlay2, float opacity) {
    const float overlayAlpha = ((overlay2.w * opacity));
    return overComposite(base, overlay2.xyz, overlayAlpha);
}

static float featureScore_bright(float4 c) {
    const float a = max(c.w, 1.0e-4f);
    const float lumaU = clamp(((((((((c.x * 0.299f)) + ((c.y * 0.587f)))) + ((c.z * 0.114f)))) / a)), 0.0f, 1.0f);
    float score = 0.0f;
    score = ((lumaU * select(0.0f, 1.0f, ((c.w > 0.02f)))));
    return score;
}

static void featureGridScan(uint gx, uint gy, texture2d<float, access::write> grid, texture2d<float> src) {
    const uint2 srcDims = uint2(src.get_width(), src.get_height());
    const float srcW = float(srcDims.x);
    const float srcH = float(srcDims.y);
    const float g = 96.0f;
    const float cu = ((((float(gx) + 0.5f)) / g));
    const float cv = ((((float(gy) + 0.5f)) / g));
    const float q = ((0.25f / g));
    float score = 0.0f;
    for (int sy = 0; ((sy < 2)); sy++) {
        for (int sx = 0; ((sx < 2)); sx++) {
            const float u = ((cu + ((((((float(sx) - 0.5f)) * 2.0f)) * q))));
            const float v = ((cv + ((((((float(sy) - 0.5f)) * 2.0f)) * q))));
            const uint tx = wgsl_f2u(clamp(((u * srcW)), 0.0f, ((srcW - 1.0f))));
            const uint ty = wgsl_f2u(clamp(((v * srcH)), 0.0f, ((srcH - 1.0f))));
            score = max(score, featureScore_bright(src.read(uint2(tx, ty), 0)));
        }
    }
    grid.write(float4(score, 0.0f, 0.0f, 1.0f), uint2(gx, gy));
}

static float trackHash(float x) {
    return fract(((sin(x) * 43758.5453123f)));
}

static void trackerPursuit(uint ti, texture2d<float> featGrid, texture2d<float, access::write> next, constant TrackParams& params, texture2d<float, access::write> present, texture2d<float> prev, texture2d<float> src) {
    auto P = ((&params));
    const float iF = float(ti);
    const float4 head = prev.read(uint2(0u, ti), 0);
    const float4 meta_1 = prev.read(uint2(1u, ti), 0);
    float posX = head.x;
    float posY = head.y;
    float frame = head.z;
    float genStart = ((head.w - 1.0f));
    float missStreak = meta_1.x;
    float gen = meta_1.z;
    float crowdStreak = meta_1.w;
    if ((((head.w < 0.5f)))) {
        posX = ((0.15f + ((0.7f * trackHash(((((iF * 7.31f)) + 1.3f)))))));
        posY = ((0.15f + ((0.7f * trackHash(((((iF * 11.93f)) + 4.7f)))))));
        frame = 0.0f;
        genStart = 0.0f;
        missStreak = 0.0f;
        gen = 1.0f;
    }
    frame = ((frame + 1.0f));
    const float minFeat = max(((*P)).threshold, 0.02f);
    const float Lpref = max(((1.0f - ((((*P)).variance * trackHash(((((((iF * 6.13f)) + ((gen * 0.37f)))) + 2.9f))))))), minFeat);
    const uint2 srcDims = uint2(src.get_width(), src.get_height());
    const float srcW = float(srcDims.x);
    const float srcH = float(srcDims.y);
    const float radius = ((0.035f + ((0.11f * ((*P)).agility))));
    float sumW = 0.0f;
    float sumX = 0.0f;
    float sumY = 0.0f;
    for (int dy = (-3); ((dy <= 3)); dy++) {
        for (int dx = (-3); ((dx <= 3)); dx++) {
            const float ox = ((((float(dx) / 3.0f)) * radius));
            const float oy = ((((float(dy) / 3.0f)) * radius));
            const float cx01 = clamp(((posX + ox)), 0.02f, 0.98f);
            const float cy01 = clamp(((posY + oy)), 0.02f, 0.98f);
            const uint tx = wgsl_f2u(clamp(((cx01 * srcW)), 0.0f, ((srcW - 1.0f))));
            const uint ty = wgsl_f2u(clamp(((cy01 * srcH)), 0.0f, ((srcH - 1.0f))));
            const float s = featureScore_bright(src.read(uint2(tx, ty), 0));
            const float gate = select(0.0f, 1.0f, ((s > minFeat)));
            const float dBand = ((s - Lpref));
            const float aff = ((exp(((((dBand * dBand)) * (-24.0f)))) * gate));
            const float off = ((sqrt(((((ox * ox)) + ((oy * oy))))) / max(radius, 1.0e-3f)));
            const float w = ((aff * ((1.0f - ((0.3f * off))))));
            sumW = ((sumW + w));
            sumX = ((sumX + ((cx01 * w))));
            sumY = ((sumY + ((cy01 * w))));
        }
    }
    const bool locked = ((sumW > 0.8f));
    float bestX = posX;
    float bestY = posY;
    if ((locked)) {
        bestX = ((sumX / sumW));
        bestY = ((sumY / sumW));
    }
    missStreak = select(((missStreak + 1.0f)), 0.0f, locked);
    if (((!(locked)))) {
        const float g = 96.0f;
        float bestW = 0.0f;
        float tgtX = posX;
        float tgtY = posY;
        for (int gy = 0; ((gy < 96)); gy++) {
            for (int gx = 0; ((gx < 96)); gx++) {
                const float cs = featGrid.read(uint2(uint(gx), uint(gy)), 0).x;
                const float cGate = select(0.0f, 1.0f, ((cs > minFeat)));
                const float dB = ((cs - Lpref));
                const float aff = ((exp(((((dB * dB)) * (-14.0f)))) * cGate));
                const float cx = ((((float(gx) + 0.5f)) / g));
                const float cy = ((((float(gy) + 0.5f)) / g));
                const float ddx = ((cx - posX));
                const float ddy = ((cy - posY));
                const float pref = ((0.6f + ((0.8f * trackHash(((((((iF * 3.17f)) + ((float(gx) * 13.71f)))) + ((float(gy) * 29.37f)))))))));
                const float wgt = ((((aff * pref)) / ((1.0f + ((5.0f * ((((ddx * ddx)) + ((ddy * ddy))))))))));
                if ((((wgt > bestW)))) {
                    bestW = wgt;
                    tgtX = cx;
                    tgtY = cy;
                }
            }
        }
        if ((((bestW > 0.02f)))) {
            bestX = clamp(((tgtX + ((((trackHash(((((iF * 5.77f)) + ((gen * 2.13f))))) - 0.5f)) / g)))), 0.02f, 0.98f);
            bestY = clamp(((tgtY + ((((trackHash(((((iF * 8.31f)) + ((gen * 4.97f))))) - 0.5f)) / g)))), 0.02f, 0.98f);
        } else {
            const float ang = ((((trackHash(((((iF * 13.77f)) + ((gen * 3.19f))))) * 6.283185307179586f)) + ((sin(((((frame * 0.02f)) + iF))) * 1.4f))));
            bestX = clamp(((posX + ((cos(ang) * 0.08f)))), 0.03f, 0.97f);
            bestY = clamp(((posY + ((sin(ang) * 0.08f)))), 0.03f, 0.97f);
        }
    }
    const float maxStep = ((((*P)).dt * ((0.15f + ((1.4f * ((*P)).agility))))));
    const float dX = ((bestX - posX));
    const float dY = ((bestY - posY));
    const float dist = sqrt(((((dX * dX)) + ((dY * dY)))));
    const float stepK = min(1.0f, ((maxStep / max(dist, 1.0e-5f))));
    posX = ((posX + ((dX * stepK))));
    posY = ((posY + ((dY * stepK))));
    float crowded = 0.0f;
    const int iN = int(ti);
    for (int k = 0; ((k < iN)); k++) {
        const float kF = float(k);
        const float4 other = prev.read(uint2(0u, uint(k)), 0);
        const float odx = ((other.x - posX));
        const float ody = ((other.y - posY));
        const float near = select(0.0f, 1.0f, ((sqrt(((((odx * odx)) + ((ody * ody))))) < 0.022f)));
        crowded = max(crowded, ((((near * other.w)) * select(0.0f, 1.0f, ((kF < ((*P)).trackersF))))));
    }
    crowdStreak = select(0.0f, ((crowdStreak + 1.0f)), ((crowded > 0.5f)));
    if ((((crowdStreak > 30.0f)))) {
        const float hopAng = ((trackHash(((((((iF * 9.13f)) + ((gen * 5.77f)))) + 2.3f))) * 6.283185307179586f));
        const float hopDist = ((0.05f + ((0.08f * trackHash(((((iF * 4.71f)) + ((gen * 8.11f)))))))));
        posX = clamp(((posX + ((cos(hopAng) * hopDist)))), 0.03f, 0.97f);
        posY = clamp(((posY + ((sin(hopAng) * hopDist)))), 0.03f, 0.97f);
        gen = ((gen + 1.0f));
        genStart = frame;
        missStreak = 0.0f;
        crowdStreak = 0.0f;
    }
    const float lifeFrames = ((((((*P)).lifespan * 60.0f)) * ((0.7f + ((0.6f * trackHash(((((iF * 4.77f)) + ((gen * 1.31f)))))))))));
    const float expired = ((select(0.0f, 1.0f, ((((frame - genStart)) > lifeFrames))) * select(0.0f, 1.0f, ((((*P)).lifespan > 0.01f)))));
    const float lost = select(0.0f, 1.0f, ((missStreak > 90.0f)));
    if ((((((expired + lost)) > 0.5f)))) {
        posX = ((0.1f + ((0.8f * trackHash(((((((iF * 7.31f)) + ((gen * 13.7f)))) + ((frame * 0.013f)))))))));
        posY = ((0.1f + ((0.8f * trackHash(((((((iF * 11.93f)) + ((gen * 17.3f)))) + ((frame * 0.019f)))))))));
        gen = ((gen + 1.0f));
        genStart = frame;
        missStreak = 0.0f;
        crowdStreak = 0.0f;
    }
    const float writeIdx = (fmod(floor(((frame / 8.0f))), 12.0f));
    const float shouldWrite = select(0.0f, 1.0f, (((fmod(frame, 8.0f)) < 0.5f)));
    float bbMinX = posX;
    float bbMinY = posY;
    float bbMaxX = posX;
    float bbMaxY = posY;
    for (int j = 0; ((j < 12)); j++) {
        const float jF = float(j);
        float4 e = prev.read(uint2(uint(((2 + j))), ti), 0);
        const float isSlot = select(0.0f, 1.0f, ((abs(((jF - writeIdx))) < 0.5f)));
        const float doWrite = ((isSlot * shouldWrite));
        e = mix(e, float4(posX, posY, frame, gen), doWrite);
        next.write(e, uint2(uint(((2 + j))), ti));
        present.write(e, uint2(uint(((2 + j))), ti));
        const float live = ((select(0.0f, 1.0f, ((abs(((e.w - gen))) < 0.5f))) * select(0.0f, 1.0f, ((e.z > 0.5f)))));
        bbMinX = min(bbMinX, mix(posX, e.x, live));
        bbMinY = min(bbMinY, mix(posY, e.y, live));
        bbMaxX = max(bbMaxX, mix(posX, e.x, live));
        bbMaxY = max(bbMaxY, mix(posY, e.y, live));
    }
    const float4 bbOut = float4(bbMinX, bbMinY, bbMaxX, bbMaxY);
    next.write(bbOut, uint2(14u, ti));
    present.write(bbOut, uint2(14u, ti));
    const float4 headOut = float4(posX, posY, frame, ((genStart + 1.0f)));
    const float4 metaOut = float4(missStreak, sumW, gen, crowdStreak);
    next.write(headOut, uint2(0u, ti));
    present.write(headOut, uint2(0u, ti));
    next.write(metaOut, uint2(1u, ti));
    present.write(metaOut, uint2(1u, ti));
}
} // namespace S_KeyFrames

using namespace S_KeyFrames;

fragment float4 KeyFrames_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 kft_0_res = uniforms._sys.logicalViewportSize;
    const float kft_0_sf = (kft_0_res.y / 1080.0f);
    const float2 kft_0_px = float2(((uv).x * kft_0_res.x), ((uv).y * kft_0_res.y));
    const float kft_0_aa = max(max(fwidth(kft_0_px.x), fwidth(kft_0_px.y)), 0.0001f);
    const float kft_0_lw = max((uniforms.n_x.lineWidth * kft_0_sf), 0.5f);
    const float kft_0_ms = max((uniforms.n_x.markerSize * kft_0_sf), 4.0f);
    float4 kft_0_dst = rtt_0.sample(linearClamp, (uv), level(0.0f));
    const uint kft_0_n = wgsl_f2u(clamp(uniforms.n_x.trackers, 1.0f, 64.0f));
    for (uint ti = 0u; (ti < kft_0_n); ti = (ti + 1u)) {
        const float4 head = compute_0.read(uint2(0u, ti), 0);
        if (((head.w < 0.5f))) {
            continue;
        }
        const float4 bb = compute_0.read(uint2(14u, ti), 0);
        const float pad = ((kft_0_ms + (kft_0_lw * 4.0f)) + (kft_0_aa * 2.0f));
        const float2 bbMin = (float2((bb.x * kft_0_res.x), (bb.y * kft_0_res.y)) - float2(pad));
        const float2 bbMax = (float2((bb.z * kft_0_res.x), (bb.w * kft_0_res.y)) + float2(pad));
        if (((all((kft_0_px >= bbMin)) && all((kft_0_px <= bbMax))))) {
            const float4 mta = compute_0.read(uint2(1u, ti), 0);
            const float2 tp = float2((head.x * kft_0_res.x), (head.y * kft_0_res.y));
            const float searching = select(1.0f, 0.45f, (mta.x > 4.0f));
            if (((uniforms.n_x.trail > 0.001f))) {
                float4 ePrev = compute_0.read(uint2(13u, ti), 0);
                for (uint j = 0u; (j < 12u); j = (j + 1u)) {
                    const float4 e = compute_0.read(uint2((2u + j), ti), 0);
                    const float valid = (select(0.0f, 1.0f, (abs((e.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (e.z > 0.5f)));
                    const float age = (head.z - e.z);
                    const float fade = (clamp((1.0f - (age / 96.0f)), 0.0f, 1.0f) * valid);
                    const float2 ep = float2((e.x * kft_0_res.x), (e.y * kft_0_res.y));
                    const float2 dp = (kft_0_px - ep);
                    const float dsz = (kft_0_ms * 0.16f);
                    const float dSd = ((((abs(dp.x) + abs(dp.y))) * 0.7071f) - dsz);
                    {
                        const float av = clamp((((((1.0f - smoothstep(0.0f, kft_0_aa, dSd))) * uniforms.n_x.keyframeColor.a) * fade) * uniforms.n_x.trail), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.keyframeColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    const float validP = (select(0.0f, 1.0f, (abs((ePrev.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (ePrev.z > 0.5f)));
                    const float stampGap = abs((e.z - ePrev.z));
                    const float contiguous = select(0.0f, 1.0f, (stampGap < 12.0f));
                    const float2 epp = float2((ePrev.x * kft_0_res.x), (ePrev.y * kft_0_res.y));
                    const float2 pa = (kft_0_px - epp);
                    const float2 ba = (ep - epp);
                    const float h = clamp((dot(pa, ba) / max(dot(ba, ba), 0.0001f)), 0.0f, 1.0f);
                    const float segD = length((pa - (ba * h)));
                    {
                        const float av = clamp(((((((((1.0f - smoothstep((kft_0_lw * 0.4f), ((kft_0_lw * 0.4f) + kft_0_aa), segD))) * uniforms.n_x.pathColor.a) * fade) * validP) * contiguous) * uniforms.n_x.trail) * 0.8f), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.pathColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    ePrev = e;
                }
            }
            const float2 gp = (kft_0_px - tp);
            const float hlf = (kft_0_ms * 0.5f);
            const float2 q = (abs(gp) - float2(hlf));
            const float boxSd = (length(max(q, float2(0.0f))) + min(max(q.x, q.y), 0.0f));
            float strokeA = (1.0f - smoothstep(0.0f, kft_0_aa, (abs(boxSd) - (kft_0_lw * 0.5f))));
            const float bl = (hlf * 0.45f);
            const bool inCorner = ((abs(gp.x) > (hlf - bl)) && (abs(gp.y) > (hlf - bl)));
            strokeA = (strokeA * select(0.0f, 1.0f, inCorner));
            {
                const float av = clamp(((strokeA * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            const float tick = (hlf * 0.55f);
            const float chH = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.y) - (kft_0_lw * 0.5f)), (abs(gp.x) - tick))));
            const float chV = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.x) - (kft_0_lw * 0.5f)), (abs(gp.y) - tick))));
            {
                const float av = clamp((((max(chH, chV) * 0.55f) * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            {
                const float av = clamp((((1.0f - smoothstep(kft_0_lw, (kft_0_lw + kft_0_aa), length(gp)))) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((float3(1.0f, 1.0f, 1.0f)) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
        }
    }
    float4 composed_1 = float4((kft_0_dst.rgb / max(kft_0_dst.a, 0.0001f)), kft_0_dst.a);
    return composed_1;
}

fragment float4 KeyFrames_v0_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 KeyFrames_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 kft_0_res = uniforms._sys.logicalViewportSize;
    const float kft_0_sf = (kft_0_res.y / 1080.0f);
    const float2 kft_0_px = float2(((uv).x * kft_0_res.x), ((uv).y * kft_0_res.y));
    const float kft_0_aa = max(max(fwidth(kft_0_px.x), fwidth(kft_0_px.y)), 0.0001f);
    const float kft_0_lw = max((uniforms.n_x.lineWidth * kft_0_sf), 0.5f);
    const float kft_0_ms = max((uniforms.n_x.markerSize * kft_0_sf), 4.0f);
    float4 kft_0_dst = rtt_0.sample(linearClamp, (uv), level(0.0f));
    const uint kft_0_n = wgsl_f2u(clamp(uniforms.n_x.trackers, 1.0f, 64.0f));
    for (uint ti = 0u; (ti < kft_0_n); ti = (ti + 1u)) {
        const float4 head = compute_0.read(uint2(0u, ti), 0);
        if (((head.w < 0.5f))) {
            continue;
        }
        const float4 bb = compute_0.read(uint2(14u, ti), 0);
        const float pad = ((kft_0_ms + (kft_0_lw * 4.0f)) + (kft_0_aa * 2.0f));
        const float2 bbMin = (float2((bb.x * kft_0_res.x), (bb.y * kft_0_res.y)) - float2(pad));
        const float2 bbMax = (float2((bb.z * kft_0_res.x), (bb.w * kft_0_res.y)) + float2(pad));
        if (((all((kft_0_px >= bbMin)) && all((kft_0_px <= bbMax))))) {
            const float4 mta = compute_0.read(uint2(1u, ti), 0);
            const float2 tp = float2((head.x * kft_0_res.x), (head.y * kft_0_res.y));
            const float searching = select(1.0f, 0.45f, (mta.x > 4.0f));
            if (((uniforms.n_x.trail > 0.001f))) {
                float4 ePrev = compute_0.read(uint2(13u, ti), 0);
                for (uint j = 0u; (j < 12u); j = (j + 1u)) {
                    const float4 e = compute_0.read(uint2((2u + j), ti), 0);
                    const float valid = (select(0.0f, 1.0f, (abs((e.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (e.z > 0.5f)));
                    const float age = (head.z - e.z);
                    const float fade = (clamp((1.0f - (age / 96.0f)), 0.0f, 1.0f) * valid);
                    const float2 ep = float2((e.x * kft_0_res.x), (e.y * kft_0_res.y));
                    const float2 dp = (kft_0_px - ep);
                    const float dsz = (kft_0_ms * 0.16f);
                    const float dSd = ((((abs(dp.x) + abs(dp.y))) * 0.7071f) - dsz);
                    {
                        const float av = clamp((((((1.0f - smoothstep(0.0f, kft_0_aa, dSd))) * uniforms.n_x.keyframeColor.a) * fade) * uniforms.n_x.trail), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.keyframeColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    const float validP = (select(0.0f, 1.0f, (abs((ePrev.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (ePrev.z > 0.5f)));
                    const float stampGap = abs((e.z - ePrev.z));
                    const float contiguous = select(0.0f, 1.0f, (stampGap < 12.0f));
                    const float2 epp = float2((ePrev.x * kft_0_res.x), (ePrev.y * kft_0_res.y));
                    const float2 pa = (kft_0_px - epp);
                    const float2 ba = (ep - epp);
                    const float h = clamp((dot(pa, ba) / max(dot(ba, ba), 0.0001f)), 0.0f, 1.0f);
                    const float segD = length((pa - (ba * h)));
                    {
                        const float av = clamp(((((((((1.0f - smoothstep((kft_0_lw * 0.4f), ((kft_0_lw * 0.4f) + kft_0_aa), segD))) * uniforms.n_x.pathColor.a) * fade) * validP) * contiguous) * uniforms.n_x.trail) * 0.8f), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.pathColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    ePrev = e;
                }
            }
            const float2 gp = (kft_0_px - tp);
            const float hlf = (kft_0_ms * 0.5f);
            const float2 q = (abs(gp) - float2(hlf));
            const float boxSd = (length(max(q, float2(0.0f))) + min(max(q.x, q.y), 0.0f));
            float strokeA = (1.0f - smoothstep(0.0f, kft_0_aa, (abs(boxSd) - (kft_0_lw * 0.5f))));
            const float bl = (hlf * 0.45f);
            const bool inCorner = ((abs(gp.x) > (hlf - bl)) && (abs(gp.y) > (hlf - bl)));
            strokeA = (strokeA * select(0.0f, 1.0f, inCorner));
            {
                const float av = clamp(((strokeA * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            const float tick = (hlf * 0.55f);
            const float chH = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.y) - (kft_0_lw * 0.5f)), (abs(gp.x) - tick))));
            const float chV = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.x) - (kft_0_lw * 0.5f)), (abs(gp.y) - tick))));
            {
                const float av = clamp((((max(chH, chV) * 0.55f) * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            {
                const float av = clamp((((1.0f - smoothstep(kft_0_lw, (kft_0_lw + kft_0_aa), length(gp)))) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((float3(1.0f, 1.0f, 1.0f)) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
        }
    }
    float4 composed_1 = float4((kft_0_dst.rgb / max(kft_0_dst.a, 0.0001f)), kft_0_dst.a);
    return composed_1;
}

fragment float4 KeyFrames_v1_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 KeyFrames_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 kft_0_res = uniforms._sys.logicalViewportSize;
    const float kft_0_sf = (kft_0_res.y / 1080.0f);
    const float2 kft_0_px = float2(((uv).x * kft_0_res.x), ((uv).y * kft_0_res.y));
    const float kft_0_aa = max(max(fwidth(kft_0_px.x), fwidth(kft_0_px.y)), 0.0001f);
    const float kft_0_lw = max((uniforms.n_x.lineWidth * kft_0_sf), 0.5f);
    const float kft_0_ms = max((uniforms.n_x.markerSize * kft_0_sf), 4.0f);
    float4 kft_0_dst = rtt_0.sample(linearClamp, (uv), level(0.0f));
    const uint kft_0_n = wgsl_f2u(clamp(uniforms.n_x.trackers, 1.0f, 64.0f));
    for (uint ti = 0u; (ti < kft_0_n); ti = (ti + 1u)) {
        const float4 head = compute_0.read(uint2(0u, ti), 0);
        if (((head.w < 0.5f))) {
            continue;
        }
        const float4 bb = compute_0.read(uint2(14u, ti), 0);
        const float pad = ((kft_0_ms + (kft_0_lw * 4.0f)) + (kft_0_aa * 2.0f));
        const float2 bbMin = (float2((bb.x * kft_0_res.x), (bb.y * kft_0_res.y)) - float2(pad));
        const float2 bbMax = (float2((bb.z * kft_0_res.x), (bb.w * kft_0_res.y)) + float2(pad));
        if (((all((kft_0_px >= bbMin)) && all((kft_0_px <= bbMax))))) {
            const float4 mta = compute_0.read(uint2(1u, ti), 0);
            const float2 tp = float2((head.x * kft_0_res.x), (head.y * kft_0_res.y));
            const float searching = select(1.0f, 0.45f, (mta.x > 4.0f));
            if (((uniforms.n_x.trail > 0.001f))) {
                float4 ePrev = compute_0.read(uint2(13u, ti), 0);
                for (uint j = 0u; (j < 12u); j = (j + 1u)) {
                    const float4 e = compute_0.read(uint2((2u + j), ti), 0);
                    const float valid = (select(0.0f, 1.0f, (abs((e.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (e.z > 0.5f)));
                    const float age = (head.z - e.z);
                    const float fade = (clamp((1.0f - (age / 96.0f)), 0.0f, 1.0f) * valid);
                    const float2 ep = float2((e.x * kft_0_res.x), (e.y * kft_0_res.y));
                    const float2 dp = (kft_0_px - ep);
                    const float dsz = (kft_0_ms * 0.16f);
                    const float dSd = ((((abs(dp.x) + abs(dp.y))) * 0.7071f) - dsz);
                    {
                        const float av = clamp((((((1.0f - smoothstep(0.0f, kft_0_aa, dSd))) * uniforms.n_x.keyframeColor.a) * fade) * uniforms.n_x.trail), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.keyframeColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    const float validP = (select(0.0f, 1.0f, (abs((ePrev.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (ePrev.z > 0.5f)));
                    const float stampGap = abs((e.z - ePrev.z));
                    const float contiguous = select(0.0f, 1.0f, (stampGap < 12.0f));
                    const float2 epp = float2((ePrev.x * kft_0_res.x), (ePrev.y * kft_0_res.y));
                    const float2 pa = (kft_0_px - epp);
                    const float2 ba = (ep - epp);
                    const float h = clamp((dot(pa, ba) / max(dot(ba, ba), 0.0001f)), 0.0f, 1.0f);
                    const float segD = length((pa - (ba * h)));
                    {
                        const float av = clamp(((((((((1.0f - smoothstep((kft_0_lw * 0.4f), ((kft_0_lw * 0.4f) + kft_0_aa), segD))) * uniforms.n_x.pathColor.a) * fade) * validP) * contiguous) * uniforms.n_x.trail) * 0.8f), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.pathColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    ePrev = e;
                }
            }
            const float2 gp = (kft_0_px - tp);
            const float hlf = (kft_0_ms * 0.5f);
            const float2 q = (abs(gp) - float2(hlf));
            const float boxSd = (length(max(q, float2(0.0f))) + min(max(q.x, q.y), 0.0f));
            float strokeA = (1.0f - smoothstep(0.0f, kft_0_aa, (abs(boxSd) - (kft_0_lw * 0.5f))));
            const float bl = (hlf * 0.45f);
            const bool inCorner = ((abs(gp.x) > (hlf - bl)) && (abs(gp.y) > (hlf - bl)));
            strokeA = (strokeA * select(0.0f, 1.0f, inCorner));
            {
                const float av = clamp(((strokeA * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            const float tick = (hlf * 0.55f);
            const float chH = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.y) - (kft_0_lw * 0.5f)), (abs(gp.x) - tick))));
            const float chV = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.x) - (kft_0_lw * 0.5f)), (abs(gp.y) - tick))));
            {
                const float av = clamp((((max(chH, chV) * 0.55f) * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            {
                const float av = clamp((((1.0f - smoothstep(kft_0_lw, (kft_0_lw + kft_0_aa), length(gp)))) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((float3(1.0f, 1.0f, 1.0f)) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
        }
    }
    float4 composed_1 = float4((kft_0_dst.rgb / max(kft_0_dst.a, 0.0001f)), kft_0_dst.a);
    return composed_1;
}

fragment float4 KeyFrames_v2_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 KeyFrames_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 kft_0_res = uniforms._sys.logicalViewportSize;
    const float kft_0_sf = (kft_0_res.y / 1080.0f);
    const float2 kft_0_px = float2(((uv).x * kft_0_res.x), ((uv).y * kft_0_res.y));
    const float kft_0_aa = max(max(fwidth(kft_0_px.x), fwidth(kft_0_px.y)), 0.0001f);
    const float kft_0_lw = max((uniforms.n_x.lineWidth * kft_0_sf), 0.5f);
    const float kft_0_ms = max((uniforms.n_x.markerSize * kft_0_sf), 4.0f);
    float4 kft_0_dst = rtt_0.sample(linearClamp, (uv), level(0.0f));
    const uint kft_0_n = wgsl_f2u(clamp(uniforms.n_x.trackers, 1.0f, 64.0f));
    for (uint ti = 0u; (ti < kft_0_n); ti = (ti + 1u)) {
        const float4 head = compute_0.read(uint2(0u, ti), 0);
        if (((head.w < 0.5f))) {
            continue;
        }
        const float4 bb = compute_0.read(uint2(14u, ti), 0);
        const float pad = ((kft_0_ms + (kft_0_lw * 4.0f)) + (kft_0_aa * 2.0f));
        const float2 bbMin = (float2((bb.x * kft_0_res.x), (bb.y * kft_0_res.y)) - float2(pad));
        const float2 bbMax = (float2((bb.z * kft_0_res.x), (bb.w * kft_0_res.y)) + float2(pad));
        if (((all((kft_0_px >= bbMin)) && all((kft_0_px <= bbMax))))) {
            const float4 mta = compute_0.read(uint2(1u, ti), 0);
            const float2 tp = float2((head.x * kft_0_res.x), (head.y * kft_0_res.y));
            const float searching = select(1.0f, 0.45f, (mta.x > 4.0f));
            if (((uniforms.n_x.trail > 0.001f))) {
                float4 ePrev = compute_0.read(uint2(13u, ti), 0);
                for (uint j = 0u; (j < 12u); j = (j + 1u)) {
                    const float4 e = compute_0.read(uint2((2u + j), ti), 0);
                    const float valid = (select(0.0f, 1.0f, (abs((e.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (e.z > 0.5f)));
                    const float age = (head.z - e.z);
                    const float fade = (clamp((1.0f - (age / 96.0f)), 0.0f, 1.0f) * valid);
                    const float2 ep = float2((e.x * kft_0_res.x), (e.y * kft_0_res.y));
                    const float2 dp = (kft_0_px - ep);
                    const float dsz = (kft_0_ms * 0.16f);
                    const float dSd = ((((abs(dp.x) + abs(dp.y))) * 0.7071f) - dsz);
                    {
                        const float av = clamp((((((1.0f - smoothstep(0.0f, kft_0_aa, dSd))) * uniforms.n_x.keyframeColor.a) * fade) * uniforms.n_x.trail), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.keyframeColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    const float validP = (select(0.0f, 1.0f, (abs((ePrev.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (ePrev.z > 0.5f)));
                    const float stampGap = abs((e.z - ePrev.z));
                    const float contiguous = select(0.0f, 1.0f, (stampGap < 12.0f));
                    const float2 epp = float2((ePrev.x * kft_0_res.x), (ePrev.y * kft_0_res.y));
                    const float2 pa = (kft_0_px - epp);
                    const float2 ba = (ep - epp);
                    const float h = clamp((dot(pa, ba) / max(dot(ba, ba), 0.0001f)), 0.0f, 1.0f);
                    const float segD = length((pa - (ba * h)));
                    {
                        const float av = clamp(((((((((1.0f - smoothstep((kft_0_lw * 0.4f), ((kft_0_lw * 0.4f) + kft_0_aa), segD))) * uniforms.n_x.pathColor.a) * fade) * validP) * contiguous) * uniforms.n_x.trail) * 0.8f), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.pathColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    ePrev = e;
                }
            }
            const float2 gp = (kft_0_px - tp);
            const float hlf = (kft_0_ms * 0.5f);
            const float2 q = (abs(gp) - float2(hlf));
            const float boxSd = (length(max(q, float2(0.0f))) + min(max(q.x, q.y), 0.0f));
            float strokeA = (1.0f - smoothstep(0.0f, kft_0_aa, (abs(boxSd) - (kft_0_lw * 0.5f))));
            const float bl = (hlf * 0.45f);
            const bool inCorner = ((abs(gp.x) > (hlf - bl)) && (abs(gp.y) > (hlf - bl)));
            strokeA = (strokeA * select(0.0f, 1.0f, inCorner));
            {
                const float av = clamp(((strokeA * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            const float tick = (hlf * 0.55f);
            const float chH = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.y) - (kft_0_lw * 0.5f)), (abs(gp.x) - tick))));
            const float chV = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.x) - (kft_0_lw * 0.5f)), (abs(gp.y) - tick))));
            {
                const float av = clamp((((max(chH, chV) * 0.55f) * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            {
                const float av = clamp((((1.0f - smoothstep(kft_0_lw, (kft_0_lw + kft_0_aa), length(gp)))) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((float3(1.0f, 1.0f, 1.0f)) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
        }
    }
    float4 composed_1 = float4((kft_0_dst.rgb / max(kft_0_dst.a, 0.0001f)), kft_0_dst.a);
    return composed_1;
}

fragment float4 KeyFrames_v3_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 KeyFrames_v4_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 kft_0_res = uniforms._sys.logicalViewportSize;
    const float kft_0_sf = (kft_0_res.y / 1080.0f);
    const float2 kft_0_px = float2(((uv).x * kft_0_res.x), ((uv).y * kft_0_res.y));
    const float kft_0_aa = max(max(fwidth(kft_0_px.x), fwidth(kft_0_px.y)), 0.0001f);
    const float kft_0_lw = max((uniforms.n_x.lineWidth * kft_0_sf), 0.5f);
    const float kft_0_ms = max((uniforms.n_x.markerSize * kft_0_sf), 4.0f);
    float4 kft_0_dst = rtt_0.sample(linearClamp, (uv), level(0.0f));
    const uint kft_0_n = wgsl_f2u(clamp(uniforms.n_x.trackers, 1.0f, 64.0f));
    for (uint ti = 0u; (ti < kft_0_n); ti = (ti + 1u)) {
        const float4 head = compute_0.read(uint2(0u, ti), 0);
        if (((head.w < 0.5f))) {
            continue;
        }
        const float4 bb = compute_0.read(uint2(14u, ti), 0);
        const float pad = ((kft_0_ms + (kft_0_lw * 4.0f)) + (kft_0_aa * 2.0f));
        const float2 bbMin = (float2((bb.x * kft_0_res.x), (bb.y * kft_0_res.y)) - float2(pad));
        const float2 bbMax = (float2((bb.z * kft_0_res.x), (bb.w * kft_0_res.y)) + float2(pad));
        if (((all((kft_0_px >= bbMin)) && all((kft_0_px <= bbMax))))) {
            const float4 mta = compute_0.read(uint2(1u, ti), 0);
            const float2 tp = float2((head.x * kft_0_res.x), (head.y * kft_0_res.y));
            const float searching = select(1.0f, 0.45f, (mta.x > 4.0f));
            if (((uniforms.n_x.trail > 0.001f))) {
                float4 ePrev = compute_0.read(uint2(13u, ti), 0);
                for (uint j = 0u; (j < 12u); j = (j + 1u)) {
                    const float4 e = compute_0.read(uint2((2u + j), ti), 0);
                    const float valid = (select(0.0f, 1.0f, (abs((e.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (e.z > 0.5f)));
                    const float age = (head.z - e.z);
                    const float fade = (clamp((1.0f - (age / 96.0f)), 0.0f, 1.0f) * valid);
                    const float2 ep = float2((e.x * kft_0_res.x), (e.y * kft_0_res.y));
                    const float2 dp = (kft_0_px - ep);
                    const float dsz = (kft_0_ms * 0.16f);
                    const float dSd = ((((abs(dp.x) + abs(dp.y))) * 0.7071f) - dsz);
                    {
                        const float av = clamp((((((1.0f - smoothstep(0.0f, kft_0_aa, dSd))) * uniforms.n_x.keyframeColor.a) * fade) * uniforms.n_x.trail), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.keyframeColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    const float validP = (select(0.0f, 1.0f, (abs((ePrev.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (ePrev.z > 0.5f)));
                    const float stampGap = abs((e.z - ePrev.z));
                    const float contiguous = select(0.0f, 1.0f, (stampGap < 12.0f));
                    const float2 epp = float2((ePrev.x * kft_0_res.x), (ePrev.y * kft_0_res.y));
                    const float2 pa = (kft_0_px - epp);
                    const float2 ba = (ep - epp);
                    const float h = clamp((dot(pa, ba) / max(dot(ba, ba), 0.0001f)), 0.0f, 1.0f);
                    const float segD = length((pa - (ba * h)));
                    {
                        const float av = clamp(((((((((1.0f - smoothstep((kft_0_lw * 0.4f), ((kft_0_lw * 0.4f) + kft_0_aa), segD))) * uniforms.n_x.pathColor.a) * fade) * validP) * contiguous) * uniforms.n_x.trail) * 0.8f), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.pathColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    ePrev = e;
                }
            }
            const float2 gp = (kft_0_px - tp);
            const float hlf = (kft_0_ms * 0.5f);
            const float2 q = (abs(gp) - float2(hlf));
            const float boxSd = (length(max(q, float2(0.0f))) + min(max(q.x, q.y), 0.0f));
            float strokeA = (1.0f - smoothstep(0.0f, kft_0_aa, (abs(boxSd) - (kft_0_lw * 0.5f))));
            const float bl = (hlf * 0.45f);
            const bool inCorner = ((abs(gp.x) > (hlf - bl)) && (abs(gp.y) > (hlf - bl)));
            strokeA = (strokeA * select(0.0f, 1.0f, inCorner));
            {
                const float av = clamp(((strokeA * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            const float tick = (hlf * 0.55f);
            const float chH = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.y) - (kft_0_lw * 0.5f)), (abs(gp.x) - tick))));
            const float chV = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.x) - (kft_0_lw * 0.5f)), (abs(gp.y) - tick))));
            {
                const float av = clamp((((max(chH, chV) * 0.55f) * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            {
                const float av = clamp((((1.0f - smoothstep(kft_0_lw, (kft_0_lw + kft_0_aa), length(gp)))) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((float3(1.0f, 1.0f, 1.0f)) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
        }
    }
    float4 composed_1 = float4((kft_0_dst.rgb / max(kft_0_dst.a, 0.0001f)), kft_0_dst.a);
    return composed_1;
}

fragment float4 KeyFrames_v4_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 KeyFrames_v5_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 kft_0_res = uniforms._sys.logicalViewportSize;
    const float kft_0_sf = (kft_0_res.y / 1080.0f);
    const float2 kft_0_px = float2(((uv).x * kft_0_res.x), ((uv).y * kft_0_res.y));
    const float kft_0_aa = max(max(fwidth(kft_0_px.x), fwidth(kft_0_px.y)), 0.0001f);
    const float kft_0_lw = max((uniforms.n_x.lineWidth * kft_0_sf), 0.5f);
    const float kft_0_ms = max((uniforms.n_x.markerSize * kft_0_sf), 4.0f);
    float4 kft_0_dst = rtt_0.sample(linearClamp, (uv), level(0.0f));
    const uint kft_0_n = wgsl_f2u(clamp(uniforms.n_x.trackers, 1.0f, 64.0f));
    for (uint ti = 0u; (ti < kft_0_n); ti = (ti + 1u)) {
        const float4 head = compute_0.read(uint2(0u, ti), 0);
        if (((head.w < 0.5f))) {
            continue;
        }
        const float4 bb = compute_0.read(uint2(14u, ti), 0);
        const float pad = ((kft_0_ms + (kft_0_lw * 4.0f)) + (kft_0_aa * 2.0f));
        const float2 bbMin = (float2((bb.x * kft_0_res.x), (bb.y * kft_0_res.y)) - float2(pad));
        const float2 bbMax = (float2((bb.z * kft_0_res.x), (bb.w * kft_0_res.y)) + float2(pad));
        if (((all((kft_0_px >= bbMin)) && all((kft_0_px <= bbMax))))) {
            const float4 mta = compute_0.read(uint2(1u, ti), 0);
            const float2 tp = float2((head.x * kft_0_res.x), (head.y * kft_0_res.y));
            const float searching = select(1.0f, 0.45f, (mta.x > 4.0f));
            if (((uniforms.n_x.trail > 0.001f))) {
                float4 ePrev = compute_0.read(uint2(13u, ti), 0);
                for (uint j = 0u; (j < 12u); j = (j + 1u)) {
                    const float4 e = compute_0.read(uint2((2u + j), ti), 0);
                    const float valid = (select(0.0f, 1.0f, (abs((e.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (e.z > 0.5f)));
                    const float age = (head.z - e.z);
                    const float fade = (clamp((1.0f - (age / 96.0f)), 0.0f, 1.0f) * valid);
                    const float2 ep = float2((e.x * kft_0_res.x), (e.y * kft_0_res.y));
                    const float2 dp = (kft_0_px - ep);
                    const float dsz = (kft_0_ms * 0.16f);
                    const float dSd = ((((abs(dp.x) + abs(dp.y))) * 0.7071f) - dsz);
                    {
                        const float av = clamp((((((1.0f - smoothstep(0.0f, kft_0_aa, dSd))) * uniforms.n_x.keyframeColor.a) * fade) * uniforms.n_x.trail), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.keyframeColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    const float validP = (select(0.0f, 1.0f, (abs((ePrev.w - mta.z)) < 0.5f)) * select(0.0f, 1.0f, (ePrev.z > 0.5f)));
                    const float stampGap = abs((e.z - ePrev.z));
                    const float contiguous = select(0.0f, 1.0f, (stampGap < 12.0f));
                    const float2 epp = float2((ePrev.x * kft_0_res.x), (ePrev.y * kft_0_res.y));
                    const float2 pa = (kft_0_px - epp);
                    const float2 ba = (ep - epp);
                    const float h = clamp((dot(pa, ba) / max(dot(ba, ba), 0.0001f)), 0.0f, 1.0f);
                    const float segD = length((pa - (ba * h)));
                    {
                        const float av = clamp(((((((((1.0f - smoothstep((kft_0_lw * 0.4f), ((kft_0_lw * 0.4f) + kft_0_aa), segD))) * uniforms.n_x.pathColor.a) * fade) * validP) * contiguous) * uniforms.n_x.trail) * 0.8f), 0.0f, 1.0f);
                        kft_0_dst = float4((((uniforms.n_x.pathColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
                    }
                    ePrev = e;
                }
            }
            const float2 gp = (kft_0_px - tp);
            const float hlf = (kft_0_ms * 0.5f);
            const float2 q = (abs(gp) - float2(hlf));
            const float boxSd = (length(max(q, float2(0.0f))) + min(max(q.x, q.y), 0.0f));
            float strokeA = (1.0f - smoothstep(0.0f, kft_0_aa, (abs(boxSd) - (kft_0_lw * 0.5f))));
            const float bl = (hlf * 0.45f);
            const bool inCorner = ((abs(gp.x) > (hlf - bl)) && (abs(gp.y) > (hlf - bl)));
            strokeA = (strokeA * select(0.0f, 1.0f, inCorner));
            {
                const float av = clamp(((strokeA * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            const float tick = (hlf * 0.55f);
            const float chH = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.y) - (kft_0_lw * 0.5f)), (abs(gp.x) - tick))));
            const float chV = (1.0f - smoothstep(0.0f, kft_0_aa, max((abs(gp.x) - (kft_0_lw * 0.5f)), (abs(gp.y) - tick))));
            {
                const float av = clamp((((max(chH, chV) * 0.55f) * uniforms.n_x.markerColor.a) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((uniforms.n_x.markerColor.rgb) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
            {
                const float av = clamp((((1.0f - smoothstep(kft_0_lw, (kft_0_lw + kft_0_aa), length(gp)))) * searching), 0.0f, 1.0f);
                kft_0_dst = float4((((float3(1.0f, 1.0f, 1.0f)) * av) + (kft_0_dst.rgb * ((1.0f - av)))), (av + (kft_0_dst.a * ((1.0f - av)))));
            }
        }
    }
    float4 composed_1 = float4((kft_0_dst.rgb / max(kft_0_dst.a, 0.0001f)), kft_0_dst.a);
    return composed_1;
}

fragment float4 KeyFrames_v5_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

static void KeyFrames_k0_body(uint gx, uint gy, uint _arg_2, texture2d<float, access::write> grid, texture2d<float> src) {
    featureGridScan(gx, gy, grid, src);
}

kernel void KeyFrames_k0(uint3 sk_gid [[thread_position_in_grid]], texture2d<float> src [[texture(0)]], texture2d<float, access::write> grid [[texture(1)]], constant uint3& sk_size [[buffer(0)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    KeyFrames_k0_body(sk_gid.x, sk_gid.y, sk_gid.z, grid, src);
}

static void KeyFrames_k1_body(uint ti, uint _arg_1, uint _arg_2, texture2d<float> featGrid, texture2d<float, access::write> next, constant TrackParams& params, texture2d<float, access::write> present, texture2d<float> prev, texture2d<float> src) {
    trackerPursuit(ti, featGrid, next, params, present, prev, src);
}

kernel void KeyFrames_k1(uint3 sk_gid [[thread_position_in_grid]], texture2d<float> src [[texture(0)]], texture2d<float> featGrid [[texture(1)]], texture2d<float> prev [[texture(2)]], texture2d<float, access::write> next [[texture(3)]], texture2d<float, access::write> present [[texture(4)]], constant TrackParams& params [[buffer(0)]], constant uint3& sk_size [[buffer(1)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    KeyFrames_k1_body(sk_gid.x, sk_gid.y, sk_gid.z, featGrid, next, params, present, prev, src);
}
