// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: PagePeel
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_PagePeel {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct PagePeelGeom {
    float2 curlUV;
    float theta;
    float distPastCrease;
    float distIntoPeel;
    float flatReach;
    float peelReach;
    float foldBlend;
    float showCurl;
};

struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct padded_1 {
    float amount;
    float radius;
    float shading;
    float highlight;
    float highlightSoftness;
    float shadow;
    float _opacity;
    float _pad0;
};

struct struct_1 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    padded_1 n_x;
    padded n_child;
    struct_1 _sys;
};

static PagePeelGeom pagePeelGeom(float2 uv, float aspect, float cornerX, float cornerY, float oppX, float oppY, float amount, float radius) {
    const float2 pA = float2(((uv.x * aspect)), uv.y);
    const float2 cornerA = float2(((cornerX * aspect)), cornerY);
    const float2 oppA = float2(((oppX * aspect)), oppY);
    const float2 axisVec = ((oppA - cornerA));
    const float L = length(axisVec);
    const float2 axis = ((axisVec * ((1.0f / L))));
    const float t = dot(((pA - cornerA)), axis);
    const float peel = ((amount * L));
    const float cFold = peel;
    const float R = max(((radius * L)), 1.0e-4f);
    const float thetaMax = ((peel / R));
    const float X = ((((t - cFold)) / R));
    const float Xc = clamp(X, 0.0f, 1.0f);
    const float theta = asin(Xc);
    const float inBand = ((step(0.0f, X) * step(X, 1.0f)));
    const float paper = step(theta, thetaMax);
    const float cCurl = ((peel - ((R * theta))));
    const float2 sourceA = ((pA + ((axis * ((cCurl - t))))));
    const float2 curlUV = float2(((sourceA.x / aspect)), sourceA.y);
    const float curlInBounds = ((((((step(0.0f, curlUV.x) * step(curlUV.x, 1.0f))) * step(0.0f, curlUV.y))) * step(curlUV.y, 1.0f)));
    const float liftFrac = ((1.0f - cos(clamp(thetaMax, 0.0f, 1.5707963267948966f))));
    const float lipHeight = ((R * liftFrac));
    const float flatReach = max(((R + ((lipHeight * 0.5f)))), 1.0e-4f);
    const float distPastCrease = ((t - cFold));
    const float peelReach = max(((lipHeight * 2.5f)), 1.0e-4f);
    const float distIntoPeel = ((cFold - t));
    const float foldBlend = smoothstep(((cFold - 0.0015f)), ((cFold + 0.0015f)), t);
    const float showCurl = ((((inBand * paper)) * curlInBounds));
    return PagePeelGeom{curlUV, theta, distPastCrease, distIntoPeel, flatReach, peelReach, foldBlend, showCurl};
}

static float4 unpremultiplyAlpha(float4 color2) {
    const float alpha = color2.w;
    const float3 straightRGB = select(float3(0), ((color2.xyz / alpha)), ((alpha > 1.0e-3f)));
    return float4(straightRGB, alpha);
}

static float4 pagePeelCompose(float4 curlSample, float4 flatSample, float curlBright, float spec, float flatShade, float peelAlpha, float foldBlend, float showCurl) {
    const float3 litRgb = ((((curlSample.xyz * curlBright)) + ((spec * curlSample.w))));
    const float4 curlColor = float4(litRgb, curlSample.w);
    const float4 flatColor = float4(((flatSample.xyz * flatShade)), flatSample.w);
    const float4 peeledColor = float4(0.0f, 0.0f, 0.0f, peelAlpha);
    const float4 base = mix(peeledColor, flatColor, float4(foldBlend));
    return select(base, curlColor, ((showCurl > 0.5f)));
}

static float curlShade(float theta, float shading) {
    const float facing = cos(theta);
    return ((1.0f - ((shading * facing))));
}

static float curlSheen(float theta, float intensity, float softness) {
    const float thetaN = ((theta / 1.5707963267948966f));
    const float specSigma = mix(0.05f, 0.4f, softness);
    const float specDelta = ((((thetaN - 0.65f)) / specSigma));
    return ((exp(((((specDelta * specDelta)) * (-0.5f)))) * intensity));
}

static float shadowFalloff(float dist, float reach, float exponent) {
    return ((pow(((1.0f - smoothstep(0.0f, reach, dist))), exponent) * step(0.0f, dist)));
}

static float liftShadowStrength(float amount) {
    return ((smoothstep(0.0f, 0.04f, amount) * pow(((1.0f - amount)), 0.7f)));
}

static float overhangShade(float dist, float reach, float amount, float shadow) {
    const float fall = ((shadowFalloff(dist, reach, 2.0f) * liftShadowStrength(amount)));
    return ((1.0f - ((((shadow * fall)) * 0.5f))));
}

static float revealShadow(float dist, float reach, float amount, float shadow) {
    const float fall = ((((shadowFalloff(dist, reach, 1.5f) * liftShadowStrength(amount))) * shadow));
    return ((fall * 0.6f));
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float4 overComposite(float4 base, float3 blended, float overlayAlpha) {
    const float baseWeight = ((base.w * ((1.0f - overlayAlpha))));
    const float finalAlpha = ((overlayAlpha + baseWeight));
    const float3 rgb = ((((blended * overlayAlpha)) + ((base.xyz * baseWeight))));
    return float4(rgb, finalAlpha);
}

static float4 blend_normal(float4 base, float4 overlay2, float opacity) {
    const float overlayAlpha = ((overlay2.w * opacity));
    return overComposite(base, overlay2.xyz, overlayAlpha);
}
} // namespace S_PagePeel

using namespace S_PagePeel;

fragment float4 PagePeel_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const PagePeelGeom peel_0 = pagePeelGeom(uv, uniforms._sys.aspect, 0.0f, 0.0f, 1.0f, 1.0f, uniforms.n_x.amount, uniforms.n_x.radius);
    float4 composed_1 = unpremultiplyAlpha(pagePeelCompose(rtt_0.sample(linearClamp, peel_0.curlUV), rtt_0.sample(linearClamp, uv), curlShade(peel_0.theta, uniforms.n_x.shading), curlSheen(peel_0.theta, uniforms.n_x.highlight, uniforms.n_x.highlightSoftness), overhangShade(peel_0.distPastCrease, peel_0.flatReach, uniforms.n_x.amount, uniforms.n_x.shadow), revealShadow(peel_0.distIntoPeel, peel_0.peelReach, uniforms.n_x.amount, uniforms.n_x.shadow), peel_0.foldBlend, peel_0.showCurl));
    return composed_1;
}

fragment float4 PagePeel_v0_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 PagePeel_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const PagePeelGeom peel_0 = pagePeelGeom(uv, uniforms._sys.aspect, 1.0f, 0.0f, 0.0f, 1.0f, uniforms.n_x.amount, uniforms.n_x.radius);
    float4 composed_1 = unpremultiplyAlpha(pagePeelCompose(rtt_0.sample(linearClamp, peel_0.curlUV), rtt_0.sample(linearClamp, uv), curlShade(peel_0.theta, uniforms.n_x.shading), curlSheen(peel_0.theta, uniforms.n_x.highlight, uniforms.n_x.highlightSoftness), overhangShade(peel_0.distPastCrease, peel_0.flatReach, uniforms.n_x.amount, uniforms.n_x.shadow), revealShadow(peel_0.distIntoPeel, peel_0.peelReach, uniforms.n_x.amount, uniforms.n_x.shadow), peel_0.foldBlend, peel_0.showCurl));
    return composed_1;
}

fragment float4 PagePeel_v1_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 PagePeel_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const PagePeelGeom peel_0 = pagePeelGeom(uv, uniforms._sys.aspect, 0.0f, 1.0f, 1.0f, 0.0f, uniforms.n_x.amount, uniforms.n_x.radius);
    float4 composed_1 = unpremultiplyAlpha(pagePeelCompose(rtt_0.sample(linearClamp, peel_0.curlUV), rtt_0.sample(linearClamp, uv), curlShade(peel_0.theta, uniforms.n_x.shading), curlSheen(peel_0.theta, uniforms.n_x.highlight, uniforms.n_x.highlightSoftness), overhangShade(peel_0.distPastCrease, peel_0.flatReach, uniforms.n_x.amount, uniforms.n_x.shadow), revealShadow(peel_0.distIntoPeel, peel_0.peelReach, uniforms.n_x.amount, uniforms.n_x.shadow), peel_0.foldBlend, peel_0.showCurl));
    return composed_1;
}

fragment float4 PagePeel_v2_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}

fragment float4 PagePeel_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> rtt_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const PagePeelGeom peel_0 = pagePeelGeom(uv, uniforms._sys.aspect, 1.0f, 1.0f, 0.0f, 0.0f, uniforms.n_x.amount, uniforms.n_x.radius);
    float4 composed_1 = unpremultiplyAlpha(pagePeelCompose(rtt_0.sample(linearClamp, peel_0.curlUV), rtt_0.sample(linearClamp, uv), curlShade(peel_0.theta, uniforms.n_x.shading), curlSheen(peel_0.theta, uniforms.n_x.highlight, uniforms.n_x.highlightSoftness), overhangShade(peel_0.distPastCrease, peel_0.flatReach, uniforms.n_x.amount, uniforms.n_x.shadow), revealShadow(peel_0.distIntoPeel, peel_0.peelReach, uniforms.n_x.amount, uniforms.n_x.shadow), peel_0.foldBlend, peel_0.showCurl));
    return composed_1;
}

fragment float4 PagePeel_v3_rtt_0(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    return blend_normal(float4(1.0f, 1.0f, 1.0f, 0.0f), media_0.sample(linearClamp, uv), uniforms.n_child._opacity);
}
