// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: SineWave
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_SineWave {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float4 color;
    float amplitude;
    float frequency;
    float speed;
    float angle;
    float2 position;
    float thickness;
    float softness;
    float _opacity;
    float _animTime;
    char _sk_pad0[8];
};

struct struct_2 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    struct_1 n_x;
    struct_2 _sys;
};

static float2 aspectCenteredDelta(float2 uv, float2 center, float2 viewport) {
    const float aspect = ((viewport.x / max(viewport.y, 1.0e-6f)));
    return float2(((((uv.x * aspect)) - ((center.x * aspect)))), ((uv.y - ((1.0f - center.y)))));
}

static float2 rotate2(float2 p, float cosA, float sinA) {
    return float2(((((p.x * cosA)) - ((p.y * sinA)))), ((((p.x * sinA)) + ((p.y * cosA)))));
}

static float sineWaveMask(float2 uv, float2 viewport, float angle, float2 position, float frequency, float amplitude, float thickness, float softness, float animTime) {
    const float2 centered = aspectCenteredDelta(uv, position, viewport);
    const float angleRad = ((angle * 0.017453292519943295f));
    const float cosAngle = cos(angleRad);
    const float sinAngle = sin(angleRad);
    const float2 rotated = rotate2(centered, cosAngle, sinAngle);
    const float waveInput = ((((((rotated.x * frequency)) * 6.283185307179586f)) + animTime));
    const float sineWave = ((sin(waveInput) * amplitude));
    const float distanceFromWave = abs(((rotated.y - sineWave)));
    const float halfThickness = ((thickness * 0.5f));
    const float halfSoftness = ((softness * 0.5f));
    return ((1.0f - smoothstep(((halfThickness - halfSoftness)), ((halfThickness + halfSoftness)), distanceFromWave)));
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}
} // namespace S_SineWave

using namespace S_SineWave;

fragment float4 SineWave_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4(uniforms.n_x.color.rgb, ((uniforms.n_x.color.a * sineWaveMask(uv, uniforms._sys.viewportSize, uniforms.n_x.angle, uniforms.n_x.position, uniforms.n_x.frequency, uniforms.n_x.amplitude, uniforms.n_x.thickness, uniforms.n_x.softness, uniforms.n_x._animTime))));
    return composed_0;
}
