// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: Smoke
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_Smoke {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float4 colorA;
    float4 colorB;
    metal::array<float4, 8> colorsArray;
    metal::array<float4, 2> positionsArray;
    metal::array<float3, 8> convertedColorsArray;
    float stopCount;
    float2 emitFrom;
    float direction;
    float speed;
    float spread;
    float emitRadius;
    float intensity;
    float dissipation;
    float detail;
    float gravity;
    float colorDecay;
    float mouseInfluence;
    float mouseRadius;
    float colorSpace;
    float _opacity;
    char _sk_pad0[12];
};

struct struct_2 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    struct_1 n_x;
    struct_2 _sys;
};

struct MixStep {
    float3 conv;
    float alpha;
};

struct FluidParams {
    float dt;
    float emitX;
    float emitY;
    float emitVelX;
    float emitVelY;
    float perpDirX;
    float perpDirY;
    float spreadFactor;
    float emitRad;
    float emitIntensity;
    float dyeFade;
    float velFade;
    float curlStrength;
    float gravity;
    float cursorX;
    float cursorY;
    float cursorVelX;
    float cursorVelY;
    float mouseActive;
    float mouseRadSq;
    float colorDecay;
    char _sk_pad0[12];
};

static float3 awMix(float3 a, float3 b, float wA, float wB, float sw) {
    return ((((((a * wA)) + ((b * wB)))) / sw));
}

static float4 mixColors(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 rgb = awMix(colorA.xyz, colorB.xyz, weightA, weightB, safeWeight);
    return float4(rgb, totalWeight);
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float3 p3ToSRGB(float3 p3) {
    const float r = ((((((p3.x * 1.2249401f)) - ((p3.y * 0.2249404f)))) - ((p3.z * 0.0f))));
    const float g = ((((((p3.x * (-0.0420569f))) + ((p3.y * 1.0420571f)))) + ((p3.z * 0.0f))));
    const float b = ((((((p3.x * (-0.0196376f))) - ((p3.y * 0.0786361f)))) + ((p3.z * 1.0982735f))));
    return float3(r, g, b);
}

static float3 rgbToOklab(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float l = ((((((r * 0.4122214708f)) + ((g * 0.5363325363f)))) + ((b * 0.0514459929f))));
    const float m = ((((r * 0.2119034982f)) + ((((g * 0.6806995451f)) + ((b * 0.1073969566f))))));
    const float s = ((((((r * 0.0883024619f)) + ((g * 0.2817188376f)))) + ((b * 0.6299787005f))));
    const float l_ = ((sign(l) * pow(abs(l), 0.3333333333333333f)));
    const float m_ = ((sign(m) * pow(abs(m), 0.3333333333333333f)));
    const float s_ = ((sign(s) * pow(abs(s), 0.3333333333333333f)));
    return float3(((((((l_ * 0.2104542553f)) + ((m_ * 0.793617785f)))) - ((s_ * 0.0040720468f)))), ((((((l_ * 1.9779984951f)) - ((m_ * 2.428592205f)))) + ((s_ * 0.4505937099f)))), ((((((l_ * 0.0259040371f)) + ((m_ * 0.7827717662f)))) - ((s_ * 0.808675766f)))));
}

static float3 oklabToOklch(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float C = sqrt(((((a * a)) + ((b * b)))));
    const float h = atan2(b, a);
    return float3(L, C, h);
}

static float3 oklchToOklab(float3 lch) {
    const float L = lch.x;
    const float C = lch.y;
    const float h = lch.z;
    return float3(L, ((C * cos(h))), ((C * sin(h))));
}

static float3 oklabToRgb(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float l_ = ((((L + ((a * 0.3963377774f)))) + ((b * 0.2158037573f))));
    const float m_ = ((((L - ((a * 0.1055613458f)))) - ((b * 0.0638541728f))));
    const float s_ = ((((L - ((a * 0.0894841775f)))) - ((b * 1.291485548f))));
    const float l = pow(l_, 3.0f);
    const float m = pow(m_, 3.0f);
    const float s = pow(s_, 3.0f);
    return float3(((((((l * 4.0767416621f)) - ((m * 3.3077115913f)))) + ((s * 0.2309699292f)))), ((((((l * (-1.2684380046f))) + ((m * 2.6097574011f)))) - ((s * 0.3413193965f)))), ((((((l * (-0.0041960863f))) - ((m * 0.7034186147f)))) + ((s * 1.707614701f)))));
}

static float3 sRGBToP3(float3 srgb) {
    const float r = ((((((srgb.x * 0.8224621f)) + ((srgb.y * 0.177538f)))) + ((srgb.z * 0.0f))));
    const float g = ((((((srgb.x * 0.0331941f)) + ((srgb.y * 0.9668058f)))) + ((srgb.z * 0.0f))));
    const float b = ((((((srgb.x * 0.0170826f)) + ((srgb.y * 0.0723974f)))) + ((srgb.z * 0.9105199f))));
    return float3(r, g, b);
}

static float4 mixColors_2(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 oklchA = oklabToOklch(rgbToOklab(p3ToSRGB(colorA.xyz)));
    const float3 oklchB = oklabToOklch(rgbToOklab(p3ToSRGB(colorB.xyz)));
    const float3 mixed = awMix(oklchA, oklchB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(oklabToRgb(oklchToOklab(mixed)));
    return float4(rgb, totalWeight);
}

static float4 mixColors_3(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 oklabA = rgbToOklab(p3ToSRGB(colorA.xyz));
    const float3 oklabB = rgbToOklab(p3ToSRGB(colorB.xyz));
    const float3 mixed = awMix(oklabA, oklabB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(oklabToRgb(mixed));
    return float4(rgb, totalWeight);
}

static float3 rgbToHsl(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float maxVal = max(max(r, g), b);
    const float minVal = min(min(r, g), b);
    const float delta = ((maxVal - minVal));
    const float l = ((((maxVal + minVal)) * 0.5f));
    const float satDenom = max(((1.0f - abs(((((l * 2.0f)) - 1.0f))))), 1.0e-4f);
    const float s = ((delta / satDenom));
    const bool isRMax = ((maxVal == r));
    const bool isGMax = ((maxVal == g));
    const float hueR = ((((g - b)) / max(delta, 1.0e-4f)));
    const float hueG = ((2.0f + ((((b - r)) / max(delta, 1.0e-4f)))));
    const float hueB = ((4.0f + ((((r - g)) / max(delta, 1.0e-4f)))));
    const float hue = select(select(hueB, hueG, isGMax), hueR, isRMax);
    const float h = ((hue * 1.0471975512f));
    return float3(h, s, l);
}

static float3 selectRGBBySector(float c, float x, float sector) {
    float r = 0.0f;
    float g = 0.0f;
    float b = 0.0f;
    if ((((sector < 1.0f)))) {
        r = c;
        g = x;
    } else {
        if ((((sector < 2.0f)))) {
            r = x;
            g = c;
        } else {
            if ((((sector < 3.0f)))) {
                g = c;
                b = x;
            } else {
                if ((((sector < 4.0f)))) {
                    g = x;
                    b = c;
                } else {
                    if ((((sector < 5.0f)))) {
                        r = x;
                        b = c;
                    } else {
                        r = c;
                        b = x;
                    }
                }
            }
        }
    }
    return float3(r, g, b);
}

static float3 hslToRgb(float3 hsl) {
    const float h = hsl.x;
    const float s = hsl.y;
    const float l = hsl.z;
    const float c = ((s * ((1.0f - abs(((((l * 2.0f)) - 1.0f)))))));
    const float hPrime = ((h / 1.0471975512f));
    const float x = ((c * ((1.0f - abs((((fmod(hPrime, 2.0f)) - 1.0f)))))));
    const float m = ((l - ((c * 0.5f))));
    const float sector = floor(hPrime);
    return ((selectRGBBySector(c, x, sector) + m));
}

static float4 mixColors_4(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 hslA = rgbToHsl(p3ToSRGB(colorA.xyz));
    const float3 hslB = rgbToHsl(p3ToSRGB(colorB.xyz));
    const float3 mixed = awMix(hslA, hslB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(hslToRgb(mixed));
    return float4(rgb, totalWeight);
}

static float3 rgbToHsv(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float maxVal = max(max(r, g), b);
    const float minVal = min(min(r, g), b);
    const float delta = ((maxVal - minVal));
    const float v = maxVal;
    const float s = ((delta / max(maxVal, 1.0e-4f)));
    const bool isRMax = ((maxVal == r));
    const bool isGMax = ((maxVal == g));
    const float hueR = ((((g - b)) / max(delta, 1.0e-4f)));
    const float hueG = ((2.0f + ((((b - r)) / max(delta, 1.0e-4f)))));
    const float hueB = ((4.0f + ((((r - g)) / max(delta, 1.0e-4f)))));
    const float hue = select(select(hueB, hueG, isGMax), hueR, isRMax);
    const float h = ((hue * 1.0471975512f));
    return float3(h, s, v);
}

static float3 hsvToRgb(float3 hsv) {
    const float h = hsv.x;
    const float s = hsv.y;
    const float v = hsv.z;
    const float c = ((v * s));
    const float hPrime = ((h / 1.0471975512f));
    const float x = ((c * ((1.0f - abs((((fmod(hPrime, 2.0f)) - 1.0f)))))));
    const float m = ((v - c));
    const float sector = floor(hPrime);
    return ((selectRGBBySector(c, x, sector) + m));
}

static float4 mixColors_5(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 hsvA = rgbToHsv(p3ToSRGB(colorA.xyz));
    const float3 hsvB = rgbToHsv(p3ToSRGB(colorB.xyz));
    const float3 mixed = awMix(hsvA, hsvB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(hsvToRgb(mixed));
    return float4(rgb, totalWeight);
}

static float3 rgbToLab(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float x = ((((((r * 0.4124564f)) + ((g * 0.3575761f)))) + ((b * 0.1804375f))));
    const float y = ((((((r * 0.2126729f)) + ((g * 0.7151522f)))) + ((b * 0.072175f))));
    const float z = ((((((r * 0.0193339f)) + ((g * 0.119192f)))) + ((b * 0.9503041f))));
    const float xn = ((x / 0.95047f));
    const float yn = ((y / 1.0f));
    const float zn = ((z / 1.08883f));
    const float fx = select(((((xn * 7.787037037037036f)) + 0.13793103448275862f)), pow(xn, 0.3333333333333333f), ((xn > 0.008856451679035631f)));
    const float fy = select(((((yn * 7.787037037037036f)) + 0.13793103448275862f)), pow(yn, 0.3333333333333333f), ((yn > 0.008856451679035631f)));
    const float fz = select(((((zn * 7.787037037037036f)) + 0.13793103448275862f)), pow(zn, 0.3333333333333333f), ((zn > 0.008856451679035631f)));
    const float L = ((((fy * 116.0f)) - 16.0f));
    const float a = ((((fx - fy)) * 500.0f));
    const float bLab = ((((fy - fz)) * 200.0f));
    return float3(L, a, bLab);
}

static float3 labToRgb(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float fy = ((((L + 16.0f)) / 116.0f));
    const float fx = ((((a / 500.0f)) + fy));
    const float fz = ((fy - ((b / 200.0f))));
    const float xn = select(((((fx - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fx, 3.0f), ((fx > 0.20689655172413793f)));
    const float yn = select(((((fy - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fy, 3.0f), ((fy > 0.20689655172413793f)));
    const float zn = select(((((fz - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fz, 3.0f), ((fz > 0.20689655172413793f)));
    const float x = ((xn * 0.95047f));
    const float y = ((yn * 1.0f));
    const float z = ((zn * 1.08883f));
    const float r = ((((((x * 3.2404542f)) - ((y * 1.5371385f)))) - ((z * 0.4985314f))));
    const float g = ((((((x * (-0.969266f))) + ((y * 1.8760108f)))) + ((z * 0.041556f))));
    const float bRgb = ((((((x * 0.0556434f)) - ((y * 0.2040259f)))) + ((z * 1.0572252f))));
    return float3(r, g, bRgb);
}

static float4 mixColors_6(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 lchA = oklabToOklch(rgbToLab(p3ToSRGB(colorA.xyz)));
    const float3 lchB = oklabToOklch(rgbToLab(p3ToSRGB(colorB.xyz)));
    const float3 mixed = awMix(lchA, lchB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(labToRgb(oklchToOklab(mixed)));
    return float4(rgb, totalWeight);
}

static MixStep mixPreconvertedInSpace(float3 convA, float alphaA, float3 convB, float alphaB, float t) {
    const float weightA = ((alphaA * ((1.0f - t))));
    const float weightB = ((alphaB * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    return MixStep{awMix(convA, convB, weightA, weightB, safeWeight), totalWeight};
}

static MixStep gradientStopsInSpace(float t, metal::array<float4, 8> colors, metal::array<float4, 2> positions, metal::array<float3, 8> converted, float stopCount) {
    const float clampedT = clamp(t, 0.0f, 1.0f);
    const int n = int(stopCount);
    const float3 c0 = converted[0];
    float3 conv = float3(c0.x, c0.y, c0.z);
    float alpha = colors[0].w;
    for (int i = 1; ((i < n)); i++) {
        const float4 va = positions[((((i - 1)) >> 2u))];
        const float4 vb = positions[((i >> 2u))];
        const float posA = va[((((i - 1)) & 3))];
        const float posB = vb[((i & 3))];
        const float seg = clamp(((((clampedT - posA)) / max(((posB - posA)), 1.0e-6f))), 0.0f, 1.0f);
        const MixStep step_1 = mixPreconvertedInSpace(conv, alpha, converted[i], colors[i].w, seg);
        conv = float3(step_1.conv.x, step_1.conv.y, step_1.conv.z);
        alpha = step_1.alpha;
    }
    return MixStep{conv, alpha};
}

static float gaussianBrushSq(float distSq, float radiusSq) {
    return exp(((((distSq / radiusSq)) * (-1.0f))));
}

static void smokeSplat(uint cx, uint cy, device float4* dyeA, constant FluidParams& params, device float4* velA) {
    auto p = ((&params));
    const uint idx = ((((cy * 256u)) + cx));
    const float cellX = ((float(cx) + 0.5f));
    const float cellY = ((float(cy) + 0.5f));
    const float dx = ((cellX - ((*p)).emitX));
    const float dy = ((cellY - ((*p)).emitY));
    const float distSq = ((((dx * dx)) + ((dy * dy))));
    const float radSq = max(((((*p)).emitRad * ((*p)).emitRad)), 1.0f);
    const float influence = gaussianBrushSq(distSq, radSq);
    auto cell = ((&dyeA[idx]));
    const float oldDens = ((*cell)).x;
    const float addDens = ((((((((*p)).emitIntensity * influence)) * ((*p)).dt)) * 8.0f));
    const float newDens = min(((oldDens + addDens)), 1.0f);
    const float rejuvenate = ((addDens / max(newDens, 0.0010000000474974513f)));
    dyeA[idx] = float4(newDens, ((((*cell)).y * ((1.0f - min(rejuvenate, 1.0f))))), 0.0f, 0.0f);
    auto vel = ((&velA[idx]));
    const float perpOff = ((((((dx * ((*p)).perpDirX)) + ((dy * ((*p)).perpDirY)))) / max(((*p)).emitRad, 1.0f)));
    const float vmSq = max(((((((*p)).emitVelX * ((*p)).emitVelX)) + ((((*p)).emitVelY * ((*p)).emitVelY)))), 1.0f);
    const float tvx = ((((*p)).emitVelX + ((((((((*p)).perpDirX * perpOff)) * ((*p)).spreadFactor)) * sqrt(vmSq)))));
    const float tvy = ((((*p)).emitVelY + ((((((((*p)).perpDirY * perpOff)) * ((*p)).spreadFactor)) * sqrt(vmSq)))));
    const float br = min(((((influence * ((*p)).dt)) * 3.0f)), 1.0f);
    const float gravForce = ((((((((*p)).gravity * oldDens)) * ((*p)).dt)) * 20.48f));
    const float cursorDX = ((cellX - ((*p)).cursorX));
    const float cursorDY = ((cellY - ((*p)).cursorY));
    const float cursorDistSq = ((((cursorDX * cursorDX)) + ((cursorDY * cursorDY))));
    const float cursorInf = ((gaussianBrushSq(cursorDistSq, max(((*p)).mouseRadSq, 1.0f)) * ((*p)).mouseActive));
    velA[idx] = float4(((mix(((*vel)).x, tvx, br) + ((((*p)).cursorVelX * cursorInf)))), ((((mix(((*vel)).y, tvy, br) + gravForce)) + ((((*p)).cursorVelY * cursorInf)))), ((*vel)).z, 0.0f);
}

static uint nidx(int ii, int ji, int di, int dj) {
    const int row = clamp(((ii + di)), 0, 255);
    const int col = clamp(((ji + dj)), 0, 255);
    return uint(((((row * 256)) + col)));
}

static void smokeCurl(uint cx, uint cy, device float4* velA) {
    const uint idx = ((((cy * 256u)) + cx));
    const int ii = int(cy);
    const int ji = int(cx);
    auto vL = ((&velA[nidx(ii, ji, 0, (-1))]));
    auto vR = ((&velA[nidx(ii, ji, 0, 1)]));
    auto vU = ((&velA[nidx(ii, ji, (-1), 0)]));
    auto vD = ((&velA[nidx(ii, ji, 1, 0)]));
    const float curlZ = ((((((((*vR)).y - ((*vL)).y)) - ((((*vD)).x - ((*vU)).x)))) * 0.5f));
    auto vel = ((&velA[idx]));
    velA[idx] = float4(((*vel)).x, ((*vel)).y, curlZ, 0.0f);
}

static void smokeVorticity(uint cx, uint cy, constant FluidParams& params, device float4* velA) {
    auto p = ((&params));
    const uint idx = ((((cy * 256u)) + cx));
    const int ii = int(cy);
    const int ji = int(cx);
    const float cL = abs(velA[nidx(ii, ji, 0, (-1))].z);
    const float cR = abs(velA[nidx(ii, ji, 0, 1)].z);
    const float cU = abs(velA[nidx(ii, ji, (-1), 0)].z);
    const float cD = abs(velA[nidx(ii, ji, 1, 0)].z);
    const float cc = velA[idx].z;
    const float gx = ((((cR - cL)) * 0.5f));
    const float gy = ((((cD - cU)) * 0.5f));
    const float gl = max(sqrt(((((gx * gx)) + ((gy * gy))))), 9.999999747378752e-6f);
    const float fx = ((((((((gy / gl)) * cc)) * ((*p)).curlStrength)) * ((*p)).dt));
    const float fy = ((((((((((gx / gl)) * (-1.0f))) * cc)) * ((*p)).curlStrength)) * ((*p)).dt));
    auto vel = ((&velA[idx]));
    velA[idx] = float4(((((*vel)).x + fx)), ((((*vel)).y + fy)), ((*vel)).z, 0.0f);
}

static void smokeDivergence(uint cx, uint cy, device float* divergence, device float* pressure, device float4* velA) {
    const uint idx = ((((cy * 256u)) + cx));
    const int ii = int(cy);
    const int ji = int(cx);
    const float jf = float(cx);
    const float iF = float(cy);
    auto selfVel = ((&velA[idx]));
    const float normalL = velA[nidx(ii, ji, 0, (-1))].x;
    const float normalR = velA[nidx(ii, ji, 0, 1)].x;
    const float normalU = velA[nidx(ii, ji, (-1), 0)].y;
    const float normalD = velA[nidx(ii, ji, 1, 0)].y;
    const float L = select(normalL, ((((*selfVel)).x * (-1.0f))), ((jf < 0.5f)));
    const float R = select(normalR, ((((*selfVel)).x * (-1.0f))), ((jf > 254.5f)));
    const float T = select(normalU, ((((*selfVel)).y * (-1.0f))), ((iF < 0.5f)));
    const float B = select(normalD, ((((*selfVel)).y * (-1.0f))), ((iF > 254.5f)));
    const float div = ((((((R - L)) + ((B - T)))) * 0.5f));
    pressure[idx] = ((pressure[idx] * 0.8f));
    divergence[idx] = div;
}

static void smokeJacobi(uint cx, uint cy, device float* divergence, device float* pressure) {
    const uint idx = ((((cy * 256u)) + cx));
    const int ii = int(cy);
    const int ji = int(cx);
    const float pL = pressure[nidx(ii, ji, 0, (-1))];
    const float pR = pressure[nidx(ii, ji, 0, 1)];
    const float pU = pressure[nidx(ii, ji, (-1), 0)];
    const float pD = pressure[nidx(ii, ji, 1, 0)];
    const float div = divergence[idx];
    pressure[idx] = ((((((((((pL + pR)) + pU)) + pD)) - div)) * 0.25f));
}

static void smokeGradSubtract(uint cx, uint cy, device float* pressure, device float4* velA) {
    const uint idx = ((((cy * 256u)) + cx));
    const int ii = int(cy);
    const int ji = int(cx);
    const float pL = pressure[nidx(ii, ji, 0, (-1))];
    const float pR = pressure[nidx(ii, ji, 0, 1)];
    const float pU = pressure[nidx(ii, ji, (-1), 0)];
    const float pD = pressure[nidx(ii, ji, 1, 0)];
    auto vel = ((&velA[idx]));
    velA[idx] = float4(((((*vel)).x - ((((pR - pL)) * 0.5f)))), ((((*vel)).y - ((((pD - pU)) * 0.5f)))), ((*vel)).z, 0.0f);
}

static void smokeAdvectVel(uint cx, uint cy, constant FluidParams& params, device float4* velA, device float4* velB) {
    auto p = ((&params));
    const uint idx = ((((cy * 256u)) + cx));
    auto vel = ((&velA[idx]));
    const float srcX = clamp(((float(cx) - ((((*vel)).x * ((*p)).dt)))), 0.0f, 255.0f);
    const float srcY = clamp(((float(cy) - ((((*vel)).y * ((*p)).dt)))), 0.0f, 255.0f);
    const float x0 = clamp(floor(srcX), 0.0f, 254.0f);
    const float y0 = clamp(floor(srcY), 0.0f, 254.0f);
    const float sx = ((srcX - x0));
    const float sy = ((srcY - y0));
    const int ix0 = int(x0);
    const int iy0 = int(y0);
    auto v00 = ((&velA[uint(((((iy0 * 256)) + ix0)))]));
    auto v10 = ((&velA[uint(((((((iy0 * 256)) + ix0)) + 1)))]));
    auto v01 = ((&velA[uint(((((((iy0 + 1)) * 256)) + ix0)))]));
    auto v11 = ((&velA[uint(((((((((iy0 + 1)) * 256)) + ix0)) + 1)))]));
    const float decay = ((1.0f + ((((*p)).velFade * ((*p)).dt))));
    velB[idx] = float4(((mix(mix(((*v00)).x, ((*v10)).x, sx), mix(((*v01)).x, ((*v11)).x, sx), sy) / decay)), ((mix(mix(((*v00)).y, ((*v10)).y, sx), mix(((*v01)).y, ((*v11)).y, sx), sy) / decay)), 0.0f, 0.0f);
}

static void smokeCopyVel(uint cx, uint cy, device float4* velA, device float4* velB) {
    const uint idx = ((((cy * 256u)) + cx));
    auto v = ((&velB[idx]));
    velA[idx] = float4(((*v)).x, ((*v)).y, 0.0f, 0.0f);
}

static void smokeAdvectDens(uint cx, uint cy, device float4* dyeA, device float4* dyeB, constant FluidParams& params, device float4* velA) {
    auto p = ((&params));
    const uint idx = ((((cy * 256u)) + cx));
    auto vel = ((&velA[idx]));
    const float srcX = clamp(((float(cx) - ((((*vel)).x * ((*p)).dt)))), 0.0f, 255.0f);
    const float srcY = clamp(((float(cy) - ((((*vel)).y * ((*p)).dt)))), 0.0f, 255.0f);
    const float x0 = clamp(floor(srcX), 0.0f, 254.0f);
    const float y0 = clamp(floor(srcY), 0.0f, 254.0f);
    const float sx = ((srcX - x0));
    const float sy = ((srcY - y0));
    const int ix0 = int(x0);
    const int iy0 = int(y0);
    auto d00 = ((&dyeA[uint(((((iy0 * 256)) + ix0)))]));
    auto d10 = ((&dyeA[uint(((((((iy0 * 256)) + ix0)) + 1)))]));
    auto d01 = ((&dyeA[uint(((((((iy0 + 1)) * 256)) + ix0)))]));
    auto d11 = ((&dyeA[uint(((((((((iy0 + 1)) * 256)) + ix0)) + 1)))]));
    const float dens = mix(mix(((*d00)).x, ((*d10)).x, sx), mix(((*d01)).x, ((*d11)).x, sx), sy);
    const float age = mix(mix(((*d00)).y, ((*d10)).y, sx), mix(((*d01)).y, ((*d11)).y, sx), sy);
    const float decay = ((1.0f + ((((*p)).dyeFade * ((*p)).dt))));
    dyeB[idx] = float4(max(((dens / decay)), 0.0f), min(((age + ((((((*p)).dt * 0.4f)) * ((*p)).colorDecay)))), 1.0f), 0.0f, 0.0f);
}

static void smokeCopyDens(uint cx, uint cy, device float4* dyeA, device float4* dyeB) {
    const uint idx = ((((cy * 256u)) + cx));
    auto dd = ((&dyeB[idx]));
    dyeA[idx] = float4(((*dd)).x, ((*dd)).y, 0.0f, 0.0f);
}

static void smokeOutput(uint cx, uint cy, device float4* dyeA, texture2d<float, access::write> outTex) {
    const uint idx = ((((cy * 256u)) + cx));
    auto dd = ((&dyeA[idx]));
    outTex.write(float4(((*dd)).x, ((*dd)).y, 0.0f, 0.0f), uint2(cx, cy));
}
} // namespace S_Smoke

using namespace S_Smoke;

fragment float4 Smoke_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Smoke_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors_2(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors_2(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Smoke_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors_3(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors_3(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Smoke_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors_4(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors_4(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Smoke_v4_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors_5(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors_5(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Smoke_v5_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = float4((mixColors_6(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).rgb, (((mixColors_6(uniforms.n_x.colorA, uniforms.n_x.colorB, (compute_0.sample(linearClamp, uv)).y)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_0;
}

fragment float4 Smoke_v6_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const MixStep stopMix_0 = gradientStopsInSpace((compute_0.sample(linearClamp, uv)).y, uniforms.n_x.colorsArray, uniforms.n_x.positionsArray, uniforms.n_x.convertedColorsArray, uniforms.n_x.stopCount);
    float4 composed_1 = float4((float4(stopMix_0.conv, stopMix_0.alpha)).rgb, (((float4(stopMix_0.conv, stopMix_0.alpha)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_1;
}

fragment float4 Smoke_v7_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const MixStep stopMix_0 = gradientStopsInSpace((compute_0.sample(linearClamp, uv)).y, uniforms.n_x.colorsArray, uniforms.n_x.positionsArray, uniforms.n_x.convertedColorsArray, uniforms.n_x.stopCount);
    float4 composed_1 = float4((float4(sRGBToP3(oklabToRgb(oklchToOklab(stopMix_0.conv))), stopMix_0.alpha)).rgb, (((float4(sRGBToP3(oklabToRgb(oklchToOklab(stopMix_0.conv))), stopMix_0.alpha)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_1;
}

fragment float4 Smoke_v8_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const MixStep stopMix_0 = gradientStopsInSpace((compute_0.sample(linearClamp, uv)).y, uniforms.n_x.colorsArray, uniforms.n_x.positionsArray, uniforms.n_x.convertedColorsArray, uniforms.n_x.stopCount);
    float4 composed_1 = float4((float4(sRGBToP3(oklabToRgb(stopMix_0.conv)), stopMix_0.alpha)).rgb, (((float4(sRGBToP3(oklabToRgb(stopMix_0.conv)), stopMix_0.alpha)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_1;
}

fragment float4 Smoke_v9_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const MixStep stopMix_0 = gradientStopsInSpace((compute_0.sample(linearClamp, uv)).y, uniforms.n_x.colorsArray, uniforms.n_x.positionsArray, uniforms.n_x.convertedColorsArray, uniforms.n_x.stopCount);
    float4 composed_1 = float4((float4(sRGBToP3(hslToRgb(stopMix_0.conv)), stopMix_0.alpha)).rgb, (((float4(sRGBToP3(hslToRgb(stopMix_0.conv)), stopMix_0.alpha)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_1;
}

fragment float4 Smoke_v10_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const MixStep stopMix_0 = gradientStopsInSpace((compute_0.sample(linearClamp, uv)).y, uniforms.n_x.colorsArray, uniforms.n_x.positionsArray, uniforms.n_x.convertedColorsArray, uniforms.n_x.stopCount);
    float4 composed_1 = float4((float4(sRGBToP3(hsvToRgb(stopMix_0.conv)), stopMix_0.alpha)).rgb, (((float4(sRGBToP3(hsvToRgb(stopMix_0.conv)), stopMix_0.alpha)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_1;
}

fragment float4 Smoke_v11_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const MixStep stopMix_0 = gradientStopsInSpace((compute_0.sample(linearClamp, uv)).y, uniforms.n_x.colorsArray, uniforms.n_x.positionsArray, uniforms.n_x.convertedColorsArray, uniforms.n_x.stopCount);
    float4 composed_1 = float4((float4(sRGBToP3(labToRgb(oklchToOklab(stopMix_0.conv))), stopMix_0.alpha)).rgb, (((float4(sRGBToP3(labToRgb(oklchToOklab(stopMix_0.conv))), stopMix_0.alpha)).a * (compute_0.sample(linearClamp, uv)).x)));
    return composed_1;
}

static void Smoke_k0_body(uint cx, uint cy, uint _arg_2, device float4* dyeA, constant FluidParams& params, device float4* velA) {
    smokeSplat(cx, cy, dyeA, params, velA);
}

kernel void Smoke_k0(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float4* dyeA [[buffer(1)]], constant FluidParams& params [[buffer(2)]], constant uint3& sk_size [[buffer(3)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k0_body(sk_gid.x, sk_gid.y, sk_gid.z, dyeA, params, velA);
}

static void Smoke_k1_body(uint cx, uint cy, uint _arg_2, device float4* velA) {
    smokeCurl(cx, cy, velA);
}

kernel void Smoke_k1(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], constant uint3& sk_size [[buffer(1)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k1_body(sk_gid.x, sk_gid.y, sk_gid.z, velA);
}

static void Smoke_k2_body(uint cx, uint cy, uint _arg_2, constant FluidParams& params, device float4* velA) {
    smokeVorticity(cx, cy, params, velA);
}

kernel void Smoke_k2(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], constant FluidParams& params [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k2_body(sk_gid.x, sk_gid.y, sk_gid.z, params, velA);
}

static void Smoke_k3_body(uint cx, uint cy, uint _arg_2, device float* divergence, device float* pressure, device float4* velA) {
    smokeDivergence(cx, cy, divergence, pressure, velA);
}

kernel void Smoke_k3(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float* pressure [[buffer(1)]], device float* divergence [[buffer(2)]], constant uint3& sk_size [[buffer(3)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k3_body(sk_gid.x, sk_gid.y, sk_gid.z, divergence, pressure, velA);
}

static void Smoke_k4_body(uint cx, uint cy, uint _arg_2, device float* divergence, device float* pressure) {
    smokeJacobi(cx, cy, divergence, pressure);
}

kernel void Smoke_k4(uint3 sk_gid [[thread_position_in_grid]], device float* pressure [[buffer(0)]], device float* divergence [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k4_body(sk_gid.x, sk_gid.y, sk_gid.z, divergence, pressure);
}

static void Smoke_k5_body(uint cx, uint cy, uint _arg_2, device float* pressure, device float4* velA) {
    smokeGradSubtract(cx, cy, pressure, velA);
}

kernel void Smoke_k5(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float* pressure [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k5_body(sk_gid.x, sk_gid.y, sk_gid.z, pressure, velA);
}

static void Smoke_k6_body(uint cx, uint cy, uint _arg_2, constant FluidParams& params, device float4* velA, device float4* velB) {
    smokeAdvectVel(cx, cy, params, velA, velB);
}

kernel void Smoke_k6(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float4* velB [[buffer(1)]], constant FluidParams& params [[buffer(2)]], constant uint3& sk_size [[buffer(3)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k6_body(sk_gid.x, sk_gid.y, sk_gid.z, params, velA, velB);
}

static void Smoke_k7_body(uint cx, uint cy, uint _arg_2, device float4* velA, device float4* velB) {
    smokeCopyVel(cx, cy, velA, velB);
}

kernel void Smoke_k7(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float4* velB [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k7_body(sk_gid.x, sk_gid.y, sk_gid.z, velA, velB);
}

static void Smoke_k8_body(uint cx, uint cy, uint _arg_2, device float4* dyeA, device float4* dyeB, constant FluidParams& params, device float4* velA) {
    smokeAdvectDens(cx, cy, dyeA, dyeB, params, velA);
}

kernel void Smoke_k8(uint3 sk_gid [[thread_position_in_grid]], device float4* velA [[buffer(0)]], device float4* dyeA [[buffer(1)]], device float4* dyeB [[buffer(2)]], constant FluidParams& params [[buffer(3)]], constant uint3& sk_size [[buffer(4)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k8_body(sk_gid.x, sk_gid.y, sk_gid.z, dyeA, dyeB, params, velA);
}

static void Smoke_k9_body(uint cx, uint cy, uint _arg_2, device float4* dyeA, device float4* dyeB) {
    smokeCopyDens(cx, cy, dyeA, dyeB);
}

kernel void Smoke_k9(uint3 sk_gid [[thread_position_in_grid]], device float4* dyeA [[buffer(0)]], device float4* dyeB [[buffer(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k9_body(sk_gid.x, sk_gid.y, sk_gid.z, dyeA, dyeB);
}

static void Smoke_k10_body(uint cx, uint cy, uint _arg_2, device float4* dyeA, texture2d<float, access::write> outTex) {
    smokeOutput(cx, cy, dyeA, outTex);
}

kernel void Smoke_k10(uint3 sk_gid [[thread_position_in_grid]], device float4* dyeA [[buffer(0)]], texture2d<float, access::write> outTex [[texture(0)]], constant uint3& sk_size [[buffer(1)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Smoke_k10_body(sk_gid.x, sk_gid.y, sk_gid.z, dyeA, outTex);
}
