// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: Surface3D
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_Surface3D {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float amplitude;
    float frequency;
    float octaves;
    float seed;
    float speed;
    float tilt;
    float roll;
    float height;
    float zoom;
    float nearCutoff;
    float farCutoff;
    float edgePinning;
    float edges;
    float lighting;
    float glossiness;
    float highlights;
    float lightX;
    float lightY;
    float lightZ;
    float4 lightColor;
    float cursorIntensity;
    float cursorSpeed;
    float _opacity;
    char _sk_pad0[4];
};

struct struct_2 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    struct_1 n_x;
    padded n_child;
    struct_2 _sys;
};

struct HeightFieldParams {
    float amp;
    float freq;
    float seed;
    float edgePin;
    float cursorIntensity;
    float t;
    float aspect;
    float focal;
    float3 camPos;
    float3 camForward;
    float3 camRight;
    packed_float3 camUp;
    float lighting;
    float glossiness;
    float highlights;
    float lightX;
    float lightY;
    float lightZ;
    char _sk_pad0[12];
    packed_float3 lightColor;
    float nearCutoff;
    float farCutoff;
    float cursorWaveX;
    float cursorWaveY;
    float mouseSpeed;
    float dt;
    float decay;
    float radius;
    float waveSpeed;
    float heightEnvelope;
    float cursorActive;
    char _sk_pad1[8];
};

static float4 unpremultiplyAlpha(float4 color2) {
    const float alpha = color2.w;
    const float3 straightRGB = select(float3(0), ((color2.xyz / alpha)), ((alpha > 1.0e-3f)));
    return float4(straightRGB, alpha);
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float mxFade(float t) {
    return ((((((t * t)) * t)) * ((((t * ((((t * 6.0f)) - 15.0f)))) + 10.0f))));
}

static uint mxRotl32(uint x, int k) {
    return ((((x << uint(k))) | ((x >> uint(((32 - k)))))));
}

static uint mxBjfinal(uint a0, uint b0, uint c0) {
    uint a = a0;
    uint b = b0;
    uint c = c0;
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 14)));
    a = ((a ^ c));
    a = ((a - mxRotl32(c, 11)));
    b = ((b ^ a));
    b = ((b - mxRotl32(a, 25)));
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 16)));
    a = ((a ^ c));
    a = ((a - mxRotl32(c, 4)));
    b = ((b ^ a));
    b = ((b - mxRotl32(a, 14)));
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 24)));
    return c;
}

static uint mxHashInt1(int x, int y) {
    const uint len = 2u;
    const uint seed = ((((3735928559u + ((len << 2u)))) + 13u));
    const uint a = ((seed + uint(x)));
    const uint b = ((seed + uint(y)));
    return mxBjfinal(a, b, seed);
}

static float mxGradientFloat2(uint hash, float x, float y) {
    const uint h = ((hash & 7u));
    const float u = select(y, x, ((h < 4u)));
    const float v = ((2.0f * select(x, y, ((h < 4u)))));
    const float uu = select(u, (-(u)), ((((h & 1u)) != 0u)));
    const float vv = select(v, (-(v)), ((((h & 2u)) != 0u)));
    return ((uu + vv));
}

static float mxBilerp(float v0, float v1, float v2, float v3, float s, float t) {
    const float s1 = ((1.0f - s));
    return ((((((1.0f - t)) * ((((v0 * s1)) + ((v1 * s)))))) + ((t * ((((v2 * s1)) + ((v3 * s))))))));
}

static float mxGradientScale2d(float v) {
    return ((0.6616f * v));
}

static float mxPerlinNoiseFloat2(float2 p) {
    const int X = int(floor(p.x));
    const int Y = int(floor(p.y));
    const float fx = ((p.x - float(X)));
    const float fy = ((p.y - float(Y)));
    const float u = mxFade(fx);
    const float v = mxFade(fy);
    const float result = mxBilerp(mxGradientFloat2(mxHashInt1(X, Y), fx, fy), mxGradientFloat2(mxHashInt1(((X + 1)), Y), ((fx - 1.0f)), fy), mxGradientFloat2(mxHashInt1(X, ((Y + 1))), fx, ((fy - 1.0f))), mxGradientFloat2(mxHashInt1(((X + 1)), ((Y + 1))), ((fx - 1.0f)), ((fy - 1.0f))), u, v);
    return mxGradientScale2d(result);
}

static float mxNoiseFloat2(float2 p) {
    return mxPerlinNoiseFloat2(p);
}

static float spectralHeightField(float2 uv, constant HeightFieldParams& params, device float* readBuf) {
    auto p = ((&params));
    const float u = uv.x;
    const float v = uv.y;
    const float amp = ((*p)).amp;
    const float freq = ((*p)).freq;
    const float seedU = ((*p)).seed;
    float waveVal = 0.0f;
    {
        const float warpFreq = ((freq * 0.5f));
        const float wx = mxNoiseFloat2(float2(((((((u * warpFreq)) + ((((*p)).t * 0.1f)))) + seedU)), ((((v * warpFreq)) + ((seedU * 1.3f))))));
        const float wy = mxNoiseFloat2(float2(((((((u * warpFreq)) + seedU)) + 17.3f)), ((((((((v * warpFreq)) + ((((*p)).t * 0.07f)))) + seedU)) + 31.1f))));
        const float wu = ((u + ((wx * 0.4f))));
        const float wv = ((v + ((wy * 0.4f))));
        float accW = 0.0f;
        for (int i = 0; ((i < 2)); i++) {
            const float iF = float(i);
            const float scale = exp2(iF);
            const float weight = exp2(((iF * (-1.0f))));
            const float driftX = cos(((iF * 2.39996f)));
            const float driftY = sin(((iF * 2.39996f)));
            const float2 coord = float2(((((((((wu * freq)) * scale)) + ((((*p)).t * ((driftX * 0.3f)))))) + seedU)), ((((((((wv * freq)) * scale)) + ((((*p)).t * ((driftY * 0.3f)))))) + ((seedU * 0.7f)))));
            accW = ((accW + ((mxNoiseFloat2(coord) * weight))));
        }
        waveVal = ((accW * 0.6666666666666666f));
    }
    const float cu = ((((u - 0.5f)) * 2.0f));
    const float cv = ((((v - 0.5f)) * 2.0f));
    const float inner = max(abs(cu), abs(cv));
    const float pinFalloff = smoothstep(0.6f, 1.0f, inner);
    const float pinMask = mix(1.0f, ((1.0f - pinFalloff)), ((*p)).edgePin);
    const float baseHeight = ((((waveVal * amp)) * pinMask));
    {
        float ripple = 0.0f;
        if ((((((*p)).cursorActive > 0.5f)))) {
            const float H = 3.0f;
            const float waveU = ((((((uv.x - 0.5f)) / H)) + 0.5f));
            const float waveV = ((((((uv.y - 0.5f)) / H)) + 0.5f));
            const float Nm1 = 255.0f;
            const float gx = ((clamp(waveU, 0.0f, 1.0f) * Nm1));
            const float gy = ((clamp(waveV, 0.0f, 1.0f) * Nm1));
            const uint ix = wgsl_f2u(clamp(gx, 0.0f, Nm1));
            const uint iy = wgsl_f2u(clamp(gy, 0.0f, Nm1));
            const uint ix1 = min(((ix + 1u)), 255u);
            const uint iy1 = min(((iy + 1u)), 255u);
            const float fx = ((gx - floor(gx)));
            const float fy = ((gy - floor(gy)));
            const uint W = 256u;
            const float v00 = readBuf[((((iy * W)) + ix))];
            const float v10 = readBuf[((((iy * W)) + ix1))];
            const float v01 = readBuf[((((iy1 * W)) + ix))];
            const float v11 = readBuf[((((iy1 * W)) + ix1))];
            const float waveSample = mix(mix(v00, v10, fx), mix(v01, v11, fx), fy);
            ripple = ((waveSample * ((((*p)).cursorIntensity * 0.05f))));
        }
        return ((baseHeight + ripple));
    }
}

static void heightFieldMarch(uint cx, uint cy, texture2d<float, access::write> litTex, constant HeightFieldParams& params, device float* readBuf, texture2d<float, access::write> uvMaskTex) {
    auto p = ((&params));
    const float screenU = ((((float(cx) + 0.5f)) / 800.0f));
    const float screenV = ((((float(cy) + 0.5f)) / 600.0f));
    const float ndcX = ((((((screenU - 0.5f)) * 2.0f)) * ((*p)).aspect));
    const float ndcY = ((((((screenV - 0.5f)) * 2.0f)) * (-1.0f)));
    const float3 rayDir = normalize(((((((((*p)).camForward * ((*p)).focal)) + ((((*p)).camRight * ndcX)))) + ((float3(((*p)).camUp) * ndcY)))));
    const float envelope = ((*p)).heightEnvelope;
    const float dzSign = select((-1.0f), 1.0f, ((rayDir.z >= 0.0f)));
    const float dzSafe = ((dzSign * max(abs(rayDir.z), 9.999999974752427e-7f)));
    const float tTop = ((((envelope - ((*p)).camPos.z)) / dzSafe));
    const float tBot = ((((((envelope * (-1.0f))) - ((*p)).camPos.z)) / dzSafe));
    const float tEnter = max(min(tTop, tBot), 0.0f);
    const float tExit = min(max(tTop, tBot), 15.0f);
    const float3 farPos = ((((*p)).camPos + ((rayDir * 15.0f))));
    float hit = 0.0f;
    float finalT = 15.0f;
    float hitU = ((((farPos.x * 0.5f)) + 0.5f));
    float hitV = ((((farPos.y * 0.5f)) + 0.5f));
    float3 lit = float3(1);
    if ((((tExit > tEnter)))) {
        const float stepSize = ((((tExit - tEnter)) / 16.0f));
        float tMarch = tEnter;
        const float3 pStart = ((((*p)).camPos + ((rayDir * tEnter))));
        float prevDiff = ((pStart.z - spectralHeightField(float2(((((pStart.x * 0.5f)) + 0.5f)), ((((pStart.y * 0.5f)) + 0.5f))), params, readBuf)));
        for (int s = 0; ((s < 16)); s++) {
            tMarch = ((tMarch + stepSize));
            const float3 pos = ((((*p)).camPos + ((rayDir * tMarch))));
            const float h = spectralHeightField(float2(((((pos.x * 0.5f)) + 0.5f)), ((((pos.y * 0.5f)) + 0.5f))), params, readBuf);
            const float diff = ((pos.z - h));
            if ((((((diff < 0.0f)) && ((prevDiff > 0.0f)))))) {
                hit = 1.0f;
                break;
            }
            prevDiff = diff;
        }
        if ((((hit > 0.5f)))) {
            float tLow = ((tMarch - stepSize));
            float tHigh = tMarch;
            for (int r = 0; ((r < 6)); r++) {
                const float tMid = ((((tLow + tHigh)) * 0.5f));
                const float3 pMid = ((((*p)).camPos + ((rayDir * tMid))));
                const float dMid = ((pMid.z - spectralHeightField(float2(((((pMid.x * 0.5f)) + 0.5f)), ((((pMid.y * 0.5f)) + 0.5f))), params, readBuf)));
                if ((((dMid > 0.0f)))) {
                    tLow = tMid;
                } else {
                    tHigh = tMid;
                }
            }
            finalT = ((((tLow + tHigh)) * 0.5f));
            const float3 hitPos = ((((*p)).camPos + ((rayDir * finalT))));
            hitU = ((((hitPos.x * 0.5f)) + 0.5f));
            hitV = ((((hitPos.y * 0.5f)) + 0.5f));
            {
                const float normalEps = 0.01f;
                const float hC = spectralHeightField(float2(hitU, hitV), params, readBuf);
                const float hR = spectralHeightField(float2(((hitU + normalEps)), hitV), params, readBuf);
                const float hUp = spectralHeightField(float2(hitU, ((hitV + normalEps))), params, readBuf);
                const float dhdu = ((((hR - hC)) / normalEps));
                const float dhdv = ((((hUp - hC)) / normalEps));
                const float3 nrm = normalize(float3(((dhdu * (-0.5f))), ((dhdv * (-0.5f))), 1.0f));
                const float3 lightDir = normalize(float3(((*p)).lightX, ((*p)).lightY, ((*p)).lightZ));
                const float3 viewDir = ((rayDir * (-1.0f)));
                const float diffuse = clamp(dot(nrm, lightDir), 0.0f, 1.0f);
                const float3 halfVec = normalize(((lightDir + viewDir)));
                const float specPow = ((((((*p)).glossiness * 128.0f)) + 4.0f));
                const float specular = ((pow(clamp(dot(nrm, halfVec), 0.0f, 1.0f), specPow) * ((*p)).highlights));
                const float3 ambient = float3(0.4000000059604645f);
                const packed_float3 tintedDiffuse = ((float3(((*p)).lightColor) * ((diffuse * 0.6f))));
                const packed_float3 tintedSpec = ((float3(((*p)).lightColor) * specular));
                const float3 totalLight = ((((ambient + tintedDiffuse)) + tintedSpec));
                lit = clamp(mix(float3(1), totalLight, ((*p)).lighting), float3(0), float3(3));
            }
        }
    }
    const float2 rawSampleUV = float2(hitU, ((1.0f - hitV)));
    float2 finalUV = float2(rawSampleUV.x, rawSampleUV.y);
    const float outOfBoundsMask = 1.0f;
    finalUV = clamp(rawSampleUV, float2(0), float2(1));
    const float CUTOFF_RANGE = 15.0f;
    const float edgeAA = 0.05f;
    const float nearT = ((((*p)).nearCutoff * CUTOFF_RANGE));
    const float farT = ((((*p)).farCutoff * CUTOFF_RANGE));
    const float nearMask = smoothstep(((nearT - edgeAA)), ((nearT + edgeAA)), finalT);
    const float farMask = smoothstep(((farT + edgeAA)), ((farT - edgeAA)), finalT);
    const float finalMask = ((((hit * outOfBoundsMask)) * ((nearMask * farMask))));
    uvMaskTex.write(float4(finalUV.x, finalUV.y, finalMask, 0.0f), uint2(cx, cy));
    litTex.write(float4(lit, 0.0f), uint2(cx, cy));
}

static void waveEquationStep(uint cx, uint cy, constant HeightFieldParams& params, device float* readBuf, device float* readSrc, device float* writeBuf) {
    if ((((((((((cx > 0u)) && ((cx < 255u)))) && ((cy > 0u)))) && ((cy < 255u)))))) {
        auto p = ((&params));
        const uint gs = 256u;
        const uint idx = ((((cy * gs)) + cx));
        const float left = readSrc[((idx - 1u))];
        const float right = readSrc[((idx + 1u))];
        const float up = readSrc[((idx - gs))];
        const float down = readSrc[((idx + gs))];
        const float center = readSrc[idx];
        const float sum = ((((((left + right)) + up)) + down));
        const float prev = writeBuf[idx];
        const float dampFactor = ((1.0f - ((((*p)).decay * 4.0e-3f))));
        const float k2 = ((0.5f * ((((*p)).waveSpeed * ((*p)).waveSpeed))));
        const float lap = ((sum - ((center * 4.0f))));
        float next = ((((((((center * 2.0f)) + ((lap * k2)))) - prev)) * dampFactor));
        const float cellU = ((((float(cx) + 0.5f)) / 256.0f));
        const float cellV = ((((float(cy) + 0.5f)) / 256.0f));
        const float ddx = ((cellU - ((*p)).cursorWaveX));
        const float ddy = ((cellV - ((*p)).cursorWaveY));
        const float distSq = ((((ddx * ddx)) + ((ddy * ddy))));
        const float influenceRadius = ((((*p)).radius * 3.0f));
        if ((((((distSq < ((influenceRadius * influenceRadius)))) && ((((*p)).mouseSpeed > 0.01f)))))) {
            const float influence = exp(((((distSq / max(((((*p)).radius * ((*p)).radius)), 9.999999747378752e-5f))) * (-1.0f))));
            next = ((next - ((((((influence * ((*p)).mouseSpeed)) * ((*p)).dt)) * 3.0f))));
        }
        const float bound = 6.0f;
        next = clamp(next, ((bound * (-1.0f))), bound);
        writeBuf[idx] = next;
        readBuf[idx] = next;
    }
}
} // namespace S_Surface3D

using namespace S_Surface3D;

fragment float4 Surface3D_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v4_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v5_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v6_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v7_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v8_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v9_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v10_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

fragment float4 Surface3D_v11_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], texture2d<float> compute_0 [[texture(1)]], texture2d<float> compute_1 [[texture(2)]], sampler linearClamp [[sampler(0)]]) {
    (void)(uniforms._sys.time);
    float2 uv = in.uv;
    const float4 childColor_0 = media_0.sample(linearClamp, (float4((compute_0.sample(linearClamp, uv)).r, (compute_0.sample(linearClamp, uv)).g, 0.0f, 0.0f)).xy);
    const float4 uvMaskSample_1 = compute_0.sample(linearClamp, uv);
    float4 composed_2 = unpremultiplyAlpha(float4(clamp(((childColor_0.xyz * (compute_1.sample(linearClamp, uv)).rgb)), float3(0.0f, 0.0f, 0.0f), float3(1.0f, 1.0f, 1.0f)), ((childColor_0.w * uvMaskSample_1.b))));
    return composed_2;
}

static void Surface3D_k0_body(uint cx, uint cy, uint _arg_2, texture2d<float, access::write> litTex, constant HeightFieldParams& params, device float* readBuf, texture2d<float, access::write> uvMaskTex) {
    heightFieldMarch(cx, cy, litTex, params, readBuf, uvMaskTex);
}

kernel void Surface3D_k0(uint3 sk_gid [[thread_position_in_grid]], device float* readBuf [[buffer(0)]], constant HeightFieldParams& params [[buffer(1)]], texture2d<float, access::write> uvMaskTex [[texture(0)]], texture2d<float, access::write> litTex [[texture(1)]], constant uint3& sk_size [[buffer(2)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Surface3D_k0_body(sk_gid.x, sk_gid.y, sk_gid.z, litTex, params, readBuf, uvMaskTex);
}

static void Surface3D_k1_body(uint cx, uint cy, uint _arg_2, constant HeightFieldParams& params, device float* readBuf, device float* readSrc, device float* writeBuf) {
    waveEquationStep(cx, cy, params, readBuf, readSrc, writeBuf);
}

kernel void Surface3D_k1(uint3 sk_gid [[thread_position_in_grid]], device float* readSrc [[buffer(0)]], device float* writeBuf [[buffer(1)]], device float* readBuf [[buffer(2)]], constant HeightFieldParams& params [[buffer(3)]], constant uint3& sk_size [[buffer(4)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Surface3D_k1_body(sk_gid.x, sk_gid.y, sk_gid.z, params, readBuf, readSrc, writeBuf);
}
