// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: TriangularGrid
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_TriangularGrid {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float4 colorA;
    float4 colorB;
    float cells;
    float thickness;
    float rotation;
    float softness;
    float variation;
    float speed;
    float speedVariance;
    float colorSpace;
    float _opacity;
    float _animTime;
    char _sk_pad0[8];
};

struct struct_2 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    struct_1 n_x;
    struct_2 _sys;
};

static float2 triLattice(float2 p) {
    return float2(((p.x - ((p.y / 1.7320508075688772f)))), ((p.y * 1.1547005383792517f)));
}

static float rowSpeedHash(float row) {
    return fract(((sin(((row * 127.1f))) * 43758.5453f)));
}

static float rowSpeedMultiplier(float rowHash, float variance) {
    return ((1.0f + ((((((rowHash - 0.5f)) * 4.0f)) * variance))));
}

static float cellHash(float2 id) {
    const float2 q0 = fract(((id * float2(123.33999633789062f, 345.45001220703125f))));
    const float2 q1 = ((q0 + dot(q0, ((q0 + 34.345f)))));
    return fract(((q1.x * q1.y)));
}

static float variationFactor(float rand, float variation) {
    return max(((1.0f + ((((((rand - 0.5f)) * 2.0f)) * variation)))), 0.0f);
}

static float cellVariation(float2 cellId, float variation) {
    return variationFactor(cellHash(cellId), variation);
}

static float lineMaskFromField(float field, float lineWidth, float lo, float hi) {
    return ((((1.0f - smoothstep(lo, hi, field))) * step(1.0e-4f, lineWidth)));
}

static float strokeBandSymmetric(float field, float lineWidth, float aaWidth) {
    return lineMaskFromField(field, lineWidth, ((lineWidth - aaWidth)), ((lineWidth + aaWidth)));
}

static float2 triangularGridField(float2 p, float thickness, float softness, float variation, float speedVariance, float animTime) {
    const float2 ps = triLattice(p);
    const float rowIndex = floor(ps.y);
    const float speedMod = rowSpeedMultiplier(rowSpeedHash(rowIndex), speedVariance);
    const float drift = ((animTime * speedMod));
    const float2 psShifted = float2(((ps.x - drift)), ps.y);
    const float2 cell = floor(psShifted);
    const float2 f = fract(psShifted);
    const float upper = step(1.0f, ((f.x + f.y)));
    const float2 triId = float2(((((cell.x * 2.0f)) + upper)), cell.y);
    const float variedFactor = cellVariation(triId, variation);
    const float dEdge = min(min(min(f.x, ((1.0f - f.x))), min(f.y, ((1.0f - f.y)))), abs(((((f.x + f.y)) - 1.0f))));
    const float lineWidth = ((thickness * 0.02f));
    const float aaWidth = ((max(fwidth(ps.x), fwidth(ps.y)) + ((softness * 0.5f))));
    const float lineMask = strokeBandSymmetric(dEdge, lineWidth, aaWidth);
    return float2(lineMask, variedFactor);
}

static float geom_aspectOf(float2 viewport) {
    return ((viewport.x / max(viewport.y, 1.0e-6f)));
}

static float2 rotateAboutCanvasCentre(float2 p, float aspect, float cosA, float sinA) {
    const float centerX = ((aspect * 0.5f));
    const float centerY = 0.5f;
    const float cx = ((p.x - centerX));
    const float cy = ((p.y - centerY));
    return float2(((((((cx * cosA)) - ((cy * sinA)))) + centerX)), ((((((cx * sinA)) + ((cy * cosA)))) + centerY)));
}

static float2 latticeFrameFlipY(float2 uv, float2 viewport, float cells, float rotationDeg) {
    const float aspect = geom_aspectOf(viewport);
    const float2 correctedUV = float2(((uv.x * aspect)), ((1.0f - uv.y)));
    const float rotRad = ((rotationDeg * 0.017453292519943295f));
    const float cosR = cos(rotRad);
    const float sinR = sin(rotRad);
    return ((rotateAboutCanvasCentre(correctedUV, aspect, cosR, sinR) * cells));
}

static float3 awMix(float3 a, float3 b, float wA, float wB, float sw) {
    return ((((((a * wA)) + ((b * wB)))) / sw));
}

static float4 mixColors(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 rgb = awMix(colorA.xyz, colorB.xyz, weightA, weightB, safeWeight);
    return float4(rgb, totalWeight);
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float3 p3ToSRGB(float3 p3) {
    const float r = ((((((p3.x * 1.2249401f)) - ((p3.y * 0.2249404f)))) - ((p3.z * 0.0f))));
    const float g = ((((((p3.x * (-0.0420569f))) + ((p3.y * 1.0420571f)))) + ((p3.z * 0.0f))));
    const float b = ((((((p3.x * (-0.0196376f))) - ((p3.y * 0.0786361f)))) + ((p3.z * 1.0982735f))));
    return float3(r, g, b);
}

static float3 rgbToOklab(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float l = ((((((r * 0.4122214708f)) + ((g * 0.5363325363f)))) + ((b * 0.0514459929f))));
    const float m = ((((r * 0.2119034982f)) + ((((g * 0.6806995451f)) + ((b * 0.1073969566f))))));
    const float s = ((((((r * 0.0883024619f)) + ((g * 0.2817188376f)))) + ((b * 0.6299787005f))));
    const float l_ = ((sign(l) * pow(abs(l), 0.3333333333333333f)));
    const float m_ = ((sign(m) * pow(abs(m), 0.3333333333333333f)));
    const float s_ = ((sign(s) * pow(abs(s), 0.3333333333333333f)));
    return float3(((((((l_ * 0.2104542553f)) + ((m_ * 0.793617785f)))) - ((s_ * 0.0040720468f)))), ((((((l_ * 1.9779984951f)) - ((m_ * 2.428592205f)))) + ((s_ * 0.4505937099f)))), ((((((l_ * 0.0259040371f)) + ((m_ * 0.7827717662f)))) - ((s_ * 0.808675766f)))));
}

static float3 oklabToOklch(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float C = sqrt(((((a * a)) + ((b * b)))));
    const float h = atan2(b, a);
    return float3(L, C, h);
}

static float3 oklchToOklab(float3 lch) {
    const float L = lch.x;
    const float C = lch.y;
    const float h = lch.z;
    return float3(L, ((C * cos(h))), ((C * sin(h))));
}

static float3 oklabToRgb(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float l_ = ((((L + ((a * 0.3963377774f)))) + ((b * 0.2158037573f))));
    const float m_ = ((((L - ((a * 0.1055613458f)))) - ((b * 0.0638541728f))));
    const float s_ = ((((L - ((a * 0.0894841775f)))) - ((b * 1.291485548f))));
    const float l = pow(l_, 3.0f);
    const float m = pow(m_, 3.0f);
    const float s = pow(s_, 3.0f);
    return float3(((((((l * 4.0767416621f)) - ((m * 3.3077115913f)))) + ((s * 0.2309699292f)))), ((((((l * (-1.2684380046f))) + ((m * 2.6097574011f)))) - ((s * 0.3413193965f)))), ((((((l * (-0.0041960863f))) - ((m * 0.7034186147f)))) + ((s * 1.707614701f)))));
}

static float3 sRGBToP3(float3 srgb) {
    const float r = ((((((srgb.x * 0.8224621f)) + ((srgb.y * 0.177538f)))) + ((srgb.z * 0.0f))));
    const float g = ((((((srgb.x * 0.0331941f)) + ((srgb.y * 0.9668058f)))) + ((srgb.z * 0.0f))));
    const float b = ((((((srgb.x * 0.0170826f)) + ((srgb.y * 0.0723974f)))) + ((srgb.z * 0.9105199f))));
    return float3(r, g, b);
}

static float4 mixColors_2(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 oklchA = oklabToOklch(rgbToOklab(p3ToSRGB(colorA.xyz)));
    const float3 oklchB = oklabToOklch(rgbToOklab(p3ToSRGB(colorB.xyz)));
    const float3 mixed = awMix(oklchA, oklchB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(oklabToRgb(oklchToOklab(mixed)));
    return float4(rgb, totalWeight);
}

static float4 mixColors_3(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 oklabA = rgbToOklab(p3ToSRGB(colorA.xyz));
    const float3 oklabB = rgbToOklab(p3ToSRGB(colorB.xyz));
    const float3 mixed = awMix(oklabA, oklabB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(oklabToRgb(mixed));
    return float4(rgb, totalWeight);
}

static float3 rgbToHsl(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float maxVal = max(max(r, g), b);
    const float minVal = min(min(r, g), b);
    const float delta = ((maxVal - minVal));
    const float l = ((((maxVal + minVal)) * 0.5f));
    const float satDenom = max(((1.0f - abs(((((l * 2.0f)) - 1.0f))))), 1.0e-4f);
    const float s = ((delta / satDenom));
    const bool isRMax = ((maxVal == r));
    const bool isGMax = ((maxVal == g));
    const float hueR = ((((g - b)) / max(delta, 1.0e-4f)));
    const float hueG = ((2.0f + ((((b - r)) / max(delta, 1.0e-4f)))));
    const float hueB = ((4.0f + ((((r - g)) / max(delta, 1.0e-4f)))));
    const float hue = select(select(hueB, hueG, isGMax), hueR, isRMax);
    const float h = ((hue * 1.0471975512f));
    return float3(h, s, l);
}

static float3 selectRGBBySector(float c, float x, float sector) {
    float r = 0.0f;
    float g = 0.0f;
    float b = 0.0f;
    if ((((sector < 1.0f)))) {
        r = c;
        g = x;
    } else {
        if ((((sector < 2.0f)))) {
            r = x;
            g = c;
        } else {
            if ((((sector < 3.0f)))) {
                g = c;
                b = x;
            } else {
                if ((((sector < 4.0f)))) {
                    g = x;
                    b = c;
                } else {
                    if ((((sector < 5.0f)))) {
                        r = x;
                        b = c;
                    } else {
                        r = c;
                        b = x;
                    }
                }
            }
        }
    }
    return float3(r, g, b);
}

static float3 hslToRgb(float3 hsl) {
    const float h = hsl.x;
    const float s = hsl.y;
    const float l = hsl.z;
    const float c = ((s * ((1.0f - abs(((((l * 2.0f)) - 1.0f)))))));
    const float hPrime = ((h / 1.0471975512f));
    const float x = ((c * ((1.0f - abs((((fmod(hPrime, 2.0f)) - 1.0f)))))));
    const float m = ((l - ((c * 0.5f))));
    const float sector = floor(hPrime);
    return ((selectRGBBySector(c, x, sector) + m));
}

static float4 mixColors_4(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 hslA = rgbToHsl(p3ToSRGB(colorA.xyz));
    const float3 hslB = rgbToHsl(p3ToSRGB(colorB.xyz));
    const float3 mixed = awMix(hslA, hslB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(hslToRgb(mixed));
    return float4(rgb, totalWeight);
}

static float3 rgbToHsv(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float maxVal = max(max(r, g), b);
    const float minVal = min(min(r, g), b);
    const float delta = ((maxVal - minVal));
    const float v = maxVal;
    const float s = ((delta / max(maxVal, 1.0e-4f)));
    const bool isRMax = ((maxVal == r));
    const bool isGMax = ((maxVal == g));
    const float hueR = ((((g - b)) / max(delta, 1.0e-4f)));
    const float hueG = ((2.0f + ((((b - r)) / max(delta, 1.0e-4f)))));
    const float hueB = ((4.0f + ((((r - g)) / max(delta, 1.0e-4f)))));
    const float hue = select(select(hueB, hueG, isGMax), hueR, isRMax);
    const float h = ((hue * 1.0471975512f));
    return float3(h, s, v);
}

static float3 hsvToRgb(float3 hsv) {
    const float h = hsv.x;
    const float s = hsv.y;
    const float v = hsv.z;
    const float c = ((v * s));
    const float hPrime = ((h / 1.0471975512f));
    const float x = ((c * ((1.0f - abs((((fmod(hPrime, 2.0f)) - 1.0f)))))));
    const float m = ((v - c));
    const float sector = floor(hPrime);
    return ((selectRGBBySector(c, x, sector) + m));
}

static float4 mixColors_5(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 hsvA = rgbToHsv(p3ToSRGB(colorA.xyz));
    const float3 hsvB = rgbToHsv(p3ToSRGB(colorB.xyz));
    const float3 mixed = awMix(hsvA, hsvB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(hsvToRgb(mixed));
    return float4(rgb, totalWeight);
}

static float3 rgbToLab(float3 rgb) {
    const float r = rgb.x;
    const float g = rgb.y;
    const float b = rgb.z;
    const float x = ((((((r * 0.4124564f)) + ((g * 0.3575761f)))) + ((b * 0.1804375f))));
    const float y = ((((((r * 0.2126729f)) + ((g * 0.7151522f)))) + ((b * 0.072175f))));
    const float z = ((((((r * 0.0193339f)) + ((g * 0.119192f)))) + ((b * 0.9503041f))));
    const float xn = ((x / 0.95047f));
    const float yn = ((y / 1.0f));
    const float zn = ((z / 1.08883f));
    const float fx = select(((((xn * 7.787037037037036f)) + 0.13793103448275862f)), pow(xn, 0.3333333333333333f), ((xn > 0.008856451679035631f)));
    const float fy = select(((((yn * 7.787037037037036f)) + 0.13793103448275862f)), pow(yn, 0.3333333333333333f), ((yn > 0.008856451679035631f)));
    const float fz = select(((((zn * 7.787037037037036f)) + 0.13793103448275862f)), pow(zn, 0.3333333333333333f), ((zn > 0.008856451679035631f)));
    const float L = ((((fy * 116.0f)) - 16.0f));
    const float a = ((((fx - fy)) * 500.0f));
    const float bLab = ((((fy - fz)) * 200.0f));
    return float3(L, a, bLab);
}

static float3 labToRgb(float3 lab) {
    const float L = lab.x;
    const float a = lab.y;
    const float b = lab.z;
    const float fy = ((((L + 16.0f)) / 116.0f));
    const float fx = ((((a / 500.0f)) + fy));
    const float fz = ((fy - ((b / 200.0f))));
    const float xn = select(((((fx - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fx, 3.0f), ((fx > 0.20689655172413793f)));
    const float yn = select(((((fy - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fy, 3.0f), ((fy > 0.20689655172413793f)));
    const float zn = select(((((fz - 0.13793103448275862f)) * 0.12841854934601665f)), pow(fz, 3.0f), ((fz > 0.20689655172413793f)));
    const float x = ((xn * 0.95047f));
    const float y = ((yn * 1.0f));
    const float z = ((zn * 1.08883f));
    const float r = ((((((x * 3.2404542f)) - ((y * 1.5371385f)))) - ((z * 0.4985314f))));
    const float g = ((((((x * (-0.969266f))) + ((y * 1.8760108f)))) + ((z * 0.041556f))));
    const float bRgb = ((((((x * 0.0556434f)) - ((y * 0.2040259f)))) + ((z * 1.0572252f))));
    return float3(r, g, bRgb);
}

static float4 mixColors_6(float4 colorA, float4 colorB, float t) {
    const float weightA = ((colorA.w * ((1.0f - t))));
    const float weightB = ((colorB.w * t));
    const float totalWeight = ((weightA + weightB));
    const float safeWeight = max(totalWeight, 1.0e-3f);
    const float3 lchA = oklabToOklch(rgbToLab(p3ToSRGB(colorA.xyz)));
    const float3 lchB = oklabToOklch(rgbToLab(p3ToSRGB(colorB.xyz)));
    const float3 mixed = awMix(lchA, lchB, weightA, weightB, safeWeight);
    const float3 rgb = sRGBToP3(labToRgb(oklchToOklab(mixed)));
    return float4(rgb, totalWeight);
}
} // namespace S_TriangularGrid

using namespace S_TriangularGrid;

fragment float4 TriangularGrid_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 triField_0 = triangularGridField(latticeFrameFlipY(uv, uniforms._sys.viewportSize, uniforms.n_x.cells, uniforms.n_x.rotation), uniforms.n_x.thickness, uniforms.n_x.softness, uniforms.n_x.variation, uniforms.n_x.speedVariance, uniforms.n_x._animTime);
    float4 composed_1 = mixColors(float4(((uniforms.n_x.colorA.rgb * triField_0.y)), uniforms.n_x.colorA.a), uniforms.n_x.colorB, triField_0.x);
    return composed_1;
}

fragment float4 TriangularGrid_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 triField_0 = triangularGridField(latticeFrameFlipY(uv, uniforms._sys.viewportSize, uniforms.n_x.cells, uniforms.n_x.rotation), uniforms.n_x.thickness, uniforms.n_x.softness, uniforms.n_x.variation, uniforms.n_x.speedVariance, uniforms.n_x._animTime);
    float4 composed_1 = mixColors_2(float4(((uniforms.n_x.colorA.rgb * triField_0.y)), uniforms.n_x.colorA.a), uniforms.n_x.colorB, triField_0.x);
    return composed_1;
}

fragment float4 TriangularGrid_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 triField_0 = triangularGridField(latticeFrameFlipY(uv, uniforms._sys.viewportSize, uniforms.n_x.cells, uniforms.n_x.rotation), uniforms.n_x.thickness, uniforms.n_x.softness, uniforms.n_x.variation, uniforms.n_x.speedVariance, uniforms.n_x._animTime);
    float4 composed_1 = mixColors_3(float4(((uniforms.n_x.colorA.rgb * triField_0.y)), uniforms.n_x.colorA.a), uniforms.n_x.colorB, triField_0.x);
    return composed_1;
}

fragment float4 TriangularGrid_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 triField_0 = triangularGridField(latticeFrameFlipY(uv, uniforms._sys.viewportSize, uniforms.n_x.cells, uniforms.n_x.rotation), uniforms.n_x.thickness, uniforms.n_x.softness, uniforms.n_x.variation, uniforms.n_x.speedVariance, uniforms.n_x._animTime);
    float4 composed_1 = mixColors_4(float4(((uniforms.n_x.colorA.rgb * triField_0.y)), uniforms.n_x.colorA.a), uniforms.n_x.colorB, triField_0.x);
    return composed_1;
}

fragment float4 TriangularGrid_v4_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 triField_0 = triangularGridField(latticeFrameFlipY(uv, uniforms._sys.viewportSize, uniforms.n_x.cells, uniforms.n_x.rotation), uniforms.n_x.thickness, uniforms.n_x.softness, uniforms.n_x.variation, uniforms.n_x.speedVariance, uniforms.n_x._animTime);
    float4 composed_1 = mixColors_5(float4(((uniforms.n_x.colorA.rgb * triField_0.y)), uniforms.n_x.colorA.a), uniforms.n_x.colorB, triField_0.x);
    return composed_1;
}

fragment float4 TriangularGrid_v5_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    const float2 triField_0 = triangularGridField(latticeFrameFlipY(uv, uniforms._sys.viewportSize, uniforms.n_x.cells, uniforms.n_x.rotation), uniforms.n_x.thickness, uniforms.n_x.softness, uniforms.n_x.variation, uniforms.n_x.speedVariance, uniforms.n_x._animTime);
    float4 composed_1 = mixColors_6(float4(((uniforms.n_x.colorA.rgb * triField_0.y)), uniforms.n_x.colorA.a), uniforms.n_x.colorB, triField_0.x);
    return composed_1;
}
