// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: Twirl
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_Twirl {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct padded_1 {
    float2 center;
    float intensity;
    float edges;
    float _opacity;
    float _pad0;
    float _pad1;
    char _sk_pad0[4];
};

struct struct_1 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    padded_1 n_x;
    padded n_child;
    struct_1 _sys;
};

static float2 edgeClampUV(float2 uv) {
    return clamp(uv, float2(0), float2(1));
}

static float2 twirlUV(float2 center, float intensity, float2 uv, float aspect) {
    const float2 centerPos = float2(center.x, ((1.0f - center.y)));
    const float2 delta = ((uv - centerPos));
    const float2 acd = float2(((delta.x * aspect)), delta.y);
    const float angle = ((intensity * length(acd)));
    const float cosA = cos(angle);
    const float sinA = sin(angle);
    const float rotatedX = ((((cosA * acd.x)) - ((sinA * acd.y))));
    const float rotatedY = ((((sinA * acd.x)) + ((cosA * acd.y))));
    return float2(((((rotatedX / aspect)) + centerPos.x)), ((rotatedY + centerPos.y)));
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float edgeTransparentMask(float2 uv) {
    const float inX = ((step(0.0f, uv.x) * step(uv.x, 1.0f)));
    const float inY = ((step(0.0f, uv.y) * step(uv.y, 1.0f)));
    return ((inX * inY));
}

static float2 edgeMirrorUV(float2 uv) {
    const float mirrorX = (fmod(abs(uv.x), 2.0f));
    const float mirrorY = (fmod(abs(uv.y), 2.0f));
    return float2(select(mirrorX, ((2.0f - mirrorX)), ((mirrorX >= 1.0f))), select(mirrorY, ((2.0f - mirrorY)), ((mirrorY >= 1.0f))));
}

static float2 edgeWrapUV(float2 uv) {
    return fract(uv);
}
} // namespace S_Twirl

using namespace S_Twirl;

fragment float4 Twirl_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 foldUV_0 = edgeClampUV(twirlUV(uniforms.n_x.center, uniforms.n_x.intensity, uv, uniforms._sys.aspect));
    float4 composed_1 = media_0.sample(linearClamp, foldUV_0);
    return composed_1;
}

fragment float4 Twirl_v1_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 foldUV_1 = twirlUV(uniforms.n_x.center, uniforms.n_x.intensity, uv, uniforms._sys.aspect);
    const float4 sibs_0 = media_0.sample(linearClamp, foldUV_1);
    float4 composed_2 = float4(sibs_0.rgb, ((sibs_0.a * ((1.0f * edgeTransparentMask(twirlUV(uniforms.n_x.center, uniforms.n_x.intensity, uv, uniforms._sys.aspect)))))));
    return composed_2;
}

fragment float4 Twirl_v2_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 foldUV_0 = edgeMirrorUV(twirlUV(uniforms.n_x.center, uniforms.n_x.intensity, uv, uniforms._sys.aspect));
    float4 composed_1 = media_0.sample(linearClamp, foldUV_0);
    return composed_1;
}

fragment float4 Twirl_v3_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> media_0 [[texture(0)]], sampler linearClamp [[sampler(0)]]) {
    float2 uv = in.uv;
    const float2 foldUV_0 = edgeWrapUV(twirlUV(uniforms.n_x.center, uniforms.n_x.intensity, uv, uniforms._sys.aspect));
    float4 composed_1 = media_0.sample(linearClamp, foldUV_0);
    return composed_1;
}
