// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: Water
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_Water {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float2 center;
    float scale;
    float rotation;
    float4 waterColor;
    float clarity;
    float depth;
    float shallows;
    float caustics;
    float causticScale;
    float choppiness;
    float waveScale;
    float swirl;
    float speed;
    float reflection;
    float envRotation;
    float sharpness;
    float lightAngle;
    float foam;
    float edgeSoftness;
    float _opacity;
    float _animTime;
    float _vfOriginX;
    float _vfOriginY;
    float _vfSpanX;
    float _vfSpanY;
    float _vfActiveRes;
    float _vfRBound;
    float _saRadius;
    float _saSides;
    float _saRounding;
    float _saInnerRatio;
    float _saRotation;
    float _saHeight;
    float _saOffset;
    float _saAperture;
    char _sk_pad0[4];
};

struct struct_2 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    struct_1 n_x;
    struct_2 _sys;
};

struct KeyLight {
    float3 L;
    float3 H;
};

struct RotStruct {
    float cx;
    float sx;
    float cy;
    float sy;
    float cz;
    float sz;
    char _sk_pad0[8];
};

struct MarchParams {
    RotStruct rot;
    float rBound;
    float spanX;
    float spanY;
    float originX;
    float originY;
    uint activeRes;
    float pA;
    float pB;
    float pC;
    float pD;
    float3 mb0;
    float3 mb1;
    float3 mb2;
    float3 mb3;
    float3 mb4;
    float3 mb5;
    float3 mb6;
    float3 mb7;
};

static float2 sdfSpaceUV(float2 center, float scale, float rotation, float2 uv, float aspect) {
    const float centerX = center.x;
    const float centerY = ((1.0f - center.y));
    const float dxAc = ((((uv.x - centerX)) * aspect));
    const float dy = ((uv.y - centerY));
    const float rotRad = ((rotation * 0.017453292519943295f));
    const float cosR = cos(rotRad);
    const float sinR = sin(rotRad);
    const float rdx = ((((dxAc * cosR)) + ((dy * sinR))));
    const float rdy = ((((dy * cosR)) - ((dxAc * sinR))));
    return float2(((((rdx / scale)) + 0.5f)), ((((rdy / scale)) + 0.5f)));
}

static float4 fieldSampleArg(float2 uv, texture2d<float> field, float originX, float originY, float spanX, float spanY, float activeResF, float rBound) {
    const float uxc = clamp(uv.x, originX, ((originX + spanX)));
    const float uyc = clamp(uv.y, originY, ((originY + spanY)));
    const float outsideDist = length(float2(((uv.x - uxc)), ((uv.y - uyc))));
    const float px = ((((((((uxc - originX)) / spanX)) * activeResF)) - 0.5f));
    const float py = ((((((((uyc - originY)) / spanY)) * activeResF)) - 0.5f));
    const float x0 = floor(px);
    const float y0 = floor(py);
    const float fx = ((px - x0));
    const float fy = ((py - y0));
    const float tx2 = ((fx * fx));
    const float tx3 = ((tx2 * fx));
    const float wx0 = ((((((tx3 * (-0.5f))) + tx2)) - ((fx * 0.5f))));
    const float wx1 = ((((((tx3 * 1.5f)) - ((tx2 * 2.5f)))) + 1.0f));
    const float wx2 = ((((((tx3 * (-1.5f))) + ((tx2 * 2.0f)))) + ((fx * 0.5f))));
    const float wx3 = ((((tx3 * 0.5f)) - ((tx2 * 0.5f))));
    const float ty2 = ((fy * fy));
    const float ty3 = ((ty2 * fy));
    const float wy0 = ((((((ty3 * (-0.5f))) + ty2)) - ((fy * 0.5f))));
    const float wy1 = ((((((ty3 * 1.5f)) - ((ty2 * 2.5f)))) + 1.0f));
    const float wy2 = ((((((ty3 * (-1.5f))) + ((ty2 * 2.0f)))) + ((fy * 0.5f))));
    const float wy3 = ((((ty3 * 0.5f)) - ((ty2 * 0.5f))));
    const float maxT = ((activeResF - 1.0f));
    const uint cxm = wgsl_f2u(clamp(((x0 - 1.0f)), 0.0f, maxT));
    const uint cx0 = wgsl_f2u(clamp(x0, 0.0f, maxT));
    const uint cx1 = wgsl_f2u(clamp(((x0 + 1.0f)), 0.0f, maxT));
    const uint cx2 = wgsl_f2u(clamp(((x0 + 2.0f)), 0.0f, maxT));
    const uint cym = wgsl_f2u(clamp(((y0 - 1.0f)), 0.0f, maxT));
    const uint cy0 = wgsl_f2u(clamp(y0, 0.0f, maxT));
    const uint cy1 = wgsl_f2u(clamp(((y0 + 1.0f)), 0.0f, maxT));
    const uint cy2 = wgsl_f2u(clamp(((y0 + 2.0f)), 0.0f, maxT));
    const float4 k00 = field.read(uint2(cxm, cym), 0);
    const float4 k01 = field.read(uint2(cx0, cym), 0);
    const float4 k02 = field.read(uint2(cx1, cym), 0);
    const float4 k03 = field.read(uint2(cx2, cym), 0);
    const float4 k10 = field.read(uint2(cxm, cy0), 0);
    const float4 k11 = field.read(uint2(cx0, cy0), 0);
    const float4 k12 = field.read(uint2(cx1, cy0), 0);
    const float4 k13 = field.read(uint2(cx2, cy0), 0);
    const float4 k20 = field.read(uint2(cxm, cy1), 0);
    const float4 k21 = field.read(uint2(cx0, cy1), 0);
    const float4 k22 = field.read(uint2(cx1, cy1), 0);
    const float4 k23 = field.read(uint2(cx2, cy1), 0);
    const float4 k30 = field.read(uint2(cxm, cy2), 0);
    const float4 k31 = field.read(uint2(cx0, cy2), 0);
    const float4 k32 = field.read(uint2(cx1, cy2), 0);
    const float4 k33 = field.read(uint2(cx2, cy2), 0);
    const float rAcc = ((((((((((((((((((((((((((((((((((k00.r * wx0)) * wy0)) + ((((k01.r * wx1)) * wy0)))) + ((((k02.r * wx2)) * wy0)))) + ((((k03.r * wx3)) * wy0)))) + ((((k10.r * wx0)) * wy1)))) + ((((k11.r * wx1)) * wy1)))) + ((((k12.r * wx2)) * wy1)))) + ((((k13.r * wx3)) * wy1)))) + ((((k20.r * wx0)) * wy2)))) + ((((k21.r * wx1)) * wy2)))) + ((((k22.r * wx2)) * wy2)))) + ((((k23.r * wx3)) * wy2)))) + ((((k30.r * wx0)) * wy3)))) + ((((k31.r * wx1)) * wy3)))) + ((((k32.r * wx2)) * wy3)))) + ((((k33.r * wx3)) * wy3))));
    const float aAcc = ((((((((((((((((((((((((((((((((((k00.a * wx0)) * wy0)) + ((((k01.a * wx1)) * wy0)))) + ((((k02.a * wx2)) * wy0)))) + ((((k03.a * wx3)) * wy0)))) + ((((k10.a * wx0)) * wy1)))) + ((((k11.a * wx1)) * wy1)))) + ((((k12.a * wx2)) * wy1)))) + ((((k13.a * wx3)) * wy1)))) + ((((k20.a * wx0)) * wy2)))) + ((((k21.a * wx1)) * wy2)))) + ((((k22.a * wx2)) * wy2)))) + ((((k23.a * wx3)) * wy2)))) + ((((k30.a * wx0)) * wy3)))) + ((((k31.a * wx1)) * wy3)))) + ((((k32.a * wx2)) * wy3)))) + ((((k33.a * wx3)) * wy3))));
    const float4 bl = mix(mix(k11, k12, fx), mix(k21, k22, fx), fy);
    const float rMin = min(min(k11.r, k12.r), min(k21.r, k22.r));
    const float rMax = max(max(k11.r, k12.r), max(k21.r, k22.r));
    const float aMin = min(min(k11.a, k12.a), min(k21.a, k22.a));
    const float aMax = max(max(k11.a, k12.a), max(k21.a, k22.a));
    const float aOut = clamp(aAcc, aMin, aMax);
    const float rNear = ((clamp(rAcc, rMin, rMax) + outsideDist));
    const float rCircle = ((length(float2(((uv.x - 0.5f)), ((uv.y - 0.5f)))) - rBound));
    const float rOut = mix(rNear, max(rCircle, rNear), smoothstep(0.0f, 0.25f, outsideDist));
    return float4(rOut, bl.g, bl.b, aOut);
}

static bool outsideShape(float sdf, float pxH) {
    return ((sdf > ((pxH * 2.0f))));
}

static float opticalThickness(float sdf, float volumetric) {
    const float thickVol = clamp(((((sdf * (-1.0f))) * 2.0f)), 0.0f, 1.2f);
    const float thickFlat = ((clamp(((sdf * (-1.0f))), 0.0f, 0.5f) * 2.0f));
    return select(thickFlat, thickVol, ((volumetric > 0.5f)));
}

static float3 beerLambert(float thickness, float3 absorb) {
    return float3(exp(((((thickness * absorb.x)) * (-1.0f)))), exp(((((thickness * absorb.y)) * (-1.0f)))), exp(((((thickness * absorb.z)) * (-1.0f)))));
}

static float4 fieldSampleFastArg(float2 uv, texture2d<float> field, float originX, float originY, float spanX, float spanY, float activeResF, float rBound) {
    const float uxc = clamp(uv.x, originX, ((originX + spanX)));
    const float uyc = clamp(uv.y, originY, ((originY + spanY)));
    const float outsideDist = length(float2(((uv.x - uxc)), ((uv.y - uyc))));
    const float px = ((((((((uxc - originX)) / spanX)) * activeResF)) - 0.5f));
    const float py = ((((((((uyc - originY)) / spanY)) * activeResF)) - 0.5f));
    const float x0 = floor(px);
    const float y0 = floor(py);
    const float fx = ((px - x0));
    const float fy = ((py - y0));
    const float maxT = ((activeResF - 1.0f));
    const uint cx0 = wgsl_f2u(clamp(x0, 0.0f, maxT));
    const uint cx1 = wgsl_f2u(clamp(((x0 + 1.0f)), 0.0f, maxT));
    const uint cy0 = wgsl_f2u(clamp(y0, 0.0f, maxT));
    const uint cy1 = wgsl_f2u(clamp(((y0 + 1.0f)), 0.0f, maxT));
    const float4 t00 = field.read(uint2(cx0, cy0), 0);
    const float4 t10 = field.read(uint2(cx1, cy0), 0);
    const float4 t01 = field.read(uint2(cx0, cy1), 0);
    const float4 t11 = field.read(uint2(cx1, cy1), 0);
    const float4 bl = mix(mix(t00, t10, fx), mix(t01, t11, fx), fy);
    const float rNear = ((bl.r + outsideDist));
    const float rCircle = ((length(float2(((uv.x - 0.5f)), ((uv.y - 0.5f)))) - rBound));
    const float rOut = mix(rNear, max(rCircle, rNear), smoothstep(0.0f, 0.25f, outsideDist));
    return float4(rOut, bl.g, bl.b, bl.a);
}

static float2 offsetUV(float2 uv, float ox, float oy) {
    return float2(((uv.x + ox)), ((uv.y + oy)));
}

static float3 volumetricNormal(float4 surf0, float4 surfX, float4 surfY, float eps, float gradClamp) {
    const float ddx = clamp(((((surfX.w - surf0.w)) / eps)), ((gradClamp * (-1.0f))), gradClamp);
    const float ddy = clamp(((((surfY.w - surf0.w)) / eps)), ((gradClamp * (-1.0f))), gradClamp);
    return normalize(float3(ddx, ddy, (-1.0f)));
}

static float2 patternCoords(float2 sdfUV, float4 surf0, float volumetric) {
    return float2(select(((sdfUV.x - 0.5f)), surf0.y, ((volumetric > 0.5f))), select(((sdfUV.y - 0.5f)), surf0.z, ((volumetric > 0.5f))));
}

static float2 flowWarpOffset(float2 warpInput, float flowT) {
    const float wx = ((sin(((((((warpInput.x * 1.7f)) + ((flowT * 0.7f)))) + 1.7f))) * cos(((((((warpInput.y * 1.3f)) + ((flowT * 0.5f)))) + 2.3f)))));
    const float wy = ((cos(((((((warpInput.x * 1.4f)) + ((flowT * 0.9f)))) + 8.7f))) * sin(((((((warpInput.y * 1.6f)) + ((flowT * 0.6f)))) + 5.1f)))));
    return float2(wx, wy);
}

static float mxFade(float t) {
    return ((((((t * t)) * t)) * ((((t * ((((t * 6.0f)) - 15.0f)))) + 10.0f))));
}

static uint mxRotl32(uint x, int k) {
    return ((((x << uint(k))) | ((x >> uint(((32 - k)))))));
}

static uint mxBjfinal(uint a0, uint b0, uint c0) {
    uint a = a0;
    uint b = b0;
    uint c = c0;
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 14)));
    a = ((a ^ c));
    a = ((a - mxRotl32(c, 11)));
    b = ((b ^ a));
    b = ((b - mxRotl32(a, 25)));
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 16)));
    a = ((a ^ c));
    a = ((a - mxRotl32(c, 4)));
    b = ((b ^ a));
    b = ((b - mxRotl32(a, 14)));
    c = ((c ^ b));
    c = ((c - mxRotl32(b, 24)));
    return c;
}

static uint mxHashInt1(int x, int y) {
    const uint len = 2u;
    const uint seed = ((((3735928559u + ((len << 2u)))) + 13u));
    const uint a = ((seed + uint(x)));
    const uint b = ((seed + uint(y)));
    return mxBjfinal(a, b, seed);
}

static float mxGradientFloat2(uint hash, float x, float y) {
    const uint h = ((hash & 7u));
    const float u = select(y, x, ((h < 4u)));
    const float v = ((2.0f * select(x, y, ((h < 4u)))));
    const float uu = select(u, (-(u)), ((((h & 1u)) != 0u)));
    const float vv = select(v, (-(v)), ((((h & 2u)) != 0u)));
    return ((uu + vv));
}

static float mxBilerp(float v0, float v1, float v2, float v3, float s, float t) {
    const float s1 = ((1.0f - s));
    return ((((((1.0f - t)) * ((((v0 * s1)) + ((v1 * s)))))) + ((t * ((((v2 * s1)) + ((v3 * s))))))));
}

static float mxGradientScale2d(float v) {
    return ((0.6616f * v));
}

static float mxPerlinNoiseFloat2(float2 p) {
    const int X = int(floor(p.x));
    const int Y = int(floor(p.y));
    const float fx = ((p.x - float(X)));
    const float fy = ((p.y - float(Y)));
    const float u = mxFade(fx);
    const float v = mxFade(fy);
    const float result = mxBilerp(mxGradientFloat2(mxHashInt1(X, Y), fx, fy), mxGradientFloat2(mxHashInt1(((X + 1)), Y), ((fx - 1.0f)), fy), mxGradientFloat2(mxHashInt1(X, ((Y + 1))), fx, ((fy - 1.0f))), mxGradientFloat2(mxHashInt1(((X + 1)), ((Y + 1))), ((fx - 1.0f)), ((fy - 1.0f))), u, v);
    return mxGradientScale2d(result);
}

static float mxNoiseFloat2(float2 p) {
    return mxPerlinNoiseFloat2(p);
}

static KeyLight keyLight(float lx, float ly, float lz) {
    const float3 L = normalize(float3(lx, ly, lz));
    const float3 H = normalize(((L + float3(0, 0, (-1)))));
    return KeyLight{L, H};
}

static float grazingView(float3 n) {
    return ((1.0f - clamp(((n.z * (-1.0f))), 0.0f, 1.0f)));
}

static float sharpGlint(float ndh, float sharp, float4 cfg) {
    return ((pow(ndh, mix(cfg.x, cfg.y, sharp)) * mix(cfg.z, cfg.w, sharp)));
}

static float insideMask(float sdf, float sharpEdge, float pxH, float minPixels) {
    const float w = max(((sharpEdge * 0.03125f)), ((pxH * minPixels)));
    return clamp(((((sdf * (-1.0f))) / w)), 0.0f, 1.0f);
}

static float silhouetteAlpha(float sdf, float edgeSoftness, float pxH) {
    const float sharpEdge = max(((edgeSoftness * 0.5f)), 1.0e-3f);
    return smoothstep(0.0f, 1.0f, insideMask(sdf, sharpEdge, pxH, 1.5f));
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}

static float3 rotateVec3(float3 v, RotStruct rot) {
    const float x1 = ((((v.x * rot.cy)) + ((v.z * rot.sy))));
    const float z1 = ((((v.z * rot.cy)) - ((v.x * rot.sy))));
    const float y2 = ((((v.y * rot.cx)) - ((z1 * rot.sx))));
    const float z2 = ((((v.y * rot.sx)) + ((z1 * rot.cx))));
    const float x3 = ((((x1 * rot.cz)) - ((y2 * rot.sz))));
    const float y3 = ((((x1 * rot.sz)) + ((y2 * rot.cz))));
    return float3(x3, y3, z2);
}

static float sdSphere(float3 p, float r) {
    return ((length(p) - r));
}

static float sdfFn(float3 p, constant MarchParams& params) {
    auto pp = ((&params));
    return sdSphere(p, ((*pp)).pA);
}

static float4 raymarchedField(float2 fuv, RotStruct rot, float rBound, constant MarchParams& params) {
    const float3 ro0 = float3(((fuv.x - 0.5f)), ((0.5f - fuv.y)), (-1.2f));
    const float3 rd0 = float3(0, 0, 1);
    const float3 ro = rotateVec3(ro0, rot);
    const float3 rd = rotateVec3(rd0, rot);
    const int steps = int(clamp(((rBound * 220.0f)), 96.0f, 384.0f));
    const float b = dot(ro, rd);
    const float perp = sqrt(max(((dot(ro, ro) - ((b * b)))), 0.0f));
    const float halfSpan = sqrt(max(((((rBound * rBound)) - ((perp * perp)))), 0.0f));
    const float tStart = max(((((b * (-1.0f))) - halfSpan)), 0.0f);
    const float tEnd = ((((((b * (-1.0f))) + halfSpan)) + 0.01f));
    float t = tStart;
    float tPrev = tStart;
    float minD = 10.0f;
    float hit = 0.0f;
    for (int i = 0; ((i < steps)); i++) {
        const float3 p = ((ro + ((rd * t))));
        const float dd = sdfFn(p, params);
        minD = min(minD, dd);
        if ((((dd < 0.0f)))) {
            hit = 1.0f;
            break;
        }
        if ((((t > tEnd)))) {
            break;
        }
        tPrev = t;
        t = ((t + max(dd, 2.0e-3f)));
    }
    float fieldVal = minD;
    float patternU = 0.0f;
    float patternV = 0.0f;
    float viewDepth = ((tEnd + 0.4f));
    if ((((hit > 0.5f)))) {
        float eLo = tPrev;
        float eHi = t;
        for (int i = 0; ((i < 10)); i++) {
            const float mid = ((((eLo + eHi)) * 0.5f));
            const float dm = sdfFn(((ro + ((rd * mid)))), params);
            if ((((dm > 0.0f)))) {
                eLo = mid;
            } else {
                eHi = mid;
            }
        }
        const float tEnter = ((((eLo + eHi)) * 0.5f));
        float tExit = tEnter;
        {
            const float3 roB = ((ro + ((rd * tEnd))));
            const float span = ((((tEnd - tStart)) + 0.01f));
            float s = 0.0f;
            float sPrev = 0.0f;
            for (int i = 0; ((i < steps)); i++) {
                const float3 p = ((roB - ((rd * s))));
                const float dd = sdfFn(p, params);
                if ((((dd < 0.0f)))) {
                    break;
                }
                if ((((s > span)))) {
                    break;
                }
                sPrev = s;
                s = ((s + max(dd, 2.0e-3f)));
            }
            float xLo = sPrev;
            float xHi = s;
            for (int i = 0; ((i < 10)); i++) {
                const float mid = ((((xLo + xHi)) * 0.5f));
                const float dm = sdfFn(((roB - ((rd * mid)))), params);
                if ((((dm > 0.0f)))) {
                    xLo = mid;
                } else {
                    xHi = mid;
                }
            }
            tExit = ((tEnd - ((((xLo + xHi)) * 0.5f))));
        }
        const float halfChord = ((max(((tExit - tEnter)), 0.0f) * 0.5f));
        fieldVal = ((halfChord * (-1.0f)));
        viewDepth = tEnter;
        {
            const float3 hp = ((ro + ((rd * tEnter))));
            patternU = ((hp.x + ((hp.z * 0.7f))));
            patternV = ((hp.y + ((hp.z * 0.5f))));
        }
    }
    return float4(fieldVal, patternU, patternV, viewDepth);
}

static void volumetricFieldMarch(uint cx, uint cy, texture2d<float, access::write> field_1, constant MarchParams& params) {
    auto p = ((&params));
    const float activeResF = float(((*p)).activeRes);
    const float2 uv = float2(((((*p)).originX + ((((((float(cx) + 0.5f)) / activeResF)) * ((*p)).spanX)))), ((((*p)).originY + ((((((float(cy) + 0.5f)) / activeResF)) * ((*p)).spanY)))));
    const float4 field = raymarchedField(uv, ((*p)).rot, ((*p)).rBound, params);
    field_1.write(field, uint2(cx, cy));
}
} // namespace S_Water

using namespace S_Water;

fragment float4 Water_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]], texture2d<float> compute_0 [[texture(0)]]) {
    float2 uv = in.uv;
    const float2 sdfUV_3 = sdfSpaceUV(uniforms.n_x.center, uniforms.n_x.scale, uniforms.n_x.rotation, uv, uniforms._sys.aspect);
    const float4 s0_2 = fieldSampleArg(sdfUV_3, compute_0, uniforms.n_x._vfOriginX, uniforms.n_x._vfOriginY, uniforms.n_x._vfSpanX, uniforms.n_x._vfSpanY, uniforms.n_x._vfActiveRes, uniforms.n_x._vfRBound);
    const float sdf_1 = ((s0_2.x / uniforms.n_x.scale));
    const float pxH_4 = ((1.0f / uniforms._sys.viewportSize.y));
    float4 water_0 = float4(0.0f, 0.0f, 0.0f, 0.0f);
    if ((((!(outsideShape(sdf_1, pxH_4)))))) {
        const float3 wc_7 = uniforms.n_x.waterColor.rgb;
        const float thickness_9 = ((opticalThickness(sdf_1, 1.0f) * uniforms.n_x.depth));
        const float depthT_8 = clamp(((thickness_9 * 1.3f)), 0.0f, 1.0f);
        const float3 transmit_10 = beerLambert(thickness_9, float3(((((1.0f - wc_7.x)) * 2.2f)), ((((1.0f - wc_7.y)) * 2.2f)), ((((1.0f - wc_7.z)) * 2.2f))));
        const float3 bodyTint_6 = ((((mix(mix(wc_7, float3(1.0f, 1.0f, 1.0f), float3(clamp(uniforms.n_x.shallows, 0.0f, 1.0f))), wc_7, float3(depthT_8)) * transmit_10)) + ((wc_7 * ((depthT_8 * 0.18f))))));
        const float4 sX_16 = fieldSampleFastArg(offsetUV(sdfUV_3, 0.01f, 0.0f), compute_0, uniforms.n_x._vfOriginX, uniforms.n_x._vfOriginY, uniforms.n_x._vfSpanX, uniforms.n_x._vfSpanY, uniforms.n_x._vfActiveRes, uniforms.n_x._vfRBound);
        const float4 sY_17 = fieldSampleFastArg(offsetUV(sdfUV_3, 0.0f, 0.01f), compute_0, uniforms.n_x._vfOriginX, uniforms.n_x._vfOriginY, uniforms.n_x._vfSpanX, uniforms.n_x._vfSpanY, uniforms.n_x._vfActiveRes, uniforms.n_x._vfRBound);
        const float3 nGeo_15 = volumetricNormal(s0_2, sX_16, sY_17, 0.01f, 5.0f);
        const float2 pat_20 = patternCoords(sdfUV_3, s0_2, 1.0f);
        const float freq_21 = ((uniforms.n_x.waveScale * 2.4f));
        const float2 q_19 = float2(((((pat_20.x * freq_21)) * 0.8f)), ((((pat_20.y * freq_21)) * 1.25f)));
        const float flowT_22 = ((uniforms.n_x._animTime * 0.2f));
        const float2 qw_18 = ((((q_19 + ((flowWarpOffset(((q_19 * 0.6f)), flowT_22) * ((uniforms.n_x.swirl * 0.9f)))))) + float2(0.0f, ((flowT_22 * (-1.0f))))));
        const float h0n1_23 = ((mxNoiseFloat2(qw_18) * 0.52f));
        const float relief_24 = ((uniforms.n_x.choppiness * 0.5f));
        const float2 qf_25 = ((((((qw_18 * 3.3f)) + float2(((flowT_22 * 1.7f)), ((flowT_22 * (-1.15f)))))) + float2(11.3f, 4.7f)));
        const float f0n1_26 = ((mxNoiseFloat2(qf_25) * 0.52f));
        const float reliefFine_27 = ((uniforms.n_x.choppiness * 0.22f));
        const float3 n_14 = normalize(float3(((((nGeo_15.x - ((clamp(((((((mxNoiseFloat2(((qw_18 + float2(0.06f, 0.0f)))) * 0.52f)) - h0n1_23)) / 0.06f)), (-4.0f), 4.0f) * relief_24)))) - ((clamp(((((((mxNoiseFloat2(((qf_25 + float2(0.025f, 0.0f)))) * 0.52f)) - f0n1_26)) / 0.025f)), (-4.0f), 4.0f) * reliefFine_27)))), ((((nGeo_15.y - ((clamp(((((((mxNoiseFloat2(((qw_18 + float2(0.0f, 0.06f)))) * 0.52f)) - h0n1_23)) / 0.06f)), (-4.0f), 4.0f) * relief_24)))) - ((clamp(((((((mxNoiseFloat2(((qf_25 + float2(0.0f, 0.025f)))) * 0.52f)) - f0n1_26)) / 0.025f)), (-4.0f), 4.0f) * reliefFine_27)))), nGeo_15.z));
        const float3 tDir_13 = refract(float3(0.0f, 0.0f, 1.0f), n_14, 0.7501875468867217f);
        const float2 env_28 = float2(cos(((uniforms.n_x.envRotation * 0.017453292519943295f))), sin(((uniforms.n_x.envRotation * 0.017453292519943295f))));
        const float transEy_12 = ((((tDir_13.x * env_28.y)) + ((tDir_13.y * env_28.x))));
        const float transUp_11 = clamp(((((transEy_12 * 0.5f)) + 0.5f)), 0.0f, 1.0f);
        const float sharp_30 = clamp(uniforms.n_x.sharpness, 0.0f, 1.0f);
        const float transSunRad_29 = mix(0.5f, 0.13f, sharp_30);
        const float transEx_31 = ((((tDir_13.x * env_28.x)) - ((tDir_13.y * env_28.y))));
        const float2 light_32 = float2(cos(((uniforms.n_x.lightAngle * 0.017453292519943295f))), sin(((uniforms.n_x.lightAngle * 0.017453292519943295f))));
        const KeyLight kl_34 = keyLight(light_32.x, light_32.y, (-0.7f));
        const float diffuse_33 = ((((pow(clamp(((((dot(n_14, kl_34.L) * 0.5f)) + 0.5f)), 0.0f, 1.0f), 0.8f) * 0.5f)) + 0.5f));
        const float causT_38 = ((uniforms.n_x._animTime * 3.0f));
        const float2 causP_37 = ((((float2(pat_20.x, pat_20.y) * uniforms.n_x.causticScale)) + float2(((sin(((causT_38 * 0.15f))) * 0.4f)), ((((causT_38 * 0.3f)) * (-1.0f))))));
        const float2 fbmC1_36 = causP_37;
        const float2 fbmC2_39 = ((((causP_37 * 1.9f)) + float2(3.7f, ((((causT_38 * 0.18f)) * (-1.0f))))));
        const float causV_35 = pow(clamp(((((((1.0f - abs(((((((mxNoiseFloat2(fbmC1_36) + ((mxNoiseFloat2(((((fbmC1_36 * 2.07f)) + float2(4.3f, 9.1f)))) * 0.5f)))) + ((mxNoiseFloat2(((((fbmC1_36 * 4.13f)) + float2(1.7f, 8.2f)))) * 0.25f)))) * 0.52f))))) * 0.6f)) + ((((1.0f - abs(((((((mxNoiseFloat2(fbmC2_39) + ((mxNoiseFloat2(((((fbmC2_39 * 2.07f)) + float2(4.3f, 9.1f)))) * 0.5f)))) + ((mxNoiseFloat2(((((fbmC2_39 * 4.13f)) + float2(1.7f, 8.2f)))) * 0.25f)))) * 0.52f))))) * 0.4f)))), 0.0f, 1.0f), 3.0f);
        const float causMask_40 = ((((((depthT_8 * 0.8f)) + 0.2f)) * uniforms.n_x.caustics));
        const float3 R_44 = reflect(float3(0.0f, 0.0f, 1.0f), n_14);
        const float reflEy_43 = ((((R_44.x * env_28.y)) + ((R_44.y * env_28.x))));
        const float reflUp_42 = clamp(((((reflEy_43 * 0.5f)) + 0.5f)), 0.0f, 1.0f);
        const float reflSunRad_45 = mix(0.5f, 0.13f, sharp_30);
        const float reflEx_46 = ((((R_44.x * env_28.x)) - ((R_44.y * env_28.y))));
        const float3 reflCol_41 = ((((mix(float3(0.04f, 0.1f, 0.16f), mix(float3(0.9f, 0.96f, 1.0f), float3(0.2f, 0.46f, 0.85f), float3(smoothstep(0.5f, 1.0f, reflUp_42))), float3(smoothstep(0.4f, 0.55f, reflUp_42))) + ((float3(1.0f, 0.97f, 0.88f) * ((smoothstep(reflSunRad_45, ((reflSunRad_45 * 0.15f)), length(((float2(reflEx_46, reflEy_43) - float2(((light_32.x * 0.8f)), ((((light_32.y * 0.8f)) + 0.12f))))))) * 1.5f)))))) * uniforms.n_x.reflection));
        const float grazing_47 = grazingView(n_14);
        const float2 fbmH0_50 = qw_18;
        const float h0_49 = ((((((mxNoiseFloat2(fbmH0_50) + ((mxNoiseFloat2(((((fbmH0_50 * 2.07f)) + float2(4.3f, 9.1f)))) * 0.5f)))) + ((mxNoiseFloat2(((((fbmH0_50 * 4.13f)) + float2(1.7f, 8.2f)))) * 0.25f)))) * 0.52f));
        const float foamMask_48 = ((clamp(((smoothstep(0.62f, 0.92f, clamp(((((h0_49 * 0.5f)) + 0.5f)), 0.0f, 1.0f)) + ((((1.0f - smoothstep(0.0f, 0.045f, ((sdf_1 * (-1.0f)))))) * 0.7f)))), 0.0f, 1.0f) * uniforms.n_x.foam));
        const float3 waterRgb_5 = mix(((mix(((((((mix(bodyTint_6, ((((((((mix(float3(0.04f, 0.1f, 0.16f), mix(float3(0.9f, 0.96f, 1.0f), float3(0.2f, 0.46f, 0.85f), float3(smoothstep(0.5f, 1.0f, transUp_11))), float3(smoothstep(0.4f, 0.55f, transUp_11))) + ((float3(1.0f, 0.97f, 0.88f) * ((smoothstep(transSunRad_29, ((transSunRad_29 * 0.15f)), length(((float2(transEx_31, transEy_12) - float2(((light_32.x * 0.8f)), ((((light_32.y * 0.8f)) + 0.12f))))))) * 1.5f)))))) * transmit_10)) * 0.6f)) + ((bodyTint_6 * 0.4f)))), float3(((clamp(uniforms.n_x.clarity, 0.0f, 1.0f) * ((1.0f - ((depthT_8 * 0.8f)))))))) * diffuse_33)) * ((1.0f + ((((causV_35 * causMask_40)) * 0.7f)))))) + ((float3(0.55f, 0.82f, 1.0f) * ((((causV_35 * causMask_40)) * 0.45f)))))), reflCol_41, float3(clamp(((0.04f + ((pow(grazing_47, 5.0f) * 0.96f)))), 0.0f, 1.0f))) + ((float3(1.0f, 0.98f, 0.92f) * sharpGlint(clamp(dot(n_14, kl_34.H), 0.0f, 1.0f), sharp_30, float4(40.0f, 600.0f, 0.3f, 1.3f)))))), float3(1.0f, 1.0f, 1.0f), float3(((foamMask_48 * 0.85f))));
        water_0 = float4(waterRgb_5, silhouetteAlpha(sdf_1, uniforms.n_x.edgeSoftness, pxH_4));
    }
    float4 composed_51 = water_0;
    return composed_51;
}

static void Water_k0_body(uint cx, uint cy, uint _arg_2, texture2d<float, access::write> field_1, constant MarchParams& params) {
    volumetricFieldMarch(cx, cy, field_1, params);
}

kernel void Water_k0(uint3 sk_gid [[thread_position_in_grid]], texture2d<float, access::write> field_1 [[texture(0)]], constant MarchParams& params [[buffer(0)]], constant uint3& sk_size [[buffer(1)]]) {
    if (any(sk_gid >= sk_size)) { return; }
    Water_k0_body(sk_gid.x, sk_gid.y, sk_gid.z, field_1, params);
}
