// Generated by wgsl2x from the shaders.com WGSL library — do not edit.
// Shader: Weave
#include <metal_stdlib>
using namespace metal;

struct SK_VertexOut { float4 position [[position]]; float2 uv; };

namespace S_Weave {
[[maybe_unused]] static inline int wgsl_isign(int x) { return (x > 0) - (x < 0); }
[[maybe_unused]] static inline int2 wgsl_isign(int2 x) { return int2((x > 0)) - int2((x < 0)); }
[[maybe_unused]] static inline int3 wgsl_isign(int3 x) { return int3((x > 0)) - int3((x < 0)); }
[[maybe_unused]] static inline int4 wgsl_isign(int4 x) { return int4((x > 0)) - int4((x < 0)); }
[[maybe_unused]] static inline uint wgsl_f2u(float x) { return uint(max(x, 0.0f)); }
[[maybe_unused]] static inline uint2 wgsl_f2u(float2 x) { return uint2(max(x, 0.0f)); }
[[maybe_unused]] static inline uint3 wgsl_f2u(float3 x) { return uint3(max(x, 0.0f)); }
[[maybe_unused]] static inline uint4 wgsl_f2u(float4 x) { return uint4(max(x, 0.0f)); }
struct CellTile {
    float2 cell;
    float2 local;
};

struct padded {
    float _opacity;
    float _pad0;
    float _pad1;
    float _pad2;
};

struct struct_1 {
    float4 colorA;
    float4 colorB;
    float cells;
    float gap;
    float rotation;
    float _opacity;
};

struct struct_2 {
    float time;
    float2 viewportSize;
    float2 logicalViewportSize;
    float aspect;
    float2 pointer;
    float pointerActive;
    char _sk_pad0[4];
};

struct combined {
    padded n_root;
    struct_1 n_x;
    struct_2 _sys;
};

static CellTile squareTiling(float2 p) {
    return CellTile{floor(p), fract(p)};
}

static float bandMask(float x, float lo, float hi) {
    return ((smoothstep(lo, hi, x) * smoothstep(lo, hi, ((1.0f - x)))));
}

static float flooredMod1(float x, float m) {
    return ((x - ((m * floor(((x / m)))))));
}

static float4 weaveColor(float2 scaledUV, float gap, float4 colorA, float4 colorB) {
    const CellTile tile = squareTiling(scaledUV);
    const float pixel = ((fwidth(scaledUV.x) * 0.5f));
    const float hBand = bandMask(tile.local.y, gap, ((gap + pixel)));
    const float vBand = bandMask(tile.local.x, gap, ((gap + pixel)));
    const float isHTopFloat = flooredMod1(((tile.cell.x + tile.cell.y)), 2.0f);
    const float intersection = ((hBand * vBand));
    const float hVis = clamp(((hBand - ((intersection * isHTopFloat)))), 0.0f, 1.0f);
    const float vVis = clamp(((vBand - ((intersection * ((1.0f - isHTopFloat)))))), 0.0f, 1.0f);
    const float weightA = ((colorA.w * hVis));
    const float weightB = ((colorB.w * vVis));
    const float totalAlpha = clamp(((weightA + weightB)), 0.0f, 1.0f);
    const float safeWeight = max(((weightA + weightB)), 1.0e-3f);
    const float r = ((((((colorA.x * weightA)) + ((colorB.x * weightB)))) / safeWeight));
    const float g = ((((((colorA.y * weightA)) + ((colorB.y * weightB)))) / safeWeight));
    const float b = ((((((colorA.z * weightA)) + ((colorB.z * weightB)))) / safeWeight));
    return float4(r, g, b, totalAlpha);
}

static float geom_aspectOf(float2 viewport) {
    return ((viewport.x / max(viewport.y, 1.0e-6f)));
}

static float2 rotateAboutCanvasCentre(float2 p, float aspect, float cosA, float sinA) {
    const float centerX = ((aspect * 0.5f));
    const float centerY = 0.5f;
    const float cx = ((p.x - centerX));
    const float cy = ((p.y - centerY));
    return float2(((((((cx * cosA)) - ((cy * sinA)))) + centerX)), ((((((cx * sinA)) + ((cy * cosA)))) + centerY)));
}

static float2 latticeFrame(float2 uv, float2 viewport, float cells, float rotationDeg) {
    const float aspect = geom_aspectOf(viewport);
    const float2 correctedUV = float2(((uv.x * aspect)), uv.y);
    const float rotRad = ((rotationDeg * 0.017453292519943295f));
    const float cosR = cos(rotRad);
    const float sinR = sin(rotRad);
    return ((rotateAboutCanvasCentre(correctedUV, aspect, cosR, sinR) * cells));
}

static float3 linearToSrgb(float3 color) {
    const float3 a = ((((pow(color, float3(0.41666001081466675f)) * 1.055f)) - 0.055f));
    const float3 b = ((color * 12.92f));
    const bool3 factor = ((color <= float3(0.0031308000907301903f)));
    return select(a, b, factor);
}

static float3 tone_linear(float3 color) {
    return float3(color.x, color.y, color.z);
}
} // namespace S_Weave

using namespace S_Weave;

fragment float4 Weave_v0_final(SK_VertexOut in [[stage_in]], constant combined& uniforms [[buffer(0)]]) {
    float2 uv = in.uv;
    float4 composed_0 = weaveColor(latticeFrame(uv, uniforms._sys.viewportSize, uniforms.n_x.cells, uniforms.n_x.rotation), uniforms.n_x.gap, uniforms.n_x.colorA, uniforms.n_x.colorB);
    return composed_0;
}
