// Generates the typed Swift layer structs (one per shader) from a descriptor.

const SWIFT_KEYWORDS = new Set([
    'associatedtype', 'class', 'deinit', 'enum', 'extension', 'fileprivate', 'func', 'import', 'init', 'inout', 'internal', 'let', 'open', 'operator',
    'private', 'precedencegroup', 'protocol', 'public', 'rethrows', 'static', 'struct', 'subscript', 'typealias', 'var', 'break', 'case', 'catch',
    'continue', 'default', 'defer', 'do', 'else', 'fallthrough', 'for', 'guard', 'if', 'in', 'repeat', 'return', 'throw', 'switch', 'where', 'while',
    'Any', 'as', 'await', 'false', 'is', 'nil', 'self', 'Self', 'super', 'throws', 'true', 'try', 'some', 'any', 'Type', 'description', 'node', 'layer', 'children',
])

export function swiftIdent(name: string): string {
    return SWIFT_KEYWORDS.has(name) ? `\`${name}\`` : name
}

export function caseName(value: string): string {
    const parts = value.split(/[^A-Za-z0-9]+/).filter(Boolean)
    if (!parts.length) return 'none'
    let s = parts.map((p, i) => (i === 0 ? p.charAt(0).toLowerCase() + p.slice(1) : p.charAt(0).toUpperCase() + p.slice(1))).join('')
    // keep all-caps acronyms readable (e.g. "HSL" → "hsl")
    if (/^[A-Z0-9]+$/.test(parts[0])) s = parts[0].toLowerCase() + parts.slice(1).map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('')
    if (/^[0-9]/.test(s)) s = `_${s}`
    return SWIFT_KEYWORDS.has(s) ? `\`${s}\`` : s
}

function typeName(name: string): string {
    const n = name.replace(/[^A-Za-z0-9]/g, '')
    return n.charAt(0).toUpperCase() + n.slice(1)
}

function swiftString(s: string): string {
    if (/["\\\n]/.test(s)) {
        // raw string literal; pick enough # to be safe
        let hashes = '#'
        while (s.includes(`"${hashes}`)) hashes += '#'
        return `${hashes}"${s}"${hashes}`
    }
    return `"${s}"`
}

function swiftFloat(v: number): string {
    if (Number.isInteger(v)) return `${v}`
    return `${v}`
}

export const SHARED: Record<string, string> = {
    '["linear","oklch","oklab","hsl","hsv","lch"]': 'ColorSpace',
    '["stretch","transparent","mirror","wrap"]': 'EdgeMode',
    '["outside","center","inside"]': 'StrokePosition',
    '["cover","contain","fill","scale-down"]': 'ObjectFit',
}

export function sharedEnumSwift(_descs: any[]): {source: string; sharedByOptions: Map<string, string>} {
    const map = new Map<string, string>(Object.entries(SHARED))
    const source = `// Generated by wgsl2x — do not edit.
// Shared option enums live in Model/LayerModel.swift (ColorSpace, EdgeMode, StrokePosition, ObjectFit, ShaderOrigin).
import Foundation

/// Marker protocol for generated option enums.
public protocol ShaderOptionEnum: RawRepresentable, CaseIterable, Hashable, Sendable where RawValue == String {}

extension ColorSpace: ShaderOptionEnum {}
extension EdgeMode: ShaderOptionEnum {}
extension StrokePosition: ShaderOptionEnum {}
extension ObjectFit: ShaderOptionEnum {}
extension ShaderOrigin: ShaderOptionEnum {}
`
    return {source, sharedByOptions: map}
}

interface PlanField {
    name: string
    swiftName: string
    type: string
    defaultExpr: string
    toItem: string
}

export interface PropPlan {
    name: string
    swiftName: string
    type: string
    defaultExpr: string
    toPropValue: string
    nestedEnum?: {name: string; options: {label: string; value: string}[]}
    nestedItem?: {name: string; fields: PlanField[]}
}

function positionExpr(def: any): string {
    const axis = (v: any): string => {
        if (typeof v === 'number') return `.number(${swiftFloat(v)})`
        if (typeof v === 'string') return `.keyword(${swiftString(v)})`
        if (v && typeof v === 'object' && typeof v.value === 'number') return `.dimensional(DimensionalValue(value: ${swiftFloat(v.value)}, unit: .${v.unit === 'px' ? 'px' : 'uv'}))`
        return `.number(0.5)`
    }
    if (typeof def === 'string') return `.keyword(${swiftString(def)})`
    if (def && typeof def === 'object' && 'x' in def) {
        if (typeof def.x === 'number' && typeof def.y === 'number') return `ShaderPosition(x: ${swiftFloat(def.x)}, y: ${swiftFloat(def.y)})`
        return `ShaderPosition(x: ${axis(def.x)}, y: ${axis(def.y)})`
    }
    return '.center'
}

function dimensionalExpr(def: any): string {
    if (typeof def === 'number') return swiftFloat(def)
    if (def && typeof def === 'object' && typeof def.value === 'number') return `DimensionalValue(value: ${swiftFloat(def.value)}, unit: .${def.unit === 'px' ? 'px' : 'uv'})`
    return '0'
}

export function planProp(p: any, shader: string, shared: Map<string, string>): PropPlan {
    const name: string = p.name
    const swiftName = swiftIdent(name)
    const t = p.transform
    const ui = p.ui ?? {types: []}
    const types: string[] = ui.types ?? []
    const def = p.defaultValue
    const enumFor = (): PropPlan => {
        const key = JSON.stringify((ui.options ?? []).map((o: any) => o.value))
        const sharedName = shared.get(key)
        const enumName = sharedName ?? typeName(name)
        const defaultCase = typeof def === 'string' ? caseName(def) : caseName(String(ui.options?.[0]?.value ?? 'none'))
        return {
            name, swiftName, type: enumName, defaultExpr: `.${defaultCase}`, toPropValue: `.string(${swiftName}.rawValue)`,
            nestedEnum: sharedName ? undefined : {name: enumName, options: ui.options ?? []},
        }
    }
    switch (t.kind) {
        case 'color': return {name, swiftName, type: 'ShaderColor', defaultExpr: swiftString(typeof def === 'string' ? def : '#000000'), toPropValue: `${swiftName}.propValue`}
        case 'position': return {name, swiftName, type: 'ShaderPosition', defaultExpr: positionExpr(def), toPropValue: `${swiftName}.propValue`}
        case 'angle': {
            if (typeof def === 'string') return {name, swiftName, type: 'String', defaultExpr: swiftString(def), toPropValue: `.string(${swiftName})`}
            return {name, swiftName, type: 'Float', defaultExpr: swiftFloat(typeof def === 'number' ? def : 0), toPropValue: `.number(${swiftName})`}
        }
        case 'edges': return {name, swiftName, type: 'EdgeMode', defaultExpr: `.${caseName(String(def ?? 'stretch'))}`, toPropValue: `.string(${swiftName}.rawValue)`}
        case 'colorSpace': return {name, swiftName, type: 'ColorSpace', defaultExpr: `.${caseName(String(def ?? 'linear'))}`, toPropValue: `.string(${swiftName}.rawValue)`}
        case 'strokePosition': return {name, swiftName, type: 'StrokePosition', defaultExpr: `.${caseName(String(def ?? 'center'))}`, toPropValue: `.string(${swiftName}.rawValue)`}
        case 'boolean': case 'booleanTable': return {name, swiftName, type: 'Bool', defaultExpr: def ? 'true' : 'false', toPropValue: `.bool(${swiftName})`}
        case 'colorStops': return {name, swiftName, type: '[ColorStop]?', defaultExpr: 'nil', toPropValue: `${swiftName}.map { PropValue.colorStops($0) } ?? .null`}
        case 'list': {
            const itemName = typeName(ui.itemLabel ?? name.replace(/s$/, ''))
            const fields = (ui.item ?? []).map((f: any) => {
                const fname = swiftIdent(f.name)
                switch (f.kind) {
                    case 'position': return {name: f.name, swiftName: fname, type: 'ShaderPosition', defaultExpr: positionExpr(f.defaultValue), toItem: `.position(${fname}.input)`}
                    case 'color': return {name: f.name, swiftName: fname, type: 'ShaderColor', defaultExpr: swiftString(typeof f.defaultValue === 'string' ? f.defaultValue : '#ffffff'), toItem: `.string(${fname}.css)`}
                    case 'boolean': return {name: f.name, swiftName: fname, type: 'Bool', defaultExpr: f.defaultValue ? 'true' : 'false', toItem: `.bool(${fname})`}
                    default: return {name: f.name, swiftName: fname, type: 'Float', defaultExpr: swiftFloat(typeof f.defaultValue === 'number' ? f.defaultValue : 0), toItem: `.number(${fname})`}
                }
            })
            const itemsDefault = Array.isArray(def) ? `[${def.map((item: Record<string, unknown>) => `${itemName}(${fields.map((f: {name: string; swiftName: string; type: string; defaultExpr: string}) => {
                const v = item?.[f.name]
                let expr = f.defaultExpr
                if (v !== undefined && v !== null) {
                    if (f.type === 'ShaderPosition') expr = positionExpr(v)
                    else if (f.type === 'ShaderColor') expr = swiftString(String(v))
                    else if (f.type === 'Bool') expr = v ? 'true' : 'false'
                    else expr = swiftFloat(Number(v))
                }
                return `${f.swiftName}: ${expr}`
            }).join(', ')})`).join(', ')}]` : '[]'
            return {name, swiftName, type: `[${itemName}]`, defaultExpr: itemsDefault, toPropValue: `.list(${swiftName}.map { $0.listItem })`, nestedItem: {name: itemName, fields}}
        }
        case 'select': return enumFor()
        default: {
            if (types.includes('origin')) return {name, swiftName, type: 'ShaderOrigin', defaultExpr: `.${caseName(String(def ?? 'center'))}`, toPropValue: `.string(${swiftName}.rawValue)`}
            if (Array.isArray(ui.options) && ui.options.length && typeof def === 'string') return enumFor()
            if (typeof def === 'boolean') return {name, swiftName, type: 'Bool', defaultExpr: def ? 'true' : 'false', toPropValue: `.bool(${swiftName})`}
            if (typeof def === 'number' || (def && typeof def === 'object' && typeof def.value === 'number')) {
                const dimensional = (Array.isArray(ui.units) && ui.units.includes('px')) || !!ui.dimensional || (def && typeof def === 'object')
                if (dimensional) return {name, swiftName, type: 'DimensionalValue', defaultExpr: dimensionalExpr(def), toPropValue: `${swiftName}.propValue`}
                return {name, swiftName, type: 'Float', defaultExpr: swiftFloat(def as number), toPropValue: `.number(${swiftName})`}
            }
            if (typeof def === 'string') return {name, swiftName, type: 'String', defaultExpr: swiftString(def), toPropValue: `.string(${swiftName})`}
            if (def && typeof def === 'object' && 'x' in def) return {name, swiftName, type: 'ShaderPosition', defaultExpr: positionExpr(def), toPropValue: `${swiftName}.propValue`}
            if (def === null && types.includes('gradient-stops')) return {name, swiftName, type: '[ColorStop]?', defaultExpr: 'nil', toPropValue: `${swiftName}.map { PropValue.colorStops($0) } ?? .null`}
            return {name, swiftName, type: 'PropValue', defaultExpr: '.null', toPropValue: swiftName}
        }
    }
}

export function generateLayerSwift(desc: any, shared: Map<string, string>): string {
    const name: string = desc.name
    const plans = desc.props.map((p: any) => planProp(p, name, shared))
    const acceptsChildren = desc.flags.requiresChild || desc.flags.acceptsOptionalChild || desc.role === 'structural'
    const lines: string[] = []
    lines.push(`// Generated by wgsl2x from the shaders.com library — do not edit.`)
    lines.push(`import Foundation`)
    lines.push(``)
    const doc = (desc.description ?? name).replace(/\n/g, ' ')
    lines.push(`/// ${doc}`)
    lines.push(`///`)
    lines.push(`/// Category: ${desc.category ?? '—'} · Role: ${desc.role}${acceptsChildren ? ' · wraps child layers' : ''}${desc.flags.hasCompute ? ' · compute-backed' : ''}`)
    lines.push(`public struct ${name}: ShaderLayer, Equatable, Sendable {`)
    // nested enums / item structs
    const seenEnums = new Set<string>()
    for (const pl of plans) {
        if (pl.nestedEnum && !seenEnums.has(pl.nestedEnum.name)) {
            seenEnums.add(pl.nestedEnum.name)
            lines.push(`    public enum ${pl.nestedEnum.name}: String, ShaderOptionEnum {`)
            const used = new Set<string>()
            for (const o of pl.nestedEnum.options) {
                let c = caseName(o.value)
                while (used.has(c)) c = `${c}_`
                used.add(c)
                const raw = o.value
                lines.push(`        /// ${o.label}`)
                lines.push(c.replace(/`/g, '') === raw ? `        case ${c}` : `        case ${c} = ${swiftString(raw)}`)
            }
            lines.push(`    }`)
        }
        if (pl.nestedItem) {
            lines.push(`    public struct ${pl.nestedItem.name}: Equatable, Sendable {`)
            for (const f of pl.nestedItem.fields) lines.push(`        public var ${f.swiftName}: ${f.type}`)
            lines.push(`        public init(${pl.nestedItem.fields.map((f: PlanField) => `${f.swiftName}: ${f.type} = ${f.defaultExpr}`).join(', ')}) {`)
            for (const f of pl.nestedItem.fields) lines.push(`            self.${f.swiftName} = ${f.swiftName}`)
            lines.push(`        }`)
            lines.push(`        public var listItem: [String: ListItemValue] {`)
            lines.push(`            [${pl.nestedItem.fields.map((f: PlanField) => `${swiftString(f.name)}: ${f.toItem}`).join(', ')}]`)
            lines.push(`        }`)
            lines.push(`    }`)
        }
    }
    lines.push(``)
    for (const pl of plans) {
        const pd = desc.props.find((p: any) => p.name === pl.name)
        if (pd?.description) lines.push(`    /// ${String(pd.description).replace(/\n/g, ' ')}`)
        lines.push(`    public var ${pl.swiftName}: ${pl.type}`)
    }
    lines.push(`    /// Blend mode, opacity, mask, id and transform.`)
    lines.push(`    public var layer: LayerAttributes`)
    if (acceptsChildren) lines.push(`    public var children: [ShaderNode]`)
    lines.push(``)
    // init
    const params = plans.map((pl: PropPlan) => `${pl.swiftName}: ${pl.type} = ${pl.defaultExpr}`)
    const initParams = [...params, `layer: LayerAttributes = LayerAttributes()`]
    const assigns = plans.map((pl: PropPlan) => `        self.${pl.swiftName} = ${pl.swiftName}`)
    if (acceptsChildren) {
        lines.push(`    public init(${[...initParams, `@ShaderLayerBuilder content: () -> [ShaderNode] = { [] }`].join(', ')}) {`)
        lines.push(...assigns)
        lines.push(`        self.layer = layer`)
        lines.push(`        self.children = content()`)
        lines.push(`    }`)
    } else {
        lines.push(`    public init(${initParams.join(', ')}) {`)
        lines.push(...assigns)
        lines.push(`        self.layer = layer`)
        lines.push(`    }`)
    }
    lines.push(``)
    lines.push(`    public static let typeName = ${swiftString(name)}`)
    lines.push(`    public static var descriptor: ShaderDescriptor? { ShaderRegistry.descriptor(typeName) }`)
    lines.push(``)
    lines.push(`    public var node: ShaderNode {`)
    if (plans.length === 0) {
        lines.push(`        ShaderNode(type: Self.typeName, props: [:], children: ${acceptsChildren ? 'children' : '[]'}, attributes: layer)`)
    } else {
        lines.push(`        ShaderNode(type: Self.typeName, props: [`)
        for (const pl of plans) lines.push(`            ${swiftString(pl.name)}: ${pl.toPropValue},`)
        lines.push(`        ], children: ${acceptsChildren ? 'children' : '[]'}, attributes: layer)`)
    }
    lines.push(`    }`)
    lines.push(`}`)
    lines.push(``)
    return lines.join('\n')
}
